### ISSUE TITLE
"No handler found" error in contentprovider extension

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode-extension-samples#1]
I copied contentprovider-sample as is to my .vscode/extensions folder and when trying to run, I get:

    No handler found for the command: 'editor.printReferences'. An extension might be missing an activation event.

**Comment by cfjedimaster** [comment]
Just an issue of me not compiling the extension, but I'd add a note in the readme to make it clear for folks that this step is necessary. Remember that these samples are for folks learning, so this step is something they could forget.

**Comment by jrieken** [comment]
@cfjedimaster what readme.md do you prefer? The one at the root level, or those at the project level, or both?

**Comment by cfjedimaster** [comment]
I think both should have it (assuming all the samples need the same), or have the readme here point folks to the root one.
