### ISSUE TITLE
Contributing guide could be improved with getting started section for bugs and issues

### ISSUE THREAD

**Issue by AlexanderSambale** [microsoft/vscode-extension-samples#1028]
### Extension sample

general

### VS Code version

1.89.1

### What went wrong?

- I wanted to follow the contribution guidlines for reporting an issue.
- There is no getting started section for issues and bugs.
- It could look similar to [.github/CONTRIBUTING.md](https://github.com/github/docs/blob/a107d854397cc1a346fa011fd1d5dc0a573a2d3f/.github/CONTRIBUTING.md).

**Comment by mjbvz** [comment]
What are you suggesting?

**Comment by AlexanderSambale** [comment]
It depends a bit on what your contribution workflow should look like:

What would be your best practice for opening an issue? 
What should I read before creating a new one?
When should I create a PR?
Should I ask in an issue before create a PR?

I would like it to be similar to the sections "Getting Started > Issues, Make Changes" in [.github/CONTRIBUTING.md](https://github.com/github/docs/blob/a107d854397cc1a346fa011fd1d5dc0a573a2d3f/.github/CONTRIBUTING.md).

I think it would reduce the barrier for someone to contribute.

**Comment by mjbvz** [comment]
We have issue templates to guide folks in the right direction and you can see the [sample guidelines](https://github.com/microsoft/vscode-extension-samples/blob/main/.github/SAMPLE_GUIDELINE.md) if you're interested in creating a new sample

You're welcome to add extra documentation if you think it would help others
