### ISSUE TITLE
wasm:lose an example of a function with a return type of string

### ISSUE THREAD

**Issue by liluyue** [microsoft/vscode-extension-samples#1029]
### Extension sample

wasm-component-model

### VS Code version

*

### What went wrong?

I am using Rust to develop a vscode plugin based on Wasm, but when the function return type is string, JavaScript always fails to receive results. May I ask if there is an example of **a function with a return type of string in wit** that you can refer to

**Comment by dbaeumer** [comment]
@liluyue this is actually a bug in the component model. Will fix it and release a new version and ping here when available.

**Comment by dbaeumer** [comment]
I published a new version of the component model: 0.1.0-pre.13
