### ISSUE TITLE
lsp-sample: Error: connect ECONNREFUSED 127.0.0.1:6009 when trying to attach to server

### ISSUE THREAD

**Issue by tom-sherman** [Microsoft/vscode-extension-samples#103]
```
Node v10.9.0
VSCode 1.27.2
macOS High Sierra
```

I get the following error when I try to debug the server in Vscode after starting the client.

```
Debugging with inspector protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:6009)
```

Then after several seconds I get this timeout message:

```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:6009).
```

I've tried changing the port with no luck. Any ideas?

**Update:** Looks like other packages have had similar issues, see https://github.com/Microsoft/vscode-azurefunctions/issues/387

On further inspection, it doesn't look like the server is starting at all. I can't see the process and the example language server isn't working at all.

**Comment by tom-sherman** [comment]
Turns out I need to activate the server by opening a text document from the disk.

**Comment by JohnArcher** [comment]
Life saver, thanks a lot for posting the solution!
