### ISSUE TITLE
github.copilot-chat/1/gpt-3.5-turbo' errored, check cause for more details Unknown Error: Sorry, this message is too long. Please try a shorter question.

### ISSUE THREAD

**Issue by zhuweid** [microsoft/vscode-extension-samples#1046]
### Extension sample

chat-sample

### VS Code version

1.91.0-insider

### What went wrong?

even the message is just "hi", it still throws the following error:

Language model 'github.copilot-chat/1/gpt-3.5-turbo' errored, check cause for more details Unknown Error: Sorry, this message is too long. Please try a shorter question.
    at Je.render (c:\Users\\.vscode-insiders\extensions\github.copilot-chat-0.16.2024060502\dist\extension.js:766:3606)
    at processTicksAndRejections (C:\Hack\vscode-extension-samples\chat-sample\lib\internal\process\task_queues.js:95:5)

**Comment by aberridg** [comment]
I also have this issue - any hints?

**Comment by fls1wi** [comment]
Hello i had the same issue, i switched to Github copilot pre-release version and than it worked.

**Comment by isidorn** [comment]
Sorry about the slow response. 
This should be fixed in latest, please let me know if you still see issues with this and we can reopen. Thanks
