### ISSUE TITLE
emoji is not shown

### ISSUE THREAD

**Issue by zongou** [microsoft/vscode-extension-samples#1098]
### Extension sample

notebook-extend-markdown-renderer-sample

### VS Code version

1.93.0

## Open sample dir
```sh
code -r /media/user/RD20/repos/vscode-extension-samples/notebook-extend-markdown-renderer-sample
```
## Install dependencies
```sh
npm install
```
## Launch extension
Run `Launch Extension` and this opens a new window

## Open a markdown file to test
```markdown
:smile:
```

**Comment by mjbvz** [comment]
> Open a markdown file to test

This is meant to work for markdown cells in notebooks, not in plain markdown files:

![Image](https://github.com/user-attachments/assets/c1a2830b-698d-4082-b7d7-a9f5ec44aac4)

Just tested the sample and it seems to be working fine for that
