### ISSUE TITLE
Missing good test examples

### ISSUE THREAD

**Issue by aristotelos** [microsoft/vscode-extension-samples#1112]
### Extension sample

helloworld-test-sample

### VS Code version

1.94.2

### What went wrong?

The current test examples in `helloworld-test-sample` are far too simple, and does not illustrate how the vscode API should be used for integration testing.

I myself am struggling to find examples of the following:

- How to activate the extension via the VS Code API? I could find this in another extension sample: https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-log-streaming-sample/client/src/test/completion.test.ts, but it should be part of helloworld-test-sample
- How to assert something about the contents of an Output console window?
- How to assert something about the contents of a Test Results console window?
- How to assert something about parts of the VS Code window, for instance the Test Runner window?

**Comment by connor4312** [comment]
The VS Code API, vscode.d.ts, is what you get. Some of those things can be introspected, others cannot be and can be mocked using your choice of mocking library.
