### ISSUE TITLE
Adding a search text input to sidebar extension

### ISSUE THREAD

**Issue by GabrielBB** [Microsoft/vscode-extension-samples#113]
How can I add a Search input to a tree view container extension, something similar to the extension explorer? Like this:

![image](https://user-images.githubusercontent.com/8752823/47718425-c65e5280-dc1e-11e8-98c3-d955b7e60917.png)

**Comment by sandy081** [comment]
This is not supported.

**Comment by OlafCheng** [comment]
> This is not supported.

does it support now?

**Comment by Delizald** [comment]
Yeah, same question here as @OlafCheng. Trying to build a tree view extension with quick picks and a search box.

**Comment by KamasamaK** [comment]
The correct place to check if something is supported is the VS Code documentation or vscode repo. 

For tree views, that feature request was closed microsoft/vscode#50062

There are some newer open ones that are similar, though. I found: microsoft/vscode#70646 and microsoft/vscode#97190

**Comment by nmhungdev** [comment]
any update?
