### ISSUE TITLE
How to get back the HTML from previewHTML?

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode-extension-samples#12]
I have successfully implemented an interactive network graphic using D3 and the previewHTML feature. This is pretty cool, many thanks for that.

However, how would I read out the generated svg to e.g. to store it on disk? Is it possible to read back what is currently in the preview?

**Comment by Tyriar** [comment]
Moved to https://github.com/Microsoft/vscode/issues/23897
