### ISSUE TITLE
Configuration sample has errors

### ISSUE THREAD

**Issue by diberry** [Microsoft/vscode-extension-samples#128]
I cloned today and ran the configuration sample. It did run but there were errors. Since I figured out what I needed, I didn't track it down much further. 

![vscode-extension-configuration-error](https://user-images.githubusercontent.com/41597107/49489273-0ce73400-f7ff-11e8-8ec5-5d5d8c2a5fbb.PNG)

**Comment by diberry** [comment]
@sandy081 Why did you close this without explanation or help?

**Comment by KamasamaK** [comment]
@diberry It was closed automatically via commit 8785872. The issue was that the minimum version of VS Code was too low since this sample used properties introduced in later versions.

**Comment by diberry** [comment]
@KamasamaK Thank you for explaining. :)
