### ISSUE TITLE
Windows Security detects examples as virus

### ISSUE THREAD

**Issue by jokervTv** [microsoft/vscode-extension-samples#129]
When I download the zip file,  the Windows Security delete it and I get this:

![image](https://user-images.githubusercontent.com/29646575/49955628-3cecb080-ff3e-11e8-8075-c18e7741023a.png)

I know it is a mistake, but a little funny.

The samples are great, and I love the VS Code. Thanks for your working.

Have a good day.

**Comment by mjbvz** [comment]
Is this still happening?

**Comment by jokervTv** [comment]
oh no, it work well

thanks
