### ISSUE TITLE
[tree-explorer] is there a way to customize node ?

### ISSUE THREAD

**Issue by fforjan** [Microsoft/vscode-extension-samples#13]
Abilitity to have some icons, tooltip or give basic label text styles - italic, bold are the one I'm looking after.

What's the proposal for context menu ? invoke an action with a quick pick ? Or do you have anything in mind ?

**Comment by Tyriar** [comment]
Features requests should be created in the main repo https://github.com/Microsoft/vscode/issues/new

I recommend holding off on addition issues around this request until https://github.com/Microsoft/vscode/issues/15485 is resolved.
