### ISSUE TITLE
How can language server list all file names in one workspace folder?

### ISSUE THREAD

**Issue by sumneko** [Microsoft/vscode-extension-samples#132]
I'm sorroy my ENGLISH and JS is pool.
I have read the document and my understanding is that server should not read file in workspace, but I can't find any protocol to request client to do that.
I have read some other extensions then found that their servers readlly used filesystem to list files by themself.

So should my server list files by myself, or there is some way I missed?

**Comment by dbaeumer** [comment]
Servers are allowed to read file from disk that are NOT open in the editor. The editor signals the open with a corresponding `textDocument/open` notification.
