### ISSUE TITLE
example of color changes other than decorator

### ISSUE THREAD

**Issue by oreporan** [Microsoft/vscode-extension-samples#146]
I'm trying to build an extension that changes the color of the active tab, or the title bar for example.
I can't find an example that shows this.

Is the only way to do this by changing the workspace settings? or is there an API for this?

**Comment by aeschli** [comment]
All colors are owned by the current theme. You can override them in the settings, but you would have to find a solution that works nicely with all possible themes (light, dark, high contrast, works well with the theme colors...) 

The API to change the settings is workspace.getConfiguration('workbench.colorCustomizations").get/set;
You would get the existing setting, add your property, and write it back.

I'm not sure that this is a common use case so I don't think this should be added to the samples. Better to ask and discuss such things on stackoverflow or in our slack channels.
