### ISSUE TITLE
tree-explorer-sample: registerTreeExplorerNodeProvider is not a function.

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode-extension-samples#15]
Trying to run the tree explorer sample with latest Insider's (https://github.com/Microsoft/vscode/commit/c615b43be67170e166779c9020a249442c4f36fc) throws the following error:

>Activating extension `octref.dep` failed: vscode.window.registerTreeExplorerNodeProvider is not a function.

Probably caused by these recent changes: https://github.com/Microsoft/vscode/commit/ccae6f96efd7c4e5598c37210e0c970e1ee18da2

**Comment by Tyriar** [comment]
I know there are changes being made to the API in question. The `--enable-proposed-api <ext>` CLI arg was also added recently, I think yo need to explicitly opt in to proposed APIs when launching VS Code Insiders.

**Comment by sandy081** [comment]
@Gama11 I am actively working on this API and doing changes. I will also update this sample as per new changes.

**Comment by Gama11** [comment]
Looks like the sample is in sync with the changed API again. :)
