### ISSUE TITLE
Debugging: fsprovider-sample and launch.json

### ISSUE THREAD

**Issue by moxonj** [Microsoft/vscode-extension-samples#153]
Looking at the **fsprovider-sample**

Is it possible to easily use the registered file system to debug with Node? 

I thought a launch.json with the following contents might work but I get "Attribute program is not absolute (memfs:/file.js); consider adding ${workspaceFolder}/ as a prefix to make it absolute"

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "memfs:/file.js"
    }
}
```

Many thanks

**Comment by jrieken** [comment]
I don't think that's possible because node doesn't know how to load the menfs-file. Adding @weinand for more insights

**Comment by weinand** [comment]
The  Code node debugger extension does not support URIs where paths are expected.

**Comment by roblourens** [comment]
If you can't run `node xyz` in a terminal then it's not really feasible to support this in the debug adapter.

The Chrome debugger may or may not work, where sourcemaps come from, etc.
