### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rafaelsous** [Microsoft/vscode-extension-samples#155]
- Issue Type: `Performance`
- Extension Name: `qlk-vscode`
- Extension Version: `0.1.4`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/rafael/ash9g.qlk-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Tyriar** [comment]
You should report against https://marketplace.visualstudio.com/items?itemName=ash9g.qlk-vscode, not this repo?
