### ISSUE TITLE
Any plan for a simple Tree View sample with JSON data as menu

### ISSUE THREAD

**Issue by systemaker** [Microsoft/vscode-extension-samples#159]
Hello,
I am looking for a simple tiny example of a simple TreeView filled by a short JSON data for a very cute simple menu.
Sorry but you know, life is too short to try to understand the other TreeProviders :D
Thanks for your help

**Comment by sandy081** [comment]
This view - https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/testView.ts is based on json data.

**Comment by systemaker** [comment]
So when will we get in vscode production version ( not in vscode.proposed.d.ts ) the **TreeItem2** class from TestView example ?

**Comment by sandy081** [comment]
https://github.com/Microsoft/vscode/issues/61579
