### ISSUE TITLE
testing not working with webpack bundling

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-extension-samples#163]
I tried the new bundling feature and it runs fine ... but tests are not working. I tried using your launch config here, but it yields the following error
https://github.com/Microsoft/vscode-extension-samples/blob/master/webpack-sample/.vscode/launch.json#L18-L31

`Error: Error: Cannot find module '/Users/papa/_git/vscode-peacock/out/test'`

I also tried running it with npm scripts, but that did not work. I noticed that your sample does not have a npm script for test either.

How do we get testing to work?

**Comment by johnpapa** [comment]
I got testing to work by compiling both with `tsc` and with webpack. I think this is what y'all intended. Is that right

**Comment by KamasamaK** [comment]
Some discussion of this at Microsoft/vscode-docs#2254

**Comment by johnpapa** [comment]
Perfect. I’ll close this and go read that thread. Thank you.
