### ISSUE TITLE
[tree-view-example]Is there a way to give same icon as the activated iconTheme?

### ISSUE THREAD

**Issue by leftstick** [Microsoft/vscode-extension-samples#17]
Let's take the `FTP Explorer` for instance, the resources being displayed are `folder`, `.js`, `.gz`, `.html`, `.ico`, `.json`....

I have an iconTheme activated, so i want to display the corresponding icon in `FTP Explorer` depends on the resource "type", is it possible?

**Comment by sandy081** [comment]
Yes this is being considered. Please follow the item https://github.com/Microsoft/vscode/issues/27823

**Comment by leftstick** [comment]
@sandy081  Thanks for the information
