### ISSUE TITLE
Sample language client shows "config" as an other icon in auto complete.

### ISSUE THREAD

**Issue by sumneko** [Microsoft/vscode-extension-samples#170]
![TIM图片20190401001609](https://user-images.githubusercontent.com/5213431/55291704-3f531780-5414-11e9-85ec-187303f3e2e3.png)

Server set `kind = CompletionItemKind.File` , but client shows another icon when `label = "config"`.

**Comment by KamasamaK** [comment]
Pretty sure this is just the VS Code feature [File and folder icons in IntelliSense](https://code.visualstudio.com/updates/v1_29#_file-and-folder-icons-in-intellisense).

**Comment by sumneko** [comment]
@KamasamaK thank you, I will use another kind.
