### ISSUE TITLE
Need help in creating an extension for a new javascript framework

### ISSUE THREAD

**Issue by sumeetchhetri** [Microsoft/vscode-extension-samples#171]
I posted this question of [stackoverflow](https://stackoverflow.com/questions/55625476/vs-code-write-custom-extension-for-a-framework) hoping to get some response, but I did not get any answers yet, so reposting this here assuming some guidance can be provided.

I need to write a custom extension to enable support for a new javascript mvc framework. The framework has config files starting with a prefix fjs-config*.json, these files define the following,

- the names of the framework specific files (json, js, html)
- references to js function names (functions defined in js files)
- references to form schemas defined in json files
- references to html templates defined in the html files
- references to routes used in the framework

The extension,

- needs to get activated on opening this file in the editor
- should load a framework json schema file for the json syntax validation as per the framework rules (for fjs-config.json) (http://schemastore.org/json/)
- provide ctrl+click navigation from the fjs-config.json file to actual js function definitions
- provide ctrl+click navigation from the fjs-config.json file to actual json form definitions/files
- provide ctrl+click navigation from the fjs-config.json file to actual html template definitions/files
- other validations

I am currently confused as to whether I need to write a language server extension or use the existing embedded json lang-server and write a custom client extension that can interact with it to achieve what is desired here. I have already gone through the sample extensions. Need help to proceed as I am currently not able to move further on this action.

**Comment by Tyriar** [comment]
You should study the source of other extensions that do something similar in the marketplace as the majority of them are open source.

**Comment by KamasamaK** [comment]
If you have specific questions along the way, the members of the VS Code Development Community workspace can probably answer them.

https://vscode-slack.amod.io/

**Comment by sumeetchhetri** [comment]
That was a fun answer, go find your needle in the haystack. Thanks for responding with the slack link @KamasamaK.
