### ISSUE TITLE
add live share sample

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode-extension-samples#176]
It would be nice if there was an extension that shows how to use the VS Live Share Extension API.

**Comment by egamma** [comment]
@SimonSiefke this now exists pls see https://github.com/vsls-contrib/counter also see this blog post https://dev.to/lostintangent/building-a-collaborative-development-platform-5c34
//fyi @lostintangent

**Comment by SimonSiefke** [comment]
Thanks!
