### ISSUE TITLE
Sample request: diagnostics without a language server

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode-extension-samples#18]
I'm working on an extension where I'd like to display some diagnostics (red squiggles) for certain JSON documents.  I'm having trouble finding documentation or samples for the createDiagnosticCollection API.  (I don't want to implement a full language server because (a) these are JSON documents and (b) it's too much work for the small thing I want to do).  There is an example at https://github.com/hoovercj/vscode-extension-tutorial but it seems to involve a surprising amount of wiring up document event handlers, and requires some additional poking and prodding to make it display diagnostics on documents that are open at startup - so it doesn't feel like this is the intended usage.

It would be great if a sample could be added that shows how to create diagnostics.

If it would help, I can send a pull request containing a simple sample based on what I have at the moment, and then you folks can review it into the ground...  **grin**

**Comment by emackey** [comment]
For what it's worth, I found that you can take the existing `lsp-sample` here, target it to the JSON language type, and it will add its own diagnostics on top of the existing JSON diagnostics.  The two can coexist just fine.

**Comment by jan-dolejsi** [comment]
Depends what you want to achieve, but if all you want is to display diagnostic for actively open files in the editor, it takes less code. Including associated code actions it looks like this:

![Diagnostic code actions](https://github.com/microsoft/vscode-extension-samples/blob/master/code-actions-sample/example_diagnostic.gif?raw=true)

It displays a diagnostic entry for every mention of the 'emoji' word.

See the code in [diagnostics.ts](https://github.com/microsoft/vscode-extension-samples/blob/master/code-actions-sample/src/diagnostics.ts).

and the diagnostic collection initialized in the [extension.ts](https://github.com/microsoft/vscode-extension-samples/blob/master/code-actions-sample/src/extension.ts)

```typescript
	const emojiDiagnostics = vscode.languages.createDiagnosticCollection("emoji");
	context.subscriptions.push(emojiDiagnostics);

	subscribeToDocumentChanges(context, emojiDiagnostics);
````

**Comment by mjbvz** [comment]
Closing since we have not seen further user interest (thumbs up) over the past few years
