### ISSUE TITLE
helloworld-test-sample: `npm test` should compile first

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-extension-samples#188]
Testing https://github.com/microsoft/vscode/issues/74436

- open 'helloworld-test-sample'.
- in the console type `npm test`.
Doesn't work, need to '`npm compile` first.
In the extensions we generate we always do `"test": "npm run compile && node ./out/test/runTest.js"`

https://github.com/microsoft/vscode-extension-samples/blob/048fa2f156090c43cbe56bc4e2788aa77c091a5d/helloworld-test-sample/package.json#L31

**Comment by Tyriar** [comment]
> "test": "npm run compile && node ./out/test/runTest.js"

I hope that's not the case as that doesn't work on Windows. `"pretest": "npm run compile"` is the Windows-friendly way.
