### ISSUE TITLE
How to webpack the lsp-sample

### ISSUE THREAD

**Issue by obiwanjacobi** [microsoft/vscode-extension-samples#191]
Trying to publish my LSP extension I ran into missing dependencies and a warning that I needed to pack my .ts files (due to number of files).

I have a hard time wrapping my head around trying to webpack the lsp-sample. My code base was started using this sample and still has the same structure.

Am I correct in saying that I need 2 entry's, one for client (extension) and one for server?
I just don't have a clue how to make that work...

I have found other webpack examples for vscode extension samples, but they don't deal with these 2 entry points...

I now have copied the extension webpack config file from the vscode extension manual, but that makes the client crash (F5)...
https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by dbaeumer** [comment]
@obiwanjacobi you may want to look at the eslint extension here which is web packed. It can act as a blue print since it is very similar to the lsp-sample. https://github.com/microsoft/vscode-eslint

Does this help?

**Comment by obiwanjacobi** [comment]
Ah I see. Will investigate further. Thanks for now.

**Comment by 1138-4EB** [comment]
@obiwanjacobi I found that https://github.com/Microsoft/vscode-extension-samples/blob/master/webpack-sample/webpack.config.js works for https://github.com/ghdl/ghdl-language-server/tree/master/vscode-client, as long as you remove the `"module": "es6"` option from `ts-loader`.

**Comment by obiwanjacobi** [comment]
I get compile errors (all vscode dependencies not found) when I add that to the client.

> TS2307: Cannot find module 'vscode-languageclient'

I was thinking that maybe this warning I'm getting (2 of them) was the issue:

> WARNING in ./server/node_modules/vscode-languageserver/lib/files.js 79:36-54
Critical dependency: the request of a dependency is an expression

I think that means that webpack cannot correctly intercept the import/require in that code. I could see how that would lead to something not working.

[Here's my client webpack config file](https://github.com/obiwanjacobi/Zingularity/blob/master/Source/Language%20Server/client/webpack.config.js).
[Here's my server webpack config file](https://github.com/obiwanjacobi/Zingularity/blob/master/Source/Language%20Server/server/webpack.config.js)

**Comment by 1138-4EB** [comment]
> I get compile errors (all vscode dependencies not found) when I add that to the client.
> 
> > TS2307: Cannot find module 'vscode-languageclient'

Yes, I meant to comment it out: https://github.com/1138-4EB/ghdl-language-server/blob/bundle/vscode-client/webpack.config.js#L31-L35

> [Here's my client webpack config file](https://github.com/obiwanjacobi/Zingularity/blob/master/Source/Language%20Server/client/webpack.config.js) [](/obiwanjacobi/Zingularity/blob/HEAD@{2019-08-11T07:30:36Z}/Source/Language%20Server/client/webpack.config.js).
> [Here's my server webpack config file](https://github.com/obiwanjacobi/Zingularity/blob/master/Source/Language%20Server/server/webpack.config.js) [](/obiwanjacobi/Zingularity/blob/HEAD@{2019-08-11T07:30:36Z}/Source/Language%20Server/server/webpack.config.js)

Honestly, this is a blind suggestion, but it might work: have you considered installing webpack in https://github.com/obiwanjacobi/Zingularity/blob/master/Source/Language%20Server/client/package.json and building the client only from there?

**Comment by obiwanjacobi** [comment]
> Honestly, this is a blind suggestion, but it might work: have you considered installing webpack in https://github.com/obiwanjacobi/Zingularity/blob/master/Source/Language%20Server/client/package.json and building the client only from there?

So install webpack twice and run client and server in their own 'instance'?
This is my command (script) `"webpack": "npm run clean && webpack --mode production --config ./client/webpack.config.js && webpack --mode production --config ./server/webpack.config.js"`
I cannot see how that would be any different - so I have not tried it (yet).

The webpack operation does produce results for the client and server.
Running the webpack (client) output in the extension host (F5) results in 
> [Error - 10:39:12] Starting client failed
1
being displayed in the extension host and a popup that my extension failed. I use `--disable-extension` in my launch file - so there are no other extensions messing things up.

Is there a more detailed log where I can see what is going wrong? I suspect it is probably a dependency that cannot be loaded, but I have no way of knowing.

**Comment by obiwanjacobi** [comment]
I cannot see anything I am doing wrong, that leaves these two warnings when webpacking the server:
> WARNING in ./server/node_modules/vscode-languageserver/lib/files.js 79:36-54
Critical dependency: the request of a dependency is an expression
 @ ./server/node_modules/vscode-languageserver/lib/main.js
 @ ./server/src/server.ts

> WARNING in ./server/node_modules/vscode-languageserver/lib/files.js 280:15-28
Critical dependency: the request of a dependency is an expression
 @ ./server/node_modules/vscode-languageserver/lib/main.js
 @ ./server/src/server.ts

**Comment by dbaeumer** [comment]
The reason for this is that the LSP libraries needed a fix to be able to work with webpack but the sample is not requiring the latest version. I fixed this.

**Comment by obiwanjacobi** [comment]
I think you mean you've updated the engines/vscode value in package.json?

Anyway I have taken that sample and tried to make a webpack version (attached). 
It has the same problem I have. I would really appreciate it if someone could look at it.

I have added some dev-dependencies and some scripts. Check out the readme.md for more info on how I think this should work.

- After `npm run webpack` the code does not run correctly in vscode debug mode (launch client).
- After 'npm run package` (and having changed the publisher field) and `code --install-extension lsp-sample-1.0.0.vsix` the extension also fails.

If I can be of any help, let me know.

[lsp-sample_webpack.zip](https://github.com/microsoft/vscode-extension-samples/files/3510107/lsp-sample_webpack.zip)

**Comment by dbaeumer** [comment]
Can you fork the original repository and create a branch. Makes it easier to work on than using a ZIP.

And how does the extension fail?

**Comment by obiwanjacobi** [comment]
> And how does the extension fail?

Looks to me like the client is starting fine but the server does not start.
But it says:
> [Error - 10:39:12] Starting client failed
1

I hope I did this right:
https://github.com/obiwanjacobi/vscode-extension-samples

Branch name: `191-webpack-issue`

**Comment by dbaeumer** [comment]
I had a quick look and when running out of dev you need to webpack differently. Have a look at the eslint example here: https://github.com/Microsoft/vscode-eslint/blob/master/package.json#L321

Or does this fail from a vsix install

**Comment by dbaeumer** [comment]
And one mistake on my side: you need to use next version to have no error when packing the server. 

```
"vscode-languageclient": "5.3.0-next.8"
"vscode-languageserver": "5.3.0-next.9"
```

Sorry for that.

**Comment by obiwanjacobi** [comment]
I made (and pushed) the changes you suggested. I deleted all node_modules and out folders and ran `npm install` again. The I ran the new script `webpack:dev` and tried running the extension in the extension host (F5). It came back with the same error as before:

> Or does this fail from a vsix install
After that I ran `webpack` for production and made a vsix package and installed it locally. That also does not seem to work (as before). I do not see any errors in this case, though...

**Comment by Johanpdrsn** [comment]
I am having the same exact issue. Using the eslint setup as a blueprint, i can bundle both server and client with no problems, but when you run them in the extension host i get the following:

> [Error - 13.14.04] Starting client failed
1

**Comment by obiwanjacobi** [comment]
Is anybody still working on this?

**Comment by obiwanjacobi** [comment]
I see the issue is labelled with 'needs more info'.
What info do you need?

**Comment by bkelley13** [comment]
Has there been any resolution on this issue?  Encountering same issue.

**Comment by obiwanjacobi** [comment]
Nope I'm being ignored...

**Comment by Razzeee** [comment]
I managed to get this to work, but there are some rough edges https://github.com/elm-tooling/elm-language-server/commit/60640c7a12df183435d0808e53d461216260e5cf

You also probably don't want the wasm stuff

**Comment by tjohnsonBCM** [comment]
> [Error - 13.14.04] Starting client failed
> 1

I got the same vague error message. What fixed it for me was updating my versions of `vscode-languageclient` and `vscode-languageserver` from 4.x to 6.x.

**Comment by felipecrs** [comment]
It would be really good to have an official sample for this.

**Comment by felipecrs** [comment]
Ok, I managed to do something like below, and it worked well:

```js
// webpack.config.js
entry: {
  extension: './src/extension.ts', 
  fileServiceServer: './src/files/server/fileServiceServer.ts'
}, // the entry point of this extension, 📖 -> https://webpack.js.org/configuration/entry-context/
output: {
  // the bundle is stored in the 'dist' folder (check package.json), 📖 -> https://webpack.js.org/configuration/output/
  path: path.resolve(__dirname, 'dist'),
  filename: '[name].js',
  libraryTarget: 'commonjs2'
},
```

```js
// fileServiceClient
private getOptions(): { serverOptions: ServerOptions, clientOptions: LanguageClientOptions } {
        let serverModule = path.join(Settings.getInstance().extensionRoot, "dist", "fileServiceServer.js");
[...]
```

It's working so far.

**Comment by Gasparri** [comment]
with me it doesn't work. I have to put it or this code

HI. chez moi sa marche pas. je dois le mettre ou ce code.

GREENTING





Ok, I managed to do something like below, and it worked well:


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Felipe ***@***.***>
Envoyé le :lundi, 29 mars 2021 16:48
À : ***@***.***>
Cc : ***@***.***>
Objet :Re: [microsoft/vscode-extension-samples] How to webpack the lsp-sample (#191)


Ok, I managed to do something like below, and it worked well:

// webpack.config.js



entry: {



  extension: './src/extension.ts',



  fileServiceServer: './src/files/server/fileServiceServer.ts'



}, // the entry point of this extension, 📖 -> https://webpack.js.org/configuration/entry-context/



output: {



  // the bundle is stored in the 'dist' folder (check package.json), 📖 -> https://webpack.js.org/configuration/output/



  path: path.resolve(__dirname, 'dist'),



  filename: '[name].js',



  libraryTarget: 'commonjs2'



},

// fileServiceClient



private getOptions(): { serverOptions: ServerOptions, clientOptions: LanguageClientOptions } {



        let serverModule = path.join(Settings.getInstance().extensionRoot, "dist", "fileServiceServer.js");



[...]

It's working so far.

**Comment by felipecrs** [comment]
I created an example through https://github.com/microsoft/vscode-extension-samples/pull/398.

**Comment by dbaeumer** [comment]
I made `lsp-user-input-sample` webpack friendly. It can be used as a blue print for how to web pack a client extension with a node LSP server.

**Comment by deakjahn** [comment]
@dbaeumer A `.vscodeignore` would also be welcome to show what can be left out.
