### ISSUE TITLE
Should I fix @types/vscode's version in my extension?

### ISSUE THREAD

**Issue by HaaLeo** [microsoft/vscode-extension-samples#193]
I got a **question** regarding the new `@types/vscode` package in the [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample):  
I do not understand why you can set the [`@types/vscode`](https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample/package.json#L38)'s version to `^1.32.0`. Doesn't that bear the risk that the installed version of `@types/vscode` mismatches the specified [`engines`](https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample/package.json#L9) version? 

Therefore, `"@types/vscode": "~1.32.0"` makes more sense to me.

**Comment by octref** [comment]
`@types/vscode` is package-locked to 1.32.0. If people remove lock file and do reinstall, indeed they might install a newer version. In that case if you are **publishing** an extension, you need to update `engines.vscode` as well. For development it doesn't matter.

Ofc that's just a starter template and you can do any change you wish. The only implication of `engines.vscode` version is minimum VS Code version where your extension can be launched, and the only check we do in vsce is `@types/vscode version <= engines.vscode version`.
