### ISSUE TITLE
How to use sendRequest

### ISSUE THREAD

**Issue by houdaM97** [microsoft/vscode-extension-samples#194]
Hi,
I want to provide a function in client side that calls a function implemented in the server side using sendRequest function, what is the signature of sendRequest and how can i get the result from the function of server side by sendRequest function?

**Comment by dbaeumer** [comment]
`sendRequest` allows you to send a JSON RPC request. The result comes in the returned promise. Here is an example on how to use it: https://github.com/Microsoft/vscode-lsif-extension/blob/master/client/src/extension.ts#L169

**Comment by RomanMIzulin** [comment]
Could someone add example of using sendRequest to this repo, because IMHO it is basic case for developing LSP extension.
