### ISSUE TITLE
Can debug lsp server code

### ISSUE THREAD

**Issue by jamwulei** [microsoft/vscode-extension-samples#200]
Hello:
 @octref  @sandy081 @jrieken @mjbvz @dbaeumer 
can you help about this issue.
when I want to debug lsp sample`sservercode by this configruation，this issue occurred.
first time: I set the port 6009 ,and the port num in issue last information is 6009 ,after I note it，the issue information as follows。

![image](https://user-images.githubusercontent.com/52454773/61601556-918ca280-ac68-11e9-92d3-7e47e4a1c6bc.png)

**Comment by octref** [comment]
You'll need to open a txt file in the newly launched window. Otherwise you cannot attach to it because the Language Server wouldn't be running.

**Comment by jamwulei** [comment]
@octref ,thansk  a lot.I have resolve this issue by your suggestion.
