### ISSUE TITLE
task-provider-sample: how to read custom task attribute value?

### ISSUE THREAD

**Issue by tdjastrzebski** [microsoft/vscode-extension-samples#204]
According to the task-provider [guide](https://code.visualstudio.com/api/extension-guides/task-provider):
> The task definition has two attributes **task** and **file**. **task** is the name of the Rake task and **file** points to the Rakefile that contains the task. The **task** property is required, the **file** property is optional. If the **file** attribute is omitted, the Rakefile in the root of the workspace folder is used.

It does not seem the **file** attribute value from **tasks.json** is actually being used in [extension.ts](https://github.com/microsoft/vscode-extension-samples/blob/master/task-provider-sample/src/extension.ts) code.
How do I read custom task attribute values defined in **tasks.json**?
Where/how are they available?
Do I need to parse **tasks.json** file?

**Comment by alexr00** [comment]
`task` and `file` are defined for VS Code in the package.json of the extension and are used for identifying a task. They are not for modifying a task, they are instead provided by the the extension. 

If you want to pass stuff from tasks.json into an extension, that's this issue: https://github.com/microsoft/vscode/issues/58836
