### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by vincent-smit** [microsoft/vscode-extension-samples#208]
I am trying to implement a onHover method on a LSP server for a custom scripting language we are using for our products. I am using [this](https://blog.logrocket.com/how-to-use-the-language-server-protocol-to-extending-a-client-764da0e7863c/) example but every time I am getting the following error:

Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 

Do I have to add something to my client to support the hover action?  I have added this, for testing, to my server (+ declared the capability on top):

`
connection.onHover(({ textDocument, position }: Hover => {
    return {
      contents: {
        kind: 'markdown',
        value: 'Current word',
      },
    };	
});
`

**Comment by dbaeumer** [comment]
Actually, this looks OK to me. If you provide me with a fork of the lsp-sample in this repository demoing your problem I will have a look.

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
