### ISSUE TITLE
comment-sample uses @types/vscode@1.32 and custom vscode.Comment

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-extension-samples#209]
The `comment-sample` uses an incorrect `@types/vscode` version in `package.json`

```
"@types/vscode": "^1.32.0"
```

while the engine is set to
```
	"engines": {
		"vscode": "^1.35.0"
	},
```
This results in a lot of TypeScript errors.

Setting
```
"@types/vscode": "^1.35.0"
```
**and removing** 
```
comment-sample/src/typings/vscode.d.ts
```

Solves the errors.

**Comment by KamasamaK** [comment]
I think `"enableProposedApi": true` can also be removed.
