### ISSUE TITLE
proposed-api-sample postinstall doesn't work on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-extension-samples#214]
&& doesn't work on windows.

```
"postinstall": "vscode-dts dev && vscode-dts master"
```

**Comment by octref** [comment]
I don't really want to introduce dependencies, and just learned `install` and `postinstall` run sequentially after installing deps. So opted to use that.

**Comment by Tyriar** [comment]
Yep, alternatively this works too:

```
		"downloadapi": "vscode-dts master",
		"postdownloadapi": "vscode-dts dev",
		"postinstall": "npm run downloadapi"
```

`predownloadapi` would be available too if we needed a third

**Comment by octref** [comment]
Wow, didn't realize this was possible:

> Additionally, arbitrary scripts can be executed by running npm run-script <stage>. Pre and post commands with matching names will be run for those as well (e.g. premyscript, myscript, postmyscript).

Changed to use that instead.
