### ISSUE TITLE
How to change behavior of HTML file editing?

### ISSUE THREAD

**Issue by ackava** [microsoft/vscode-extension-samples#222]
I want to enable `<script>` tag to support typescript in existing html files. As I process html file to convert typescript to javascript. I have seen examples of how to embed language like HTML in custom language. Is it possible to achieve it easily or I have to rewrite HTML language service?

**Comment by octref** [comment]
You have to fork the HTML language server: https://github.com/microsoft/vscode/tree/master/extensions/html-language-features. And you can only use that extension in place of the current HTML extension. By standard what's inside `<script>` in a HTML file is JS, so we can't make any changes to support TS there upstream.
