### ISSUE TITLE
Use MochaOption to set color in index.ts example

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode-extension-samples#223]
I think it is better to use MochaOption instead of using a setter method to set the color usage

```
const mocha = new Mocha({
    ui: 'tdd'
  });
  mocha.useColors(true);
```
```
const mocha = new Mocha({
    ui: 'tdd',
    useColors : true
  });
```
It allows to have a more coherent coding style with the 'ui' tdd MochaOption already used.

relates to https://github.com/microsoft/vscode-docs/issues/3220

**Comment by octref** [comment]
See https://github.com/microsoft/vscode-docs/pull/3221#issuecomment-551148225, sorry
