### ISSUE TITLE
Remove decoration type (again?)

### ISSUE THREAD

**Issue by marabesi** [microsoft/vscode-extension-samples#23]
As posted in the issue #22 I am waiting for an answer, should it be reopened?

The best thing would be to update the example https://github.com/Microsoft/vscode-extension-samples/blob/master/decorator-sample/src/extension.ts with the ability to remove the decoration applied.

**Comment by mpearon** [comment]
I agree.  We need some good examples for this.

**Comment by alexdima** [comment]
PR welcome.
