### ISSUE TITLE
lsp-sample build hanging

### ISSUE THREAD

**Issue by sgranade** [microsoft/vscode-extension-samples#234]
I've run into issues building and debugging the lsp-sample code. I'm running vscode 1.40.2 on a Windows 10 box.

My steps:

* Unpacked lsp-sample from the repo (current as of commit 0a4a2d4, Dec 9th 2019)
* At command line, ran `npm install` in the `lsp-sample` directory with no errors
* Opened VS Code on the folder
* Pressed Ctrl+Shift+B to build.
	* Build task runs `npm run watch`, which runs `npm run watch` which in turn triggers the typescript compiler `tsc -b -w`.
	* Build task indicator whirls forever. No more output appears in the terminal.
* In the Debug viewlet, verified that the configuration dropdown listed `Launch Client`.
* Pressed the Run icon next to the configuration dropdown.
	* Clock icon appears on the Debug icon, the "working" bar underneat the configuration dropdown moved left-to-right endlessly, with no output and no further action.

The client and server are compiling to some extent, since their corresponding Javascript files are showing up in the `out` directories.

If I restart VS Code, I can run the `Launch Client` debug configuration, but the extension doesn't work. Entering all-cap words or pressing `t` or `j` does nothing.

If I run the `Client + Server` debug configuration, I can set breakpoints in extension.ts (line 9 during startup; line 20 during activation) and they're caught. Similar startup breakpoints in server.ts (line 6, line 22) are grayed out with the warning that the generated code isn't found. A server.ts breakpoint on line 33 in onInitialize() is allowed, but is never reached.

Any ideas?

**Comment by sgranade** [comment]
To add, after a second go-round: I cloned a clean copy of the sample repo. When I went through the above steps again, the Build task completed. However, when I fired off the `Launch Client` configuration, the new build of the extension failed to work, and the breakpoints behaved as previously described.

**Comment by sgranade** [comment]
While the Build issue remains, I did discover that the server only fires up when you _open a text file_, as per #103. I'll close since I can work around the weird Build error for now.

**Comment by axetroy** [comment]
hi! @sgranade 

I also encountered the same problem, would you please describe "the server only fires up when you open a text file"?

What file does it open? open with vscode? And then start the server.

Thx.

**Comment by sgranade** [comment]
If you build and run the extension, the server is available but not running. It won't activate and run until you open a text file in VS Code in the new window that opens when you run the code.
