### ISSUE TITLE
How to associate a file extension with a brand new language?

### ISSUE THREAD

**Issue by siowyisheng** [microsoft/vscode-extension-samples#235]
I'm writing a language server based off `lsp-sample`, which activates on 'plaintext' language.

However, I want the language server to be activated whenever a file with extension `.tag` is open.

I see that there are guidelines to define a new language identifier [here](https://code.visualstudio.com/docs/languages/identifiers), but I don't know how to register a new language for the user from within the language server, or if this is even possible or if I should be trying to work in a different direction.

Any help will be greatly appreciated!

**Comment by KamasamaK** [comment]
You would do this in the extension's `package.json`. See [`contributes.languages`](https://code.visualstudio.com/api/references/contribution-points#contributes.languages).

**Comment by siowyisheng** [comment]
Thank you so much @KamasamaK !
