### ISSUE TITLE
does the TreeDataProvider API only support typescript ?

### ISSUE THREAD

**Issue by zsmj1994** [Microsoft/vscode-extension-samples#24]
I rigistered a provider,and create a TreeDataProvider class with javascript .but it not work

**Comment by JokerDan** [comment]
I am also having trouble getting a TreeDataProvider to display to a view on an extension written just with JS. Any update on this issue?

**Comment by sandy081** [comment]
@zsmj1994 @JokerDan Please file an issue in [VS Code repository](https://github.com/Microsoft/vscode) and provide sample to reproduce it.
