### ISSUE TITLE
What is the reason behind vscode:prepublish in the hello-world example package.json file?

### ISSUE THREAD

**Issue by geopic** [microsoft/vscode-extension-samples#240]
It literally just runs the following script, 'compile'. There isn't any explanation for this in the docs so I'm interested in why it is there.

**Comment by geopic** [comment]
https://github.com/microsoft/vscode-extension-samples/blob/926c5c045e3274a0572f4a07ca0adf6d2fdbd949/helloworld-sample/package.json#L27

Thanks

**Comment by Tyriar** [comment]
It runs when vsce publish is run to public it to the marketplace, this makes sure that the extension is compiled before it's uploaded.
