### ISSUE TITLE
What is 'megaphone' in statusbar-sample?

### ISSUE THREAD

**Issue by geopic** [microsoft/vscode-extension-samples#241]
https://github.com/microsoft/vscode-extension-samples/blob/926c5c045e3274a0572f4a07ca0adf6d2fdbd949/statusbar-sample/src/extension.ts#L37

Thanks

**Comment by bpasero** [comment]
@misolori is this octicon no longer supported?

**Comment by misolori** [comment]
@bpasero it's still there, I think maybe they don't understand the actual icon itself? Here it is:

![image](https://user-images.githubusercontent.com/35271042/71769297-23fdc700-2ed4-11ea-95a8-ea2af456b33d.png)

**Comment by geopic** [comment]
Thank you. It wasn't defined anywhere in the file so I wanted to know what it was
