### ISSUE TITLE
is it possible to ship a C# assembly and use it from extension?

### ISSUE THREAD

**Issue by yatagarasu25** [microsoft/vscode-extension-samples#246]
is it possible to ship a C# assembly and use it from extension? I am developing a Visual Studio extension right now, would like to port it to VS Code. It have some parts build to separate assembly, mostly logic, not dependent on visual studio. Is it possible to reuse it for VSCode extension, or I need to reimplement it all on TypeScript?

**Comment by Tyriar** [comment]
If you can communicate with a C# assembly using node.js then you should be able to do that.
