### ISSUE TITLE
lsp-sample nothing happens

### ISSUE THREAD

**Issue by nobody-famous** [microsoft/vscode-extension-samples#247]
I went into the lsp-sample directory and followed the instructions in the readme,
- npm install
- open code on the lsp-sample folder
- Ctrl+Shift+B
- Launch Client from debug viewlet

The Extension Development Host opens. I open a new document for plain text, type j or t to see completion options, and nothing happens. The are no completion options. Hit Ctrl+Space to force it and it says there's no suggestions. Tried typing AAA aaa BBB as suggested, nothing happens.

The only output I find anywhere is in the EDH output for Language Server Example, it has

Debugger listening on ws://127.0.0.1:6009/57e1a15e-0197-4465-bd4f-31e8a4222b5b
For help, see: https://nodejs.org/en/docs/inspector

How do I go about debugging what's going on?

**Comment by dbaeumer** [comment]
This works for me:

![capture](https://user-images.githubusercontent.com/1931590/73163276-eca7c200-40ef-11ea-88aa-26b0d7d71b58.png)


In the debug viewlet you can run `Attach to Server` and then set a breakpoint into the server code and see whether it gets hit.

**Comment by nobody-famous** [comment]
Interesting. It's because I didn't save the file. I was using a new buffer and setting its type to plain text. If I save it as a file, it starts working.

How do you make it work for any plain text buffer?

**Comment by dbaeumer** [comment]
Allow the `untitled` scheme here: https://github.com/microsoft/vscode-extension-samples/blob/5ae1f7787122812dcc84e37427ca90af5ee09f14/lsp-sample/client/src/extension.ts#L41
