### ISSUE TITLE
Create sample extension with extension context menu contribution

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-extension-samples#248]
Testing microsoft/vscode#89361

We should create a sample extension that uses the new extension context menu contribution. I spent far too much time trying to find an example with this. We should add it to the list here:

https://github.com/microsoft/vscode-extension-samples/

cc @octref

**Comment by sandy081** [comment]
This is not a new contribution point and just an addition to existing `menus` contribution point. I do not think we have a sample for each menu location. Adding to the release notes and doc would be enough IMO.
