### ISSUE TITLE
webpack can't find module vscode, 'vscode-debugadapter', and 'vscode-debugprotocol'

### ISSUE THREAD

**Issue by paulo-fernando-silva** [microsoft/vscode-extension-samples#249]
The issue is not so much with vscode, but more with its documentation, more specifically here: https://code.visualstudio.com/api/working-with-extensions/bundling-extension

The example given in the following link fails when we add other modules:
https://github.com/Microsoft/vscode-extension-samples/tree/master/webpack-sample

Here's a patch that can be applied to the webpack-sample to reproduce the issue:
https://pastebin.com/peqvJ1Wt

I also asked on stackoverflow:
https://stackoverflow.com/questions/60024640/

Any ideas on how to fix this?
Thanks

**Comment by jrieken** [comment]
Maybe debugger people like @isidorn and @roblourens know? This seems very web pack specific and you should consult their resources

**Comment by roblourens** [comment]
I am not a webpack expert but the node-debug extension is webpacked and uses both of those modules. Maybe you can take some inspiration from that configuration: https://github.com/Microsoft/vscode-node-debug

**Comment by paulo-fernando-silva** [comment]
Thanks for your help. That solution is much more complex than the solution proposed in this sample. In the end it seems that commenting out the line
`//  "module": "es6" // override `tsconfig.json` so that TypeScript emits ...`
does the trick. Apparently it might be an issue with ts-loader. Independently the current sample documentation doesn't work as is described. I guess I'll check if everything still works without that line, and if not I'll reach out to the ts-loader people. But then again, why was that line added?
It does say:
`// override `tsconfig.json` so that TypeScript emits native JavaScript modules.`
But even without that line it still seems to generate js.
