### ISSUE TITLE
Click into terminal created by sample causes Chrome Tools to open.

### ISSUE THREAD

**Issue by fgodoy** [Microsoft/vscode-extension-samples#25]
Hi Guys. 

Firstly, nice work. 👍 

So, I ran the sample of terminals and I get a strange behavior, when I create a terminal by the command from plugin and I click to the new terminal, the Chrome Tools starts. I don't know why. If I click in the default terminal it's not occurs. 
Any Ideia why this happens? 

I created a video to better understand: 

![terminal](https://user-images.githubusercontent.com/2242629/28923035-e64bf314-7832-11e7-8251-670d853afb1e.gif)

Thanks.

**Comment by Tyriar** [comment]
@fgodoy you have an error in the console, could you press the error button to check the contents?

**Comment by Tyriar** [comment]
Just checked and it works fine for me. Maybe zsh isn't installed?

**Comment by fgodoy** [comment]
@Tyriar I tested in another machine with Windows and works. So, I'm trying to check what's happening in the Mac. zsh it's installed and works normally.
I'll post after solution. 

Thanks for tip above.

![image](https://user-images.githubusercontent.com/2242629/28977797-e9176f8c-7919-11e7-9d30-16123c704759.png)

**Comment by Tyriar** [comment]
After looking at the error, I think you're actually seeing https://github.com/Microsoft/vscode/issues/20505 which should be fixed in the next version 👍
