### ISSUE TITLE
fsprovider-sample: IntelliSense not working for memfs-based *.ts files

### ISSUE THREAD

**Issue by yutao-huang** [microsoft/vscode-extension-samples#253]
It seems the *.ts files created in this virtual file system doesn't support IntelliSense. For example, if I type in `console.`, it won't automatically show the list of members, etc. Hovering over symbols won't show type definitions, etc.

Is it possible at all to support IntelliSense for *.ts files on a virtual file system?

BTW, some file types do seem to have IntelliSense - e.g. *.html, *.css, *.php, etc.

**Comment by mjbvz** [comment]
Known limitation tracked by https://github.com/microsoft/vscode/issues/59650
