### ISSUE TITLE
webpack-sample launches unwatched

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-extension-samples#255]
The [launch configuration](https://github.com/microsoft/vscode-extension-samples/blob/631a16f9d56c7b7dffa55f527872d3cb078a54bd/webpack-sample/.vscode/launch.json) for launching the `webpack-sample` extension executes `npm: webpack` as its `preLaunchTask`, which is unwatched. All of the other samples use a watched compilation (`npm: watch`). Is there a reason that `npm: webpack-dev` is not used?

**Comment by jrieken** [comment]
>  Is there a reason that npm: webpack-dev is not used?

No but extension sample might vary in its details
