### ISSUE TITLE
vs code custom task not working properly

### ISSUE THREAD

**Issue by SofiaTa** [microsoft/vscode-extension-samples#258]
HI,

I've cloned the repo and run the `task-provider-sample`  with a `Rakefile` with several tasks and wheh you open the task ( on the extension host ) we see only the `build` task  although we have additional tasks ... see the image below 

while debug the code I see 
`result.push(task);` is filled with all the required tasks, however in task UI there is only one.
Any idea ? 

im using vscode `Version: 1.42.1` 

![image](https://user-images.githubusercontent.com/34491236/75342210-9d93af00-589e-11ea-9c4d-cf3042ab00b8.png)

**Comment by alexr00** [comment]
Please share your settings.json and tasks.json.

**Comment by SofiaTa** [comment]
@alexr00  here is the files of the **source** , the target while debug (extension development host )  have an empty `.vscode` folder ...let me know if you need additional info ? 

settings.json

```
{
	"editor.insertSpaces": false,
	"tslint.enable": true,
	"typescript.tsc.autoDetect": "off",
	"typescript.preferences.quoteStyle": "single"
}
```

tasks.json

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never",
				"panel": "dedicated"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
		{
			"type": "npm",
			"script": "compile",
			"problemMatcher": "$tsc",
			"presentation": {
				"reveal": "never",
				"panel": "dedicated"
			}
		}
	]
}
```

Thanks

**Comment by SofiaTa** [comment]
Sorry, I found the issue. thanks!
