### ISSUE TITLE
Running task doesnt add a new task

### ISSUE THREAD

**Issue by astrixj** [microsoft/vscode-extension-samples#262]
I've run the task provider example
https://github.com/microsoft/vscode-extension-samples/tree/master/task-provider-sample

in the extension host I open the following `rakefile` 

```
desc "print hello world!"        # description.
task "build" do            # rake task name.
   p "hello world!"                 # print "hello world!"
end

```

And I see the build task , when click on it and after `continue without scanning the task output" I see that the task  is running, however it doesn't add any entry to the `tasks.json` file .
in the package json it's defined ...
https://github.com/microsoft/vscode-extension-samples/blob/master/task-provider-sample/package.json#L19

Thanks

**Comment by alexr00** [comment]
This correct. The task is provided by an extension so it doesn't need to be in the tasks.json. If you want it to show in tasks.json you can run the Configure Task command.
