### ISSUE TITLE
Update javascript target from es6 to ES2019

### ISSUE THREAD

**Issue by J-Fields** [microsoft/vscode-extension-samples#265]
For a while now, VSCode has shipped with node 12, which [according to the typescript wiki](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping) can handle `ES2019`.

I may be missing something (I'm far from an expert on this stuff), but is there a reason that the extension samples here still transpile to `es6`? Would you recommend new extensions target `es6`?

**Comment by Tyriar** [comment]
Extensions need to run in browsers as well for this https://visualstudio.microsoft.com/services/visual-studio-online/

**Comment by usernamehw** [comment]
Does it mean that it's completely safe to use target `ES2019` for vscode engine **1.40.0** and higher?

**Comment by KamasamaK** [comment]
> Does it mean that it's completely safe to use target `ES2019` for vscode engine **1.40.0** and higher?

That would make sense based on the Node compatibility chart, but I wonder if there are scenarios where browser compatibility would be an issue. I've never tried it, but I know Visual Studio Codespaces exists and presumably has some minimum browser requirements but couldn't find anything on it.
