### ISSUE TITLE
lsp-embedded-language-service: use vscode-languageserver-textdocument

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-extension-samples#267]
Testing https://github.com/microsoft/vscode/issues/93809

https://github.com/microsoft/vscode-extension-samples/blob/694b0d8b178cb14d4802c9a52a7bc75956f74a76/lsp-embedded-language-service/server/src/server.ts#L23

We want to remove the TextDocument from vscode-languageserver and have API users decide what TextDocument to use. That can be the simple one from vscode-languageserver-textdocument but a more sophisticated one such a piecetree powered TextDocument.

```ts
import { TextDocument} from 'vscode-languageserver-textdocument ';
//...
const documents = new TextDocuments(TextDocument);
```

**Comment by KamasamaK** [comment]
Using `vscode-languageserver` 6.x enforces this, but the new sample uses 5.x for some reason.

**Comment by octref** [comment]
Updated to vscode-languageserver 6.x.
