### ISSUE TITLE
lsp-embedded-languages: using HTML is confusing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-extension-samples#270]
Testing microsoft/vscode#93809

Can the sample define a new language html1, and register for that?

Currently it is unclear if you see the sample extension or the built-in HTML support.

Also the extension is missing the `language:html`

**Comment by aeschli** [comment]
_Also the extension is missing the language:html_

Oh, I got confused by https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-embedded-language-service/client/package.json

Can that be deleted?

**Comment by aeschli** [comment]
```
	"activationEvents": [
		"onLanguage:html1"
	],
	"contributes": {
		"languages": [
			{
				"id": "html1",
				"extensions": [
					".html1"
				],
				"aliases": [
					"HTML1"
				]
			}
		]
	},
```

**Comment by octref** [comment]
> Can that be deleted?

Yes because it only needs to be present in top level.

HTML1 is a good idea. I'll change it.

**Comment by octref** [comment]
Adopted HTML1.
