### ISSUE TITLE
Command 'Terminal API: Attach data listener' resulted in an error 

### ISSUE THREAD

**Issue by yuzhidi** [microsoft/vscode-extension-samples#274]
Hi,
 when I run terminal-sample, attach data listener fail, how to fix it?

Command 'Terminal API: Attach data listener' resulted in an error (Running the contributed command: 'terminalTest.onDidWriteTerminalData' failed.)

**Comment by Tyriar** [comment]
This is a proposed API so it won't work unless you're on Insiders with proposed enabled. Additionally the plan is not to stabilize this so it's probably a waste of time experimenting with it.
