### ISSUE TITLE
Can't compile Helloworld extension inside VSCode

### ISSUE THREAD

**Issue by narnaud** [microsoft/vscode-extension-samples#275]
- VSCode Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:

1. Follow instructions here: https://code.visualstudio.com/api/get-started/your-first-extension
    - `npm install -g yo generator-code`
    - Same answers as on the documentation page
    - `code ./helloworld`
2. Press `F5` and run the command "Hello World"

An error is displayed:
```
Activating extension 'undefined_publisher.helloworld' failed: Cannot find module 'c:\nicolas\dev\vscode\helloworld\out\extension.js'
Require stack:
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```
There are no `out` directory created, the extension is not built.

To further investigate, I've installed typescript with `npm install typescript` and compile the extension on command line: it works.
So the problem seems to be that vscode does not built it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
What's inside your `package.json`?

**Comment by narnaud** [comment]
That's the default package.json created by yeoman:
```
{
	"name": "helloworld",
	"displayName": "Helloworld",
	"description": "",
	"version": "0.0.1",
	"engines": {
		"vscode": "^1.44.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
		"onCommand:helloworld.helloWorld"
	],
	"main": "./out/extension.js",
	"contributes": {
		"commands": [
			{
				"command": "helloworld.helloWorld",
				"title": "Hello World"
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "npm run compile",
		"compile": "tsc -p ./",
		"lint": "eslint src --ext ts",
		"watch": "tsc -watch -p ./",
		"pretest": "npm run compile && npm run lint",
		"test": "node ./out/test/runTest.js"
	},
	"devDependencies": {
		"@types/vscode": "^1.44.0",
		"@types/glob": "^7.1.1",
		"@types/mocha": "^7.0.2",
		"@types/node": "^13.11.0",
		"eslint": "^6.8.0",
		"@typescript-eslint/parser": "^2.26.0",
		"@typescript-eslint/eslint-plugin": "^2.26.0",
		"glob": "^7.1.6",
		"mocha": "^7.1.1",
		"typescript": "^3.8.3",
		"vscode-test": "^1.3.0"
	}
}
```

**Comment by narnaud** [comment]
More information: I've tested the helloworld-sample example in this repository, and have the same issue.
If I start the task `npm: watch` explicitly and then debug with `F5`, it's working. So for some reason, pressing `F5` doesn't start `npm: watch` automatically for me.

**Comment by narnaud** [comment]
I found the issue, it's not coming from VSCode actually.

In my powershell profile, I was going to a specific directory with a `Set-Location`. Apparently, this meant that when starting the task `npm: watch`, it was started in the wrong directory (ie not in the extension one).

Removing this line from my profile fix it.

Sorry about the noise.
