### ISSUE TITLE
Webview-Sample: cannot find module 'path' / 'vscode'

### ISSUE THREAD

**Issue by DarkTrick** [microsoft/vscode-extension-samples#277]
After downloading and loading the webview sample, extension.ts contains an error:
    
    Cannot find module 'path'. ts(2307) [1,23]
    Cannot find module 'vscode'. ts(2307) [2,25]
    Parameter 'e' implicitly hasan 'any' type. ts(7006) [96,4]
    Parameter 'message' implicitly has an 'any' type. ts(7006) [107,4]

**Comment by mjbvz** [comment]
Did you run npm install?

**Comment by DarkTrick** [comment]
After `npm install` it worked.

I would suggest to include that information here:
https://code.visualstudio.com/api/extension-guides/webview
At best close to the link to the github repository.

**Comment by mjbvz** [comment]
This is covered in https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample#running-the-example
