### ISSUE TITLE
terminalTest.onDidWriteTerminalData error

### ISSUE THREAD

**Issue by Fais-007** [microsoft/vscode-extension-samples#278]
Command 'Test: Terminal' resulted in an error (Running the contributed command: 'terminalTest.onDidWriteTerminalData' failed.)

**Comment by Tyriar** [comment]
It's a proposed API so it won't work in stable and without --enable-proposed-api set

**Comment by Tyriar** [comment]
I recommend against using it though as chances are slim it will get stabilized.
