### ISSUE TITLE
Leftover update-vscode script in lsp-sample

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/vscode-extension-samples#282]
The code in:

https://github.com/microsoft/vscode-extension-samples/blob/81d47e06b17b11a6c20ec2ae5806594969736bf5/lsp-sample/package.json#L49

refers to an `update-vscode` script which results in an error. I guess that's a leftover from the vscode bump in https://github.com/microsoft/vscode-extension-samples/commit/e1ecdaec8974b938e7a92589faa233e1691d251f

Ping @dbaeumer

**Comment by dbaeumer** [comment]
Thanks!
