### ISSUE TITLE
[Example request] Embedded lsp for typescript/javascript

### ISSUE THREAD

**Issue by Arthie** [microsoft/vscode-extension-samples#283]
Hello, I am trying to create an embedded language extension for typescript/javascript.
The current lsp-embedded examples are useful but there is no typescript equivalent for "vscode-html-languageservice".

Is it possible to add an embedded language example targeting typescript?

**Comment by dbaeumer** [comment]
@aeschli assigning to you. Not sure who would be the right person for this.

**Comment by aeschli** [comment]
You can look how this is done in the real html language server`: https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/server/src/modes/javascriptMode.ts

**Comment by Arthie** [comment]
@aeschli Thanks for the reply! I am looking for an example that embeds another language into Javascript. Specifically embedded into javascript template tags.
Sorry, my first post wasn't that clear.

**Comment by aeschli** [comment]
If you want to run inside the TypeScript/JavaScript language server: 
The TypeScript language server has a feature called 'plugins' that allow you to participate in it's behavior:
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin
To contribute such a plugin to the TypeScript language extension in VSCode:
https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins

**Comment by aeschli** [comment]
Assigning to @mjbvz to decide if we want to a sample that shows how to extend the TypeScript language server.

**Comment by mjbvz** [comment]
This is a pretty niche problem so it's probably best to look at what existing extensions do here. See https://github.com/mjbvz/vscode-lit-html for example

**Comment by daKmoR** [comment]
> JavaScript embedded in a other language?
> You can look how this is done in the real html language server: https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/server/src/modes/javascriptMode.ts

that sort of works but it's not what I would have expected... it does not support any code that uses imports (which probably every meaningful code will do)

e.g. examples like this do not work in `html-language-features` 

👉 `foo.js`
```js
export const foo = { on: 'foo', off: 'baz' }
```

👉 `index.html1` // it also doesn't work for the built in `.html` language service
```html
<script type="module">
   import { foo } from './foo.js';
   foo.o // no autocomplete for on/off
</script>
```

an example how to get "real" javascript completion (like in a js file supporting imports) would be awesome 🤞

I have been reading through some issues and I am not sure if it's even possible? if it's currently not possible what would be needed to make it possible? 🤔
