### ISSUE TITLE
Is there a way to set the Comment API sample contributions from the TS side?

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode-extension-samples#284]
I am going through the samples one by one and refactoring them as an exercise. I've been successful thus far and am getting a grasp on how VS Code works, but the problem with the [comment API sample] is that it has so much of its functionality in [its `package.json`](https://github.com/microsoft/vscode-extension-samples/blob/master/comment-sample/package.json) file. This has me stumped as to how to proceed. My thinking is that it would be good to move the `package.json` functionality into the `extension.ts` file, but I am not sure how to do that as the `CommentController` lacks the necessary properties to even attempt this.

Because the editor support is lacking, I am not sure if the functionality in `package.json` is complete or even how to use it. `CommentController` should be a control and yet it has no properties and uses global commands for seemingly everything

**Comment by RMacfarlane** [comment]
Unfortunately no, comment commands are expected to be declared in the `package.json` and not in the `CommentController`. There is a good write up [here](https://github.com/microsoft/vscode/issues/68020) that explains some of the history of comment API and why it follows this pattern
