### ISSUE TITLE
How to add a button to the right of the custom tree viewContainer title

### ISSUE THREAD

**Issue by i7soft** [microsoft/vscode-extension-samples#285]
I want to add some buttons to the right of the custom tree viewContainer title,like 👇
![Xnip2020-04-26_14-33-32](https://user-images.githubusercontent.com/10511797/80299957-3ffede80-87cb-11ea-9129-6ce9fe3e24af.png)
![Xnip2020-04-26_14-33-09](https://user-images.githubusercontent.com/10511797/80299959-42f9cf00-87cb-11ea-9a3c-7bdcf54db3a6.png)

I fount it named "title-actions" in the chrome devtools.
![Xnip2020-04-26_14-34-23](https://user-images.githubusercontent.com/10511797/80299950-31b0c280-87cb-11ea-80cf-e55d03261e62.png)

but I dont know how to do
`view/title` and `view/item/context` are for the view,not for the viewsContainer

**Comment by alexr00** [comment]
Not currently possible. See https://github.com/microsoft/vscode/issues/90268 for the feature request.
