### ISSUE TITLE
Completion example doesnt seem to work as expected

### ISSUE THREAD

**Issue by brpaz** [microsoft/vscode-extension-samples#288]
Hello. I am trying to create a custom extension provider and I am folloiwing the example and I have cleanup a bit to keep only  the provder2.

```js
import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
  const provider = vscode.languages.registerCompletionItemProvider(
    "yaml",
    {
      provideCompletionItems(
        document: vscode.TextDocument,
        position: vscode.Position
      ) {
        // get all text until the `position` and check if it reads `console.`
        // and if so then complete if `log`, `warn`, and `error`
        let linePrefix = document
          .lineAt(position)
          .text.substr(0, position.character);

        console.log(linePrefix);
        if (!linePrefix.endsWith("console.")) {
          return undefined;
        }

        return [
          new vscode.CompletionItem("log", vscode.CompletionItemKind.Method),
          new vscode.CompletionItem("warn", vscode.CompletionItemKind.Method),
          new vscode.CompletionItem("error", vscode.CompletionItemKind.Method),
        ];
      },
    },
    "." // triggered whenever a '.' is being typed
  );

  context.subscriptions.push(provider);
}
```

And it´s not working. 

The function is executed but it shows no suggestion when I type `console.`

Am I missing something from the example?

**Comment by jrieken** [comment]
> And it´s not working.

Be specific!

**Comment by jrieken** [comment]
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by brpaz** [comment]
I am in the process of cleaning old open issues. I don´t remember if I got this solved, but your detailed explanation makes sense ;)

Thank you. I will close this.
