### ISSUE TITLE
Problems running the lsp-sample

### ISSUE THREAD

**Issue by pajoma** [Microsoft/vscode-extension-samples#30]
* VSCode Version: 1.16.1, x64, 
* OS Version: Windows 7, x64

Should the values for "preLaunchTask" in the launch.json be "watch:client" (same for server) instead of "Client Watch?

I can start the sample extension, but I can't attach to the server. Does this have something to do with the switch from legacy to inspector? No code or configuration (besides the preLaunchTasks) have been changed. 

Error message (translated from German): No connection to runtime. Make sure that debug modus has been set to legacy.  (it [is](https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/.vscode/launch.json))

**Comment by lae0901** [comment]
I have a similar error. 
Could not find the preLaunchTask 'Client Watch'.

I ran npm install and npm run compile from the lsp-sample directory. Then start vscode and launch client.

**Comment by pajoma** [comment]
My issue was due to using 32bit version of vscode. After reinstalling the 64bit version, attaching to the server works again. 

Any yes, in launch.json, the prelaunchtasks have to be "watch:client" and "watch:server"

**Comment by vankeisb** [comment]
Same here, I'm able to run the client, but I cannot attach to server.
I have changed the prelaunchtasks as suggested, but it still doesn't work.  When I launch the config, I have an Error "Unable to connect to runtime".

I'm running Version 1.16.1 (1.16.1) on OSX.

**Comment by Jatz** [comment]
I had the same problems getting debugging working for the lsp-sample example (from the **vscode-extension-samples** repository). Here are the steps to reproduce those issues and the changes I had to make along the way to get it working for me.

**1.** Copy **lsp-sample** directory from repository https://github.com/Microsoft/vscode-extension-samples

**2.** Open **lsp-sample** folder in vscode

**3.** In the integrated terminal run **npm install**

**3.** Press F5 to start the **Launch Client** debug session

**4.** Observe the error: "Could not find the preLaunchTask 'Client Watch'".

**5.** Modify launch.json preLaunchTasks to **watch:client** for **Launch Client** configuration, and **watch:server** for **Attach to Server** configuration.

**6.** Press F5 again to launch the **Launch Client** debug session.

**7.** Observe that it works this time.

**8.**  Attempt to start the **Attach to Server** debug session

**9.** Observe the error: 'Cannot connect to runtime; make sure that runtime is in 'legacy' debug mode.

**10.** Change protocol value from **legacy** to **inspector** for **Attach to Server** configuration in launch.json

**_Note_**: at this point the launch.json looks as follows:

```json
{
  "version": "0.2.0",
  // List of configurations. Add new configurations or edit existing ones.
  "configurations": [
    {
      "name": "Launch Client",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--extensionDevelopmentPath=${workspaceRoot}/client"
      ],
      "stopOnEntry": false,
      "sourceMaps": true,
      "outFiles": [
        "${workspaceRoot}/client/out/**/*.js"
      ],
      "preLaunchTask": "watch:client"
    },
    {
      "name": "Attach to Server",
      "type": "node",
      "request": "attach",
      "port": 6009,
      "sourceMaps": true,
      "outFiles": [
        "${workspaceRoot}/client/server/**/*.js"
      ],
      "protocol": "inspector",
      "preLaunchTask": "watch:server"
    }
  ]
}
```

**11.** Change _debugOptions_ line in **client/src/extension.ts** to the following:
```javascript
let debugOptions = { execArgv: ["--nolazy", "--inspect=6009"] };
```

**12.** Re-launch the **Launch Client** configuration and **Attach to Server** configuration

**13.** Observe that there are now no longer any errors and you can debug both the client and server code.

**Comment by tdolny** [comment]
Steps @Jatz defined worked for me. Just had to compile before re-launch.
**11b**. npm run compile.

**Comment by jan-dolejsi** [comment]
Well done @Jatz and @tdolny. On top of that the upgrade to VS Code 64bit was necessary to make this work.

**Comment by dbaeumer** [comment]
I updated the example and updated the readme.md with instructions on how to use it.
