### ISSUE TITLE
custom-editor-sample: Question about CustomTextEditor

### ISSUE THREAD

**Issue by AlanLi7991** [microsoft/vscode-extension-samples#301]
custom-editor-sample: Question about CustomTextEditor

Hi, I am working on an extension about background of editor, 

I refereed two popular background extension, 

* https://github.com/shalldie/vscode-background
* https://github.com/vscode-extension/vscode-background-cover

they attached the background image by changing the default css file, 

it brings two fatal problems about

1. need run vscode as an administrator
2. vscode will warning about insiders cracked

I want to solve those by custom editor modules, is it possible?

It is a sample idea that I should read the default index.html, main.js, main.css, and assign them to the WebviewPanel properties from method

* "resolveCustomTextEditor(document: TextDocument, webviewPanel: WebviewPanel, token: CancellationToken): Thenable<void> | void" 

then I got a totally same text editor like original.

I have read all samples and documents but not found a clue.

So I came here to query is it exist a solution about this or if I want to finish my extension, I should do the same thing like others.

Tanks a lot for answer me.

**Comment by mjbvz** [comment]
No, custom editors do not solve your issue. They are for providing a complete new webview that replaces the VS Code's normal text editor. They do not let you customize VS Code's normal text editors

**Comment by AlanLi7991** [comment]
Thanks, will this module offer a function for customize normal text editor like :

**Comment by AlanLi7991** [comment]
Thanks, will this module offer a static function for customize normal text editor like :

* WebviewPanel.normalEditor(document: TextDocument)

in the future? the return Webview panel will inherit all events and styles from original.

Is it forbidden to customize vscode like this way in Microsoft plan?

**Comment by mjbvz** [comment]
No, we do not plan to support that with the custom editor api
