### ISSUE TITLE
Please sync lsp-sample and lsp-multi-server-sample

### ISSUE THREAD

**Issue by isral** [microsoft/vscode-extension-samples#302]
I try to make a compiler using lsp-multi-server-sample.
But I don't know where to put compile.
I found validateTextDocument in lsp-sample, but I don't know how to merge both samples.

**Comment by dbaeumer** [comment]
@isral this is on purpose to keep the examples small. In the lsp-multi-server-sample you can as in the single example add a something like this:

```
// The content of a text document has changed. This event is emitted
// when the text document first opened or when its content has changed.
documents.onDidChangeContent(change => {
	validateTextDocument(change.document);
});
```
