### ISSUE TITLE
How to Use Semantic Highlighting In LSP Extensions

### ISSUE THREAD

**Issue by dkelosky** [microsoft/vscode-extension-samples#304]
Looking at the [semantic highlighting sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample), I'm not clear if these methods could be used on the "server" side in an LSP extension.

My confusion comes from [this doc](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-provider) which says "The semantic token provider API comes in two flavors to accommodate a **language server's** capabilities:"

Is a VS Code extension that doesn't use LSP, still a "language server"?

**Comment by dbaeumer** [comment]
The semantic token API is proposed in the LSP libraries. See here: https://github.com/microsoft/vscode-languageserver-node

**Comment by dbaeumer** [comment]
Please track the progress there to see when this will be official avaible. The proposal is here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.semanticTokens.proposed.ts
