### ISSUE TITLE
TreeView is not refreshing

### ISSUE THREAD

**Issue by aRajeshKumar** [microsoft/vscode-extension-samples#305]
The documentation mentioned in https://code.visualstudio.com/api/extension-guides/tree-view#updating-tree-view-content and the source code is not actually reflecting.

_onDidChangeTreeData.fire() requires a data item as a parameter as per the compiler. But, documentation and examples are not addressing it.

**Comment by alexr00** [comment]
If you take a look at the API [here](https://code.visualstudio.com/api/references/vscode-api#TreeDataProvider%3CT%3E) and the same API:
https://github.com/microsoft/vscode/blob/6c9f5fa0821cf7fcf003cf9ecd7e279746a211f5/src/vs/vscode.d.ts#L7901-L7906

You can see that it does not always require a parameter.
