### ISSUE TITLE
task-provider-sample is using proposed API, why?

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode-extension-samples#306]
Reading through the [guide here](https://code.visualstudio.com/api/extension-guides/task-provider), it shows some examples of creating tasks, and then links to the [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/task-provider-sample) which is using proposed API's. This is hella confusing. 

https://github.com/microsoft/vscode-extension-samples/blob/8f289726b86309a71dbe8e670adcacea51972e63/task-provider-sample/package.json#L7

https://github.com/microsoft/vscode-extension-samples/blob/8f289726b86309a71dbe8e670adcacea51972e63/task-provider-sample/src/customTaskProvider.ts#L72-L76

As an extension author trying to understand how to use these API's, i have no idea what `vscode.Task2` is. Why has it been done like this?

**Comment by alexr00** [comment]
When we have new proposed API, a good way to show folks how to use it is in the extension samples. Once the API was finalized, the sample should be updated. Thanks for the reminder!

**Comment by badsyntax** [comment]
Sorry I'm not entirely following. Theres conflicting information, the docs link to something that is not reflected in the docs. Why don't you have separate examples for the proposed API to prevent confusion?

**Comment by badsyntax** [comment]
Nevermind, I see the examples have been updated. Thanks.
