### ISSUE TITLE
webview tab can't modify

### ISSUE THREAD

**Issue by orentoga** [microsoft/vscode-extension-samples#319]
I run an angular app in the webview (the app is 'paint').
I want after the user has a change the x icon will replace to circle (like all text files, when user change the file), it is possible?
**Before:**
![1](https://user-images.githubusercontent.com/67014553/84797216-3bec8180-b002-11ea-9a37-69c7bb57413c.png)

**After changes:** (Angular app will run postMessage commend that we have changes, and the vs-code extension.ts will mark this tab like a document that not saved)
![2](https://user-images.githubusercontent.com/67014553/84797758-d947b580-b002-11ea-81d6-5d67d990a377.png)

**Comment by orentoga** [comment]
@mjbvz  ???

**Comment by mjbvz** [comment]
Use a custom editor: https://code.visualstudio.com/api/extension-guides/custom-editors
