### ISSUE TITLE
npm failed to install lsp-multi-root-example modules

### ISSUE THREAD

**Issue by g1hanna** [Microsoft/vscode-extension-samples#32]
I'm having problems with the multi-root language server on Ubuntu 16.04 running VSCode 1.8.1. When I ran "npm install" inside the lsp-multi-root-example folder, I received an error during execution. Here's a snapshot of the console where this problem occured:

![vscode-multirootserver-npmerror](https://user-images.githubusercontent.com/26070706/30749745-55315118-9f82-11e7-903b-45aa95ffce5f.png)

The breaking point was
**> node ./node_modules/vscode/bin/install**

Apparently, when I tried installing node, Linux told me that the program was obsolete or outdated and that it didn't have a candidate I could download instead. Could you change this to use nodejs instead of node or some other substitution?

Much appreciated,
Gabe

**Comment by dbaeumer** [comment]
Unfortunately this will break other platforms and node is an established name for the node  executable. We use it at other places as well.
