### ISSUE TITLE
event.fire function in NodeDependencies.ts of tree-view-sample uses confusing API

### ISSUE THREAD

**Issue by venkateshpotluri** [microsoft/vscode-extension-samples#321]
the [fire function here](https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/nodeDependencies.ts#L14) takes zero arguments and pressing F12 shows that it uses a fire method with an optional argument. When I try to replicate this code in a new extension that I initiate with the yo code command following the VSCode first extension tutorial, using fire results in the compiler expecting one argument. and pressing F12 shows that the interface for fire has a required parameter. It would be less confusing if the sample code is updated, or documentation is provided for what the parameter must be.

**Comment by sandy081** [comment]
From the API the event can fire without any arg. 

> When I try to replicate this code in a new extension that I initiate with the yo code command following the VSCode first extension tutorial, using fire results in the compiler expecting one argument.

**Comment by alexr00** [comment]
Looks like a problem with the difference between undefined and void. Probably resulting from one of the engineering clean up efforts we've had.

**Comment by alexr00** [comment]
I'll update the sample to include void.
