### ISSUE TITLE
What do the semantic tokens modifiers do?

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode-extension-samples#324]
Token types affect the coloring, but I don't see the modifiers doing anything in the sample.

Some extra questions:

1) Is it possible to customize the coloring for token types?
2) In F# the unused variables have lighter coloring than used ones and I want to do the same for my own language. Is it possible to do this through semantic tokens? If so how? If not, what should I use for this?

**Comment by aeschli** [comment]
Semantic tokens are described by a type also an with any number of modifiers.

The colors for these tokens are defined by color themes. Additionally, users can customize the theme's styling rules.

- themes can define styling rules that match against type and/or modifiers. `"semanticTokenColors" property in the theme file: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming
- we have a number of default mappings that map semantic tokens to textmate scopes. If a theme has already theming rules for these tokens: default mappings are listed here: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map

Users can overwrite theming rules through the `editor.semanticTokenColorCustomizations` setting:
```
"editor.semanticTokenColorCustomizations": {
    "[Rouge]": {
        "enabled": true,
        "rules": {
            "*.declaration": { "bold": true }
        }
    }
}
```
This is an example of a theeming rule that matches against a modifier.

See https://github.com/microsoft/vscode-extension-samples/blob/master/semantic-tokens-sample/README.md for more examples.

2. 'Unused` is not through semantic highlighting but through diagnostics: https://github.com/microsoft/vscode/blob/c8146b02c89371fd2946458d0a805da777bb27f8/src/vs/vscode.d.ts#L4964
