### ISSUE TITLE
onLanguage:javascript  can't active my extension.

### ISSUE THREAD

**Issue by Alizwell** [microsoft/vscode-extension-samples#325]
I just do a simple change based on the hello world example.

Changes:  Add contents **onLanguage:javascript** and **onLanguage:typescript** for the **activationEvents** attr in the **package.json** file.

Expect: When I open a js file, I can see the Congratulations info from the console.

But when I open a js file, I can't see the Congratulations console info, and when I open a ts file, I can see the console log.

![onLanguageIssue](https://user-images.githubusercontent.com/9283889/87132551-a07cc280-c2c8-11ea-9d24-0da58482a054.gif)

My changes are as follows.

``
       "activationEvents": [
		"onLanguage:javascript",
		"onLanguage:typescript"
	],
``

Is this the right result? Or I need to do some change.

**Comment by mjbvz** [comment]
Your have a file association that makes `*.js` be treated as `JavaScript react`. Add  `onLanguage:javascriptreact`to fix this
