### ISSUE TITLE
Go to Definition sample

### ISSUE THREAD

**Issue by kmcyjm** [microsoft/vscode-extension-samples#327]
Hi,

Could you please publish an example for implementing the 'Go to Definition' feature?

I am planning to implement this feature for a proprietary programming language. I have checked how this is done in Python/Go, however, they are really not newbie friendly, especially I am still new to TypeScript.

If such a sample is available that will do great help to those having the same needs!

Thanks!

**Comment by mjbvz** [comment]
Closing this due to lack of further feedback. 

In general though, implementing `go to definition` is quite similar to many other language features, such as [completions](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample)
