### ISSUE TITLE
lsp-sample: does nothing after packaging and installation

### ISSUE THREAD

**Issue by jan-dolejsi** [Microsoft/vscode-extension-samples#33]
I am not sure how or which part of the language server sample is supposed to be packaged. It works great in debugger, but when I package the top level package.json or the ./client/package.json (using `vsce package`) and install the *.vsix, the extension does not work. 
I tried adding the activation event and the configuration sections from the `./client/package.json` to the  top level, nothing. I tried adding the missing 'engines' to the `./client/package.json` ... nothing.
Can you update the sample or readme.md?

**Comment by fripSide** [comment]
You should run vsce package in the client's directory as the server module is compiled into client/server folder. eg:
cd client
vsce package .

**Comment by dbaeumer** [comment]
@fripSide this is correct. Closing the issue.

**Comment by paulhocker** [comment]
please note that I had to add "typescript" to devDependencies section of package.json in the client folder in order to make this work - tsc is only available when run from root project folder

**Comment by ankitpriyarup** [comment]
Running vsce package . in client made the vsix package for me but it didn't work. I also added 'typescript' to devdependencies. Tried console.log in client while activate seems like vsix package isn't even getting activated.

**Comment by Razzeee** [comment]
Is this still how it should be done or was the repo reorganized? As the top level package json only knows most stuff.

**Comment by Razzeee** [comment]
Ok, seems like this is outdated, vsce needs to be run on the top level folder for the lsp sample
