### ISSUE TITLE
when i run a helloworld example after ‘npm install’,vscode show that it keeps building and seems not to stop

### ISSUE THREAD

**Issue by oakpromise** [microsoft/vscode-extension-samples#331]
![image](https://user-images.githubusercontent.com/7379305/88450980-d2c01f80-ce85-11ea-8314-7a09116faa01.png)
as show above. 
while i clone official example , it has the same problem. keep building all the time until I forced to close the vscode

**Comment by 1024th** [comment]
I met the same problem. Did you solved it?
And I find some strange things. When I run the extension, `out/extension.js` and `out/extension.js.map` is generated. When I delete `tsconfig.json` file, then `out` folder will not be generated, but if there is `out` folder generated before, the extension would use it and the extension host could successfully run.

**Comment by JounQin** [comment]
Should be related to https://github.com/microsoft/vscode/issues/104157 and https://github.com/microsoft/vscode/issues/103390

**Comment by magictomagic** [comment]
do not choose webpack.
```shell
? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? helloword
? What's the identifier of your extension? helloword
? What's the description of your extension?
? Initialize a git repository? Yes
? Bundle the source code with webpack? No
? Which package manager to use? npm
```

**Comment by mjbvz** [comment]
Closing as this should be filed against VS Code itself (and seems like it may have already been fixed upstream)
