### ISSUE TITLE
How to replace variables by custom task provider?

### ISSUE THREAD

**Issue by kaysonwu** [microsoft/vscode-extension-samples#337]
I'm writing a custom task provider, but I can't find the variable replacement method exposed by `vscode`. Should I write it myself or I can't find it?

**Comment by kaysonwu** [comment]
@alexr00 Hi, may I ask you to answer?

**Comment by alexr00** [comment]
Please see the API proposal here: https://github.com/microsoft/vscode/issues/81007

**Comment by alexr00** [comment]
You can see examples of how task definitions are added to package.json here: https://github.com/microsoft/vscode-extension-samples/blob/aa174fe79657d9b69cdb6cd2c6306c50c49b512d/task-provider-sample/package.json#L18-L51

**Comment by kaysonwu** [comment]
Here I only see nested types, I want type reuse, e.g `$ref`
