### ISSUE TITLE
CompletionItem data property

### ISSUE THREAD

**Issue by itsxallwater** [microsoft/vscode-extension-samples#338]
Hello!

In the `lsp-sample` repo there's some code in [server.ts](https://github.com/microsoft/vscode-extension-samples/blob/69409d5e5f992423623c0ee032d3e83e60da469b/lsp-sample/server/src/server.ts#L199) that builds the `CompletionItem` records for use with the extension. The sample includes a `data` property that doesn't seem to be defined in the [CompletionItem](https://code.visualstudio.com/api/references/vscode-api#CompletionItem) docs and, in our localized testing, doesn't seem to make a difference when present or otherwise.

This is really just a question as to whether or not that property is necessary and if so, @brentlblair and I are looking for some clarity on what it impacts. He's finishing up a [PR](https://github.com/mvextensions/mvbasic/pull/121) for a language server extension where we're doing some dynamic/custom IntelliSense construction.

Thanks :)

**Comment by jrieken** [comment]
The vscode-dts API keep instances around and therefore doesn't need a data-property
