### ISSUE TITLE
TreeView open by default - why?

### ISSUE THREAD

**Issue by orentoga** [microsoft/vscode-extension-samples#341]
I run the extension
all the tree views are close by default.
only my new 'NEW TREE ITEM' is open by default.
How i can closed it by default (like the rest)

![Untitled](https://user-images.githubusercontent.com/67014553/92085558-a7f4af80-edd1-11ea-8ddd-0c10753de004.png)

**Comment by orentoga** [comment]
help!!!!
someone here?

**Comment by RMacfarlane** [comment]
@orentoga You can use the "visibility" property to control how a view is displayed by default. For example:

```
"views": {
			"explorer": [
				{
					"id": "newTree",
					"name": "New Tree",
					"visibility":  "collapsed"
				}
			]
		},
```

Note that this only sets the initial value - once you have changed the state at all by collapsing, expanding, or hiding it, that state will be remembered and used.

**Comment by orentoga** [comment]
@RMacfarlane You sure?
its not working

And when I look at other extension it is also not there
