### ISSUE TITLE
is there a sample on how to make a  Activity Bar icon

### ISSUE THREAD

**Issue by Duui3111** [microsoft/vscode-extension-samples#344]
is there a sample on how to make a  Activity Bar icon

**Comment by misolori** [comment]
Check out the [tree-view-sample](https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/) and our [views containers docs](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers). Code reference is here:

https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/package.json#L27-L32
