### ISSUE TITLE
How to add "rename" to the file explorer treeview

### ISSUE THREAD

**Issue by dehilsterlexis** [microsoft/vscode-extension-samples#349]
VSCode allows you to click on a file and choose "rename" in the context menu. It then highlights the item and allows you to type in a new name. Can this be used in the treeview? If so, how?

**Comment by isidorn** [comment]
Forwarding to @alexr00 since I think she owns the custom trees. 
I have no plans of action here.

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode/issues/97190
