### ISSUE TITLE
cannot control svg elements in webview

### ISSUE THREAD

**Issue by spcidealacm** [microsoft/vscode-extension-samples#351]
When I embed an svg file in webview, I cannot use getSVGDocumate() to get the controller

eg:

HTML:
```<embed id="svg" src="vscode-resource:/User/vfg.svg" type="image/svg+xml"> </embed>```

JS:

```
const svg = document.getElementById("svg");
svg.onload = () => {
    console.log(svg);
    let svgDoc = svg.getSVGDocument();
    console.log(svgDoc);
}
```

It only get a null, do you have a way which makes sure I could handle it?

**Comment by spcidealacm** [comment]
"<embed id="svg" src="vscode-resource:/Users/public/vfg.svg" type="image/svg+xml"></embed>"

**Comment by mjbvz** [comment]
Please ask extension development questions over on stackoverflow
