### ISSUE TITLE
fsprovider-sample/src/extension.ts - Windows Defender throws virus warning

### ISSUE THREAD

**Issue by close-esolc** [microsoft/vscode-extension-samples#358]
After cloning the repo windows defender throws an virus warning according to the following file:

fsprovider-sample/src/extension.ts

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Backdoor%3aPHP%2fDirtelti.OD&threatid=2147761327

**Comment by revrenlove** [comment]
Possibly needs a simlar fix as that applied to [issue #104049 in the vscode repo](https://github.com/microsoft/vscode/issues/104049)

**Comment by jrieken** [comment]
closing as upstream issue
