### ISSUE TITLE
Method to extract each parent back to the root in an indented tree view

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode-extension-samples#359]
Sorry if this is the wrong place to ask this..
I have a tree with  5 indents  and would like to know the parent of each indent all the way back to the root. 
Or do I have to manually maintain a list of each parent as each indent is created?
Searched but not found anything that might help.

**Comment by alexr00** [comment]
@davidkjackson54 as the creator of the tree, it is up to you to maintain a mapping of child to parent if you want it.
