### ISSUE TITLE
Sample request: Using onDidChangeWorkspaceFolders

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-extension-samples#36]
I'm trying to subscribe to `onDidChangeWorkspaceFolders` in the server part of [my extension](https://marketplace.visualstudio.com/items?itemName=glen-84.sass-lint).

I changed:

```ts
const connection: IConnection = createConnection(new IPCMessageReader(process), new IPCMessageWriter(process));
```

To:

```ts
const connection = createConnection(ProposedFeatures.all);
```

To get access to `connection.workspace.onDidChangeWorkspaceFolders`. I have no idea if that should be done.

Now, when I run the extension, I get:

```
Error: Client doesn't support sending workspace folder change events.
```

I have no idea how to fix this. I can't find any relevant samples either.

**Comment by bpasero** [comment]
@dbaeumer this sounds like language-server related, so moving to you.

**Comment by dbaeumer** [comment]
@glen-84 I have updated the example lsp-multi-root-sample to demo this. Have a look at the initialized hook in the server.ts file.
