### ISSUE TITLE
onDidWriteTerminalData

### ISSUE THREAD

**Issue by XkijuX** [microsoft/vscode-extension-samples#361]
Im trying to use the onDidWriteTerminalData but it just errors when i run it:

Command 'Terminal API: Attach data listener' resulted in an error (Running the contributed command: 'terminalTest.onDidWriteTerminalData' failed.)

I have enabled enableProposedApi. 
What could be wrong (i know its not going to be added but i want to use it for a person project)

any idea on how i could solve this?
```
	"engines": {
		"vscode": "^1.47.0"
	},

	"devDependencies": {
		"@types/node": "^12.12.0",
		"@types/vscode": "^1.47.0",
		"@typescript-eslint/eslint-plugin": "^3.0.2",
		"@typescript-eslint/parser": "^3.0.2",
		"eslint": "^7.1.0",
		"typescript": "^4.0.2"
	}
```

**Comment by Tyriar** [comment]
This API won't work unless outside of an extension dev environment unless you're on an allow list we keep. We're not planning on making this stable so it's probably not worth trying to use it.
