### ISSUE TITLE
lsp-user-input-sample NOT working

### ISSUE THREAD

**Issue by feich-ms** [microsoft/vscode-extension-samples#364]
I'm trying the lsp-user-input-sample sample and it is breaking. When I choose to debug server, below exception was thrown. I tried multiple machines and always reproduced.

![image](https://user-images.githubusercontent.com/43032123/100093678-b967b980-2e0c-11eb-9b8a-e62ce635af49.png)

**Comment by dbaeumer** [comment]
I am not able to reproduce this. Could it be that the port is already taken by another program. If so you can change the debugging port here https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-user-input-sample/client/src/extension.ts#L15 and here https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-user-input-sample/.vscode/launch.json#L22
