### ISSUE TITLE
CSP 'wasm-eval' is not support in webview?

### ISSUE THREAD

**Issue by sknightq** [microsoft/vscode-extension-samples#366]
I was trying to add an [unity game](http://webassembly.org.cn/demo/Tanks/) in my extension using webview api.
But the console reported the error: webassembly.instantiate() wasm code generation disallowed by embedder, which resulted by CSP.
I tried to add  'wasm-eval' in script-src but it didn't work. However, it worked by using 'unsafe-eval'.
As the [StackOverflow](https://stackoverflow.com/questions/48523118/wasm-module-compile-error-in-chrome-extension) description, I think the 'wasm-eval' is better.

My vscode version is: 1.49.3  Chrome: 83.0.4103.122

**Comment by mjbvz** [comment]
This does not sounds like an issue with these samples so please file this against VS Code itself

(but also be sure to test in the latest VS Code version)
