### ISSUE TITLE
Make a component like bread-crumb menu 

### ISSUE THREAD

**Issue by phatNfqAsia** [microsoft/vscode-extension-samples#369]
Hello, I am making an extension to help move cursor in JSX easier but I can not see any API to make similar UI to the breadcrumbs (shown by press Cmd + Shift + .). Is this doable via the CallHierarchyProvider (to assign event handler to items of the call hierarchy)? Is there any other ways?

![image](https://user-images.githubusercontent.com/39822773/102706209-6b868a00-42c2-11eb-81bf-95364f8e4895.png)

**Comment by mjbvz** [comment]
The breadcrumbs are defined by the document symbols. You can use the document symbol provider api to customize what the breadcrumbs show

However there is no API support for creating custom UI like the breadcrumbs

**Comment by coolcorexix** [comment]
@mjbvz I take your guidance and work with DocumentSymbolProvider, but currently it is having this error https://github.com/microsoft/vscode/issues/156738 Please help me have a look 🥺
