### ISSUE TITLE
Debugging language servers without legacy protocol

### ISSUE THREAD

**Issue by emackey** [Microsoft/vscode-extension-samples#37]
All of the lsp samples still use the legacy debug protocol:

https://github.com/Microsoft/vscode-extension-samples/blob/79892a6eefac3836655386a927044cd15a1e6230/lsp-sample/.vscode/launch.json#L29

This is not working for me with Node 8 installed.  Can these be updated?

I tried switching mine to `inspector` instead of `legacy`, but I get an error message:

> Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:6009).

Where do I specify `--inspect` in the project?

**Comment by emackey** [comment]
With the `legacy` protocol, I get:

> Cannot connect to runtime; make sure that runtime is in 'legacy' debug mode.

**Comment by dbaeumer** [comment]
@emackey I checked all the lsp samples and only the lsp-sample still used the old legacy protocol. Fixed this.

**Comment by Catlite91** [comment]
Still have the problem?
Debugging with legacy protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:6009)

**Comment by emackey** [comment]
This fixed it, thanks!

**Comment by strongui** [comment]
@emackey How did this fix it for you? I'm still getting the error, what did you do?

**Comment by emackey** [comment]
@strongui I copied his changes from the linked changelist, e871f0099.  Specifically, the `debugOptions` defined in `extension.ts` needed to change to:

```
    let debugOptions = { execArgv: ["--nolazy", "--inspect=6009"] };
```
