### ISSUE TITLE
Request: Update the samples for `vscode-languageclient` 7.0.0

### ISSUE THREAD

**Issue by spencerkohan** [microsoft/vscode-extension-samples#373]
The examples no longer work when run with the dependency:

```
"vscode-languageclient": "^7.0.0"
```

It appears that `LanguageClient` and `ServerOptions` are no longer exported in this version, and the upgrade path is not clear.

**Comment by KamasamaK** [comment]
cc @dbaeumer

**Comment by dbaeumer** [comment]
Thanks for pointing out. Upgraded the example. Key is to import from the `node` subpath.

**Comment by rwalle** [comment]
@dbaeumer Could you update the code on the [Language Server Extension Guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) as well?

**Comment by rwalle** [comment]
Found the source for documentation, made some changes and created a pull request:
https://github.com/microsoft/vscode-docs/pull/4263

**Comment by dbaeumer** [comment]
Good point and thanks for the PR.
