### ISSUE TITLE
nodeDependenciesProvider in tree-view-example uses deprecated property 'rootPath'

### ISSUE THREAD

**Issue by SeedBoot** [microsoft/vscode-extension-samples#375]
Line 14 in [tree-view-example/extension.ts](https://github.com/microsoft/vscode-extension-samples/blob/a443e604bd70cce8d77845f97de0138bc1f2b123/tree-view-sample/src/extension.ts#L14) references the deprecated property `vscode.workspace.rootPath`.

After some searching I found this section of a document about [eliminating rootPath](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath).  Changing the above property to `vscode.workspace.workspaceFolders?.[0]?.name` eliminates the error. However I'm not sure if it's the most appropriate fix? The `DepNodeProvider`'s constructor argument would also have to be amended as follows: `private workspaceRoot: string | undefined`.

This also means the [Tree View API documentation](https://code.visualstudio.com/api/extension-guides/tree-view) requires updating too, as it also references the same deprecated property.

**Comment by wing324** [comment]
And you should also change 
`if (this.pathExists(path.join(this.workspaceRoot, 'node_modules', moduleName)))` to `if (this.workspaceRoot && this.pathExists(path.join(this.workspaceRoot, 'node_modules', moduleName)))` to avoid error.
