### ISSUE TITLE
Question: Testing - I need a vscode.ExtensionContext instance for activate

### ISSUE THREAD

**Issue by glenn2223** [microsoft/vscode-extension-samples#378]
Ref: Line 4 & 6 specifically
https://github.com/microsoft/vscode-extension-samples/blob/d81f44d8897cb8a6c249f498ce2ef3dea68f50ab/helloworld-test-sample/src/test/suite/extension.test.ts#L3-L6

---

How do I get an instance of `vscode.ExtensionContext` when my extension requires it?

Extension.ts
```TS
export async function activate(context: vscode.ExtensionContext): Promise<void> { }
```

Test.ts file
```TS
await myExtension.activate(??);
```

**Comment by mjbvz** [comment]
VS Code creates the extension context and calls `activate` with it. You don't create it yourself (and should not need to)

If you really need to explicitly activate your extension, use:

```ts
await vscode.extensions.getExtension('ext-id').activate();
```

**Comment by glenn2223** [comment]
Ahh, I see. This makes more sense now.

My extension isn't loaded as there is no workspace with a specific file type included. Is there a way of stating a folder to open on test? Sorry to bother you again
