### ISSUE TITLE
Activating extension 'vscode-samples.custom-view-samples' failed: Cannot find module 

### ISSUE THREAD

**Issue by manicken** [microsoft/vscode-extension-samples#379]
Activating extension 'vscode-samples.custom-view-samples' failed: Cannot find module 'c:\_githubClones\vscode-extension-samples-master\tree-view-sample\out\extension.js'
Require stack:
- c:\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

**Comment by epernst** [comment]
Had the same issue. I reinstalled Node.js and rebooted. Then it worked.

**Comment by mjbvz** [comment]
Closing this as I believe it is out of date

If you still see the issue with the latest version of the samples, please share additional information about how to reproduce this problem
