### ISSUE TITLE
Windows Antivirus flags as a backdoor on clone through GitHub Desktop

### ISSUE THREAD

**Issue by danperks** [microsoft/vscode-extension-samples#381]
Not done any testing on this but same issue as mentioned in #365 
On clone, Windows flags the file 'vscode-extension-samples\fsprovider-sample\src\extension.ts' as having a backdoor.
See screenshot here: https://i.imgur.com/2DfDyxb.png

Surely this can't be right, can it...

**Comment by jrieken** [comment]
closing as upstream
