### ISSUE TITLE
Securing Keys 

### ISSUE THREAD

**Issue by rupamkairi** [microsoft/vscode-extension-samples#385]
## I had a question regarding securing API keys or Environment Variables while using and Extension.
I am making an extension that saves some information from user and stores in a database. To upload information securely I need to make API calls using keys. Now I do not want to expose my API keys in repo or to the client. 
Is there a direct way to secure those keys or should I use a server-side application to make the database calls and convey the data to the client i.e., extension itself?
If you have any sample or any other thread relating to this you can refer me to that too.

**Comment by Delizald** [comment]
There's a secrets API on the SDK. Haven't used it myself though:

https://github.com/microsoft/vscode/issues/115160

https://code.visualstudio.com/api/references/vscode-api#SecretStorage

**Comment by rupamkairi** [comment]
Thank you for letting me know about the option, I'll look into that, Thanks.

**Comment by TylerLeonhardt** [comment]
Yep! The SecretStorage API is a good candidate for this. 😃
