### ISSUE TITLE
lsp-sample: Error while getting user settings in server.ts

### ISSUE THREAD

**Issue by Sarrus1** [microsoft/vscode-extension-samples#386]
Adding the following lines of code to [https://github.com/microsoft/vscode-extension-samples/blob/d56eef11a238a41b321d988aad34ee8598e1e8ac/lsp-sample/server/src/server.ts#L23](url) crashes the server on start with the error below.

```typescript
import {workspace as Workspace} from 'vscode';

let test = Workspace.getConfiguration("languageServerExample").get("maxNumberOfProblems");
console.debug(test);
```

```
Error: Cannot find module 'vscode'
Require stack:
- c:\Users\Charles\CloudStation\Documents\Perso\Dev\Test\server\out\server.js
    at Function._resolveFilename (internal/modules/cjs/loader.js:1019:15)
    at internal/modules/cjs/loader.js:895:27
    at Function._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (c:\Users\Charles\CloudStation\Documents\Perso\Dev\Test\server\out\server.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1199:30)
    at Object..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at internal/modules/cjs/loader.js:932:14 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\Charles\\CloudStation\\Documents\\Perso\\Dev\\Test\\server\\out\\server.js'
  ]
}
```

Steps to reproduce:
- Add the lines of code above here [https://github.com/microsoft/vscode-extension-samples/blob/d56eef11a238a41b321d988aad34ee8598e1e8ac/lsp-sample/server/src/server.ts#L23](url).
- Update package.json by adding `"@types/vscode"` as a dependency.
- run `npm install` and compile.
- The extension will crash on start.

Is this intended and if yes is there a way to get the Workspace's extensions' settings in `server.ts` in lsp-sample?

Thanks in advance!

**Comment by dbaeumer** [comment]
You can't add `vscode` to the server. VS Code API is only available on the client. To read settings please use code like this: https://github.com/microsoft/vscode-extension-samples/issues/412
