### ISSUE TITLE
Webview View sample doesn't work when using VSCode Remote SSH

### ISSUE THREAD

**Issue by samwho** [microsoft/vscode-extension-samples#397]
I typically do my work on a Windows host, using VSCode remote into an Arch Linux guest running on VirtualBox. Here are the steps I took when first trying out the Webview View sample:

1. Open up VSCode as normal, and connect to my virtual machine using VSCode Remote SSH.

From this point on, everything is done from inside the VSCode Remote SSH session.

2. Clone the vscode-extension-samples repo: `git clone git@github.com:microsoft/vscode-extension-samples.git`.
3. Open `code` in the Webview View sample: `code vscode-extension-samples/webview-view-sample`.
4. Press F5 to debug the extension.

We can see the Calico Colors pane rendered correctly:

![image](https://user-images.githubusercontent.com/338027/112752431-db479780-8fca-11eb-8088-08cfe33e5a61.png)

But clicking on the `Add Color` button doesn't do anything.

Opening up the `Developer: Open Developer Webview Tools` by using Ctrl+P and I see the following errors:

![image](https://user-images.githubusercontent.com/338027/112752450-ffa37400-8fca-11eb-80d1-ba65e74abecb.png)

The exact same project, when run outside of VSCode Remote SSH, just running natively on Windows, works flawlessly.

Is there some additional setup that needs to be done when using VSCode Remote? Pretty much everything else about extension development appears to work in this configuration, except loading local resources inside of a webview.

**Comment by SirWalross** [comment]
I am experiencing the same behaviour while using VSCode Remote WSL.

But if the WebView has to reload, by for example switching to the search tab and back the recourses are being loaded correctly:

![image](https://user-images.githubusercontent.com/27106448/113492118-d193c780-94d5-11eb-9c84-a6baca144a4f.png)

**Comment by mjbvz** [comment]
This is an issue with VS Code itself (which very likely has already been fixed)

If you are still seeing it please file an issue against the VS Code repo with steps to reproduce
