### ISSUE TITLE
Recommended GIF tooling

### ISSUE THREAD

**Issue by felicio** [Microsoft/vscode-extension-samples#40]
FOA, thank you for curating very informative documentation suite for VS Code product. I'd like to ask what GIF tooling do you recommend for generating illustrative assets to go with extensions that will land in the Marketplace?

**Comment by gregvanl** [comment]
[ScreenToGif](http://www.screentogif.com/) works well on Windows.

**Comment by prichodko** [comment]
Give a look at https://getkap.co/.

**Comment by taoqf** [comment]
Any tools on Debian?

**Comment by taoqf** [comment]
I got peek

**Comment by andrekosak** [comment]
> Give a look at https://getkap.co/.

Thats really a great tool! Just used it, work perfectly
