### ISSUE TITLE
How to create button in view container

### ISSUE THREAD

**Issue by KunalBurangi** [microsoft/vscode-extension-samples#402]
I wanted to know how can I create a button on views and add on click event? 
for example
![image](https://user-images.githubusercontent.com/37167732/114277317-5045b300-9a48-11eb-87bc-7ab81d7c5c36.png)

so as an attached image there are buttons like share, join I want to take inputs from the user and then do some tasks. how should I proceed?

**Comment by KamasamaK** [comment]
That is defined in [`contributes.viewsWelcome`](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome). It doesn't appear that there is any sample for using that in this repo.

**Comment by KunalBurangi** [comment]
Can i create a form in there ?? Which user has to fill and according to that the task will get perform.

**Comment by KamasamaK** [comment]
No, that example was for a TreeView, which only allows a tree or welcome content when empty.

For that kind of content, you'll want a [webview view](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample).

**Comment by losidk** [comment]
@KamasamaK Can you take a moment to look at my issue [https://github.com/microsoft/vscode-extension-samples/issues/407](url)
