### ISSUE TITLE
LSP Log Streaming Sample - Adding grammar file to package.json stops code completion from working

### ISSUE THREAD

**Issue by k-jay-c** [microsoft/vscode-extension-samples#404]
I am quite new to LSP and am working with the samples and trying to update to get a better understanding of how to develop them.  I am trying to take the existing LSP Log Streaming Sample and update it so that it works for a new language using extension .nso.  Here are the steps I've taken so far:

1. Update the package.json file to activate on new extension
  ```json
 "activationEvents": [
    "onLanguage:nso"
  ],
"main": "./client/out/extension",
  "contributes": {
        "languages": [
            {
                "id": "nso",
                "extensions": [
                    ".nso"
                ]
            }
        ],
```

2. Update extension.ts to register for .nso documents:
```typescript
// Options to control the language client
    const clientOptions: LanguageClientOptions = {
        // Register the server for .nso documents
        documentSelector: [
            { scheme: 'file', language: 'nso' },
            { scheme: 'untitled', language: 'nso'}
        ],
        synchronize: {
            // Notify the server about file changes to '.clientrc files contained in the workspace
            fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
        },
        // Hijacks all LSP logs and redirect them to a specific port through WebSocket connection
        outputChannel: websocketOutputChannel
    };
```

After making the above changes, and running the example, code completion still worked as expected. Setting the filetype to nso on the editor, code completion shows the option of 'Typescript' and 'Javascript' automatically when you enter 'J' or 'T'.

Next, I've added an existing Yaml grammar file to the workspace and added configuration for grammar in package.json for the .nso extension:

```json
  "activationEvents": [
    "onLanguage:nso"
  ],
  "main": "./client/out/extension",
  "contributes": {
        "languages": [
            {
                "id": "nso",
                "extensions": [
                    ".nso"
                ]
            }
        ],
    "grammars": [
            {
                "language": "nso",
                "scopeName": "source.nso",
                "path": "./syntaxes/nso.tmLanguage.xml"
            }
        ],
```

For the testing I am doing, I've just used a pre-existing Yaml language file that can be found [here](https://github.com/textmate/yaml.tmbundle/blob/master/Syntaxes/YAML.tmLanguage).

After adding the above JSON configuration and running the example, the auto completion stops working. The editor applies the syntax highlighting from the grammar file but if I type in letters 'J' or 'T', I see no code completion. Invoking code completion manually using Ctrl + Space works, but I cannot figure out why adding the grammar file stops it from working automatically. If I remove the grammars config from package.json file, the auto completion starts working again.

Would greatly appreciate if anyone has any ideas.

**Comment by dbaeumer** [comment]
I recommend that you use the normal lsp-sample as a starting point. The Log streaming example is only useful if you need to visualize LSP traffic.

**Comment by dbaeumer** [comment]
Are the message on the server still be called?
