### ISSUE TITLE
Does the webview of the vscode plug-in support running on the online vscode?

### ISSUE THREAD

**Issue by losidk** [microsoft/vscode-extension-samples#407]
I now want to use webview-related plug-ins in the online vscode, but the webview cannot be displayed normally on the browser

![image](https://user-images.githubusercontent.com/33344293/116020893-bc93f980-a679-11eb-860c-3ce0c67fbfa7.png)

**Comment by justinmk3** [comment]
Is that safari? Did you try other browsers?

**Comment by losidk** [comment]
It's chrome ，I also use the  official example:  calico-colors, and also was't work ,but they all worked well at the vscode client(mac); I suspect there might be a problem with configuration items like the PublicPath in Webpack

**Comment by losidk** [comment]
It seems that the problem just occurred at  when I used the webview in extension

**Comment by mjbvz** [comment]
What VS Code version are you using. The 1.53 in the link looks like an old version

**Comment by losidk** [comment]
yes, I use the 1.53, I will try the  new version, thanks you very much
