### ISSUE TITLE
Tree View Sample: Ability to display a badge

### ISSUE THREAD

**Issue by kubawolanin** [Microsoft/vscode-extension-samples#41]
Hello,
In the [tree-view-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample) there's a nice example of how to create e.g. a Refresh button on the tree view.

I'd like to add a badge with a number indicating total count of the items that are stored in my tree.
Similar thing is visible on the "Changes" tree view for VCS:
![image](https://user-images.githubusercontent.com/2270505/32796947-785e8652-c970-11e7-8b6f-27167b8854bf.png)

I'm wondering whether it's possible for me to have that too.
I'd appreciate any help.

CC: @sandy081 

EDIT: Just found that in the Git extension it's called `countBadge`:

https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json#L828

Is it exposed somewhere?

Thank you all for the tremendous work!

**Comment by sandy081** [comment]
@kubawolanin No Badges are not supported in Tree views. 

Please file any issues or feature requests [here](github.com/Microsoft/vscode/)
