### ISSUE TITLE
Can Language Servers that read "local" files work with virtual workspaces?

### ISSUE THREAD

**Issue by sgranade** [microsoft/vscode-extension-samples#413]
I have a language server for a programming language that, when a workspace is open, finds the project's main file and parses it to analyze its dependencies. I'd followed the advice in #132 to find and open the file locally from disk. Given the push to support [virtual workspaces](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces), is there any way for my extension to replicate the parse-"local"-files behavior with virtual workspaces? My extension is structured along the lines of the [LSP sample code](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample).

**Comment by dbaeumer** [comment]
We are working on a FS API for Language servers. Until that is available servers can't access files in a virtual workspace. What you can do in preparation is to make sure all your FS code is async since the LSP FS requests will be async as well.

**Comment by dselman** [comment]
> We are working on a FS API for Language servers. Until that is available servers can't access files in a virtual workspace. What you can do in preparation is to make sure all your FS code is async since the LSP FS requests will be async as well.

Has there been progress on this, or is there another GitHub issue I should watch? I'm currently in the process of rewriting the [Accord Project VSCode extension](https://github.com/accordproject/vscode-extension) as a Web Extension and would love to have this feature.

**Comment by dbaeumer** [comment]
There are issue and PRs in the LSP repository. But know big progress so far.
