### ISSUE TITLE
how to modify the reminder ( like the number ) onto the Tree View Container icon ? 

### ISSUE THREAD

**Issue by serenahappyhacking** [microsoft/vscode-extension-samples#425]
Hey guys, I recently confused about how to control the status of the Tree View Container icon?  like,  if my customized extension is released a new version, I wanna give some prompt onto the icon (like the number or some other stuff ),  however, that I didn't get any relevant API about that when I go through the document. 

Anybody could help me ? thanks !

![image](https://user-images.githubusercontent.com/29164467/118957423-16df5c00-b993-11eb-8e9a-2874b339c17e.png)

**Comment by sandy081** [comment]
This is not yet supported - https://github.com/microsoft/vscode/issues/62783
