### ISSUE TITLE
Add terminal profile example to terminal-sample

### ISSUE THREAD

**Issue by 4086606** [microsoft/vscode-extension-samples#448]
There has to be a way to add extension terminals into the "New Terminal" menu...

<img src="https://user-images.githubusercontent.com/82655227/118046357-20543d00-b371-11eb-9912-b7a19d5a269a.png" height="412px" width="412px" />

~~It seems like Python has done it, but that extension has a HUGE number of features and I can't isolate this one~~ Python doesn't have this feature..

**Comment by 4086606** [comment]
@DonJayamanne any idea how Microsoft did this?

**Comment by meganrogge** [comment]
@Tyriar added this last iteration https://code.visualstudio.com/updates/v1_57#_terminal-profile-contributions

**Comment by Tyriar** [comment]
Note that it's still proposed, the plan is to make it stable in 1.58

**Comment by 4086606** [comment]
Alright, I will open a PR to add it into this repo if that isn't already here
(Also thanks for all your work on VSC! It's helped me out countless times)

**Comment by 4086606** [comment]
As `vscode-python` product owners, could you add a terminal profile to that repository?

**Comment by Tyriar** [comment]
> As vscode-python product owners, could you add a terminal profile to that repository?

@karrtikr FYI, not sure if you've considered adding a profile so it comes up in this dropdown?

<img width="251" alt="Screen Shot 2021-06-30 at 1 39 13 PM" src="https://user-images.githubusercontent.com/2193314/124028186-8f7d0380-d9a8-11eb-96bb-f42371eca3a2.png">

**Comment by 4086606** [comment]
Although it goes live in a few days of course :)
