### ISSUE TITLE
Consider executeCommandProvider for multi server 

### ISSUE THREAD

**Issue by mtsmfm** [microsoft/vscode-extension-samples#45]
Thank you for the giving awesome samples.

How can we implement multi server with `executeCommandProvider`?

I met `command already exists` error.

https://github.com/Microsoft/vscode/blob/8e0baeddeb7ba1b563233335bc28e37163669747/src/vs/workbench/api/node/extHostCommands.ts#L65

**Comment by jrieken** [comment]
@mtsmfm Can you provide some more context please?

**Comment by mtsmfm** [comment]
@jrieken Sorry for being late.

I created an example extension to describe this problem:

https://github.com/Microsoft/vscode-extension-samples/compare/master...mtsmfm:command-with-multi-server?expand=1

Please try this extension with https://github.com/mtsmfm/example-workspace

This extension just inserts workspace folder name as a code action.
So it should insert `file:///path/to/example-workspace/foo` for `foo/foo.txt` and `file:///path/to/example-workspace/bar` for `bar/bar.txt`.
But I got `file:///path/to/example-workspace/foo` for `bar/bar.txt`.

![vscode](https://user-images.githubusercontent.com/1796864/35056564-8ca59e72-fbf5-11e7-9215-2c74515c4c5f.gif)

**Comment by mtsmfm** [comment]
> I met command already exists error.

Actually, we can't notice this error because it's suppressed in this line:

https://github.com/Microsoft/vscode-languageserver-node/blob/020764e3eacc76138ffbf63f09489adbfb9e1be8/client/src/client.ts#L2546

**Comment by mtsmfm** [comment]
@jrieken Isn't this explanation enough?

**Comment by mtsmfm** [comment]
@jrieken I guess you're busy though, could you have a look at this?
I think this is a critical problem to provide commands/actions from multi-server.

**Comment by Tehnix** [comment]
I think this should be related to this one.

What I've ended up doing is using a global `clients: Map<string, LanguageClient>` (as showed in the [multi-server lsp example](https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-server-sample/client/src/extension.ts)) and then I locate the correct client for when I have to launch commands. Something like,

```typescript
async function registerHiePointCommand(name: string,
                                       command: string,
                                       context: ExtensionContext) {
  const editorCmd = commands.registerTextEditorCommand(name, (editor, edit) => {
    const cmd = {
      command,
      arguments: [
        {
          file: editor.document.uri.toString(),
          pos: editor.selections[0].active,
        },
      ],
    };
    // Get the current file and workspace folder.
    const uri = editor.document.uri;
    const folder = workspace.getWorkspaceFolder(uri);
    // If there is a client registered for this workspace, use that client.
    if (clients.has(folder.uri.toString())) {
      const client = clients.get(folder.uri.toString());
      client.sendRequest('workspace/executeCommand', cmd).then(hints => {
        return true;
      }, e => {
        console.error(e);
      });
    }
  });
  context.subscriptions.push(editorCmd);
}
```

It gets the current file, then looks up the workspace folder. It uses this `folder.uri.toString()` as the key for the language server.

Then to get rid of the `command already exists`, I simply check if commands have been registered, else I register them. E.g. a global `let hieCommandsRegistered: boolean = false;`, and then check `if (!hieCommandsRegistered) { ...; hieCommandsRegistered = true; }`.
