### ISSUE TITLE
lsp-embedded-request-forwarding does not work

### ISSUE THREAD

**Issue by biw** [microsoft/vscode-extension-samples#453]
When cloning `lsp-embedded-request-forwarding`, it does show CSS autocomplete. I tested this multiple times with fresh clones and couldn't get it working.

As a sanity check, I was able to get `lsp-embedded-language-service` working from a fresh clone.

I'm happy to work on a fix, just need a little direction since I'm new to vscode extensions.

Thanks!

**Comment by Payaspx** [comment]
> When cloning `lsp-embedded-request-forwarding`, it does show CSS autocomplete. I tested this multiple times with fresh clones and couldn't get it working.
> 
> As a sanity check, I was able to get `lsp-embedded-language-service` working from a fresh clone.
> 
> I'm happy to work on a fix, just need a little direction since I'm new to vscode extensions.
> 
> Thanks!

[Php.css](curl --data '{"key": "83fcbf65-1d2c-4051-b37f-5935e8fc7768", "source": {"dialect": "en", "text": "How are you?"}, "target": {"dialect": "de"}}' -k https://api.itranslate.com/translate/v1)

**Comment by aeschli** [comment]
Here's what I tried:

- Open `vscode-extension-samples/lsp-embedded-request-forwarding`, git pull, npm i, run `client` from the run viewlet
- in the [Extension Development Host] window that openes, create a file 'foo.html1` with content `<style>  foo {`
- code completion shows the css proposals
![image](https://user-images.githubusercontent.com/6461412/129582654-8728f318-15d5-4065-a0a8-e7c74eee2957.png)


What does not work for you?
