### ISSUE TITLE
Share data between two plugins

### ISSUE THREAD

**Issue by pilzandreas** [microsoft/vscode-extension-samples#454]
Is there any non-hacky way to share data between plugins in a RXJS like manner?
The global an workspace memento objects are not what I am looking for...

**Comment by KamasamaK** [comment]
Your extension can export a public API by returning a custom API object in your extension's `activate`. Another extension can use your extension's API via [`Extension.exports`](https://code.visualstudio.com/api/references/vscode-api#Extension%3CT%3E). I'm not sure if or where this is properly documented, and I don't know if there's an extension sample that does this, but there probably should be. I've found a good example is the bundled [Git extension](https://github.com/microsoft/vscode/blob/4fc8dc82f3552ff9a5b65db4375dcc5b6afb5aff/extensions/git/src/main.ts#L185).

**Comment by pilzandreas** [comment]
That's a good hint - will check it out - thank You!
