### ISSUE TITLE
Compile Problems

### ISSUE THREAD

**Issue by Sadik** [microsoft/vscode-extension-samples#456]
According to the [language server extension guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) all I have to do is:

> git clone https://github.com/microsoft/vscode-extension-samples.git
> cd vscode-extension-samples/lsp-sample
> npm install
> npm run compile

But I get the following errors: 

> 
> === Running compile on terminal-sample ===
> 
> > vscode-terminal-api-example@0.0.1 compile /home/soezoguz/lsp/vscode-extension-samples/terminal-sample
> > tsc -p ./
> 
> src/extension.ts:184:43 - error TS2339: Property 'registerTerminalProfileProvider' does not exist on type 'typeof window'.
> 
> 184  context.subscriptions.push(vscode.window.registerTerminalProfileProvider('terminalTest.terminal-profile', {
>                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/extension.ts:185:89 - error TS2694: Namespace '"vscode"' has no exported member 'TerminalProfile'.
> 
> 185   provideTerminalProfile(token: vscode.CancellationToken): vscode.ProviderResult<vscode.TerminalProfile> {
>                                                                                             ~~~~~~~~~~~~~~~
> 

My OS: CentOS 8
npm --version: 6.14.11

Am I missing something?

**Comment by Tyriar** [comment]
Pulling and running npm install again should fix
