### ISSUE TITLE
How to add a new treeview as children to an existing treeview

### ISSUE THREAD

**Issue by vickyvishal** [microsoft/vscode-extension-samples#463]
I have my refresh command up and running. I want to dynamically add children to a treeview and refresh it. This is my code which doesnt work

`const newTreeItem: TreeItem[] = this.treeItem;
				if(newTreeItem[0].children && newTreeItem[0].children[0].children){
					newTreeItem[0].children[0].children.push(new TreeItem("Something", item.treeItems, new ThemeIcon("database")));
					this.treeItem = newTreeItem;
					this.refresh();
				}`

However when I try to add children one level up like this:
`newTreeItem[0].children.push(new TreeItem("Something", item.treeItems, new ThemeIcon("database")));`

It does work. Is it the right way to add dynamically? Why does it work for the 2nd example

**Comment by vickyvishal** [comment]
Looks like It has to do with `vscode.TreeItemCollapsibleState`. If I make it `TreeItemCollapsibleState.Collapsed` in construction then it does show the newly added children when it is `TreeItemCollapsibleState.Expanded`. So, I need to also change the `TreeItemCollapsibleState` when I add or remove nodes.

**Comment by aady501** [comment]
are you able to update the `TreeItemCollapsibleState` dynamically from `Collapsed` -> `Expanded`. It is not working for me, I am not able to expand the node programatically.
