### ISSUE TITLE
Completion API doesn't move cursor to position in test

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode-extension-samples#468]
I'm writing a language server, I can see code completion working when used interatively. My text fixture has:
`inter`, and I expect that setting the cursor at the end of that word will bring up a few completions, e.g. `interface`, `interface_name`, etc.

```ts
test('Completes inte in IDL file', async () => {
  await testCompletion(docUri, new vscode.Position(0, 5), {
    items: [
      { label: 'interface', kind: vscode.CompletionItemKind.Keyword },
      { label: 'interface_name', kind: vscode.CompletionItemKind.Keyword },
      { label: 'target_interface', kind: vscode.CompletionItemKind.Keyword },
      { label: 'default_interface', kind: vscode.CompletionItemKind.Keyword },
    ]
  });
});
```

However what I'm seeing, despite setting the position as (0,5), the completions I get are for the position (0,0).

Am I doing something wrong?  I haven't been able to figure out why the cursor *doesn't* get moved before invoking completion

**Comment by jrieken** [comment]
> However what I'm seeing, despite setting the position as (0,5), the completions I get are for the position (0,0).

There is little information here but I assume you having the case of completing at a word-end. In that case the word start position is used as suggest anchor
