### ISSUE TITLE
Validate color themes in CI

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode-extension-samples#474]
I'd like to add a pipeline to my upcoming theme that checks that the theme is valid.
There are no schemas in https://github.com/SchemaStore/schemastore/tree/231a34/src/schemas/json/ for VSC color theming. :(

Alternatively, is there a way for a CI to launch the theme in a new window and check that the theme throws no problems?

(Might need to ping Martin on this one..)

**Comment by SNDST00M** [comment]
Hey @aeschli any straightforward way to dump this data as a JSON?

- https://github.com/microsoft/vscode/blob/1.59.0/src/vs/workbench/services/themes/common/colorThemeSchema.ts
- https://github.com/microsoft/vscode/blob/1.59.0/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L265
- https://github.com/microsoft/vscode/blob/1.59.0/src/vs/platform/theme/common/colorRegistry.ts#L604

**Comment by aeschli** [comment]
The color-theme schema is computed based on the registry of colors and contributed colors from extensions.
It is provided at `vscode://schemas/color-theme` by a TextDocumentContentProvider.
You can write an extension that opens that document in an editor, if you want to look at it and store it. But as said, the contents depends on the extensions installed and colors contributed.
You can use the vscode-json-languageservice to validate a JSOn document against a schema. [Here](https://github.com/microsoft/vscode-json-languageservice/blob/42fe736a0a6fa1aca18bfff03ca84752591d82fc/src/test/schema.test.ts#L1253) is an sample for that.

As this is not an issue against  vscode-extension-samples (more like a vscode question) I close it.

**Comment by SNDST00M** [comment]
Thanks for the comprehensive answer. It's great that I don't have to download VSC electron either

**Comment by SNDST00M** [comment]
Does `const schema = { $ref: 'vscode://schemas/color-theme' };` work?

**Comment by aeschli** [comment]
Yes, vscode://schemas/color-theme is only resolvable when running inside vscode.

**Comment by SNDST00M** [comment]
I implemented this and it worked:

https://github.com/SNDST00M/starfall-visual-studio-code/blob/08b25d70b13f7f719b09ef47051a15a496b1b7f2/themes/test/suite/starfall-color-theme.test.ts#L16-L47

**Comment by SNDST00M** [comment]
ALright, thanks for the help
