### ISSUE TITLE
How to use Custom Editor  API with Virtual Documents

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode-extension-samples#477]
Hi I am looking for dirty indicator for webview, so created an issue in vscode https://github.com/microsoft/vscode/issues/129822

But they pointed me to custom editor api, the current example works with physical documents, for my use case I dont use files.

Can you provide an example of custom editor api for virtual docs similar to webview.

Here is my extension [Thunder Client ](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client)

<img width="1280" alt="Screenshot 2021-08-03 at 11 28 43" src="https://user-images.githubusercontent.com/8637550/128001903-ac2b4cb9-41f0-4f0e-aa64-d61df73db380.png">

Like to show dirty indicator like below in my extension webview

![Screenshot 2021-07-30 at 08 25 20](https://user-images.githubusercontent.com/8637550/127617430-3b16f4b6-c5a1-477a-943d-660fe58ac307.png)

**Comment by mjbvz** [comment]
What have you tried so far? This is a niche use case so we probably won't add a sample for it here

**Comment by rangav** [comment]
what should I try, when I can't find an example of how to use your api with virtual documents
