### ISSUE TITLE
How can a language server cache files. Is there a default directory to use

### ISSUE THREAD

**Issue by corno** [microsoft/vscode-extension-samples#511]
If a language server wants to cache files that it downloads from the internet, how can it determine the right directory for that?

**Comment by dbaeumer** [comment]
A server should use the configuration request to ask a client about this information (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration). The client should then depending on its API provide the server with a good location. In VS Code this is a value that can be accessed from the extension context.
