### ISSUE TITLE
Suggestion: Use `degit` to install extension samples

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-extension-samples#519]
Hello! 👋

Lead dev on the [Webview UI Toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit) here.

As part of the toolkit documentation, we have our own [extension sample repository](https://github.com/microsoft/vscode-webview-ui-toolkit-samples) that was closely modeled after this repo.

Recently, we made a quality of life improvement to the getting started/install instructions for each of the toolkit samples that I think could potentially be very useful in this sample repo.

Instead of asking people to clone the entire GitHub repo and then manually navigate to and open the desired sample extension directory, we now have a simple set of command-line instructions that use [degit](https://www.npmjs.com/package/degit) to directly copy any given sample extension directory locally much faster than git clone.

For those who don't know, `degit` is a tool made by Rich Harris (the creator of Rollup and Svelte) that:

> ... makes copies of git repositories. When you run degit some-user/some-repo, it will find the latest commit on https://github.com/some-user/some-repo and download the associated tar file to `~/.degit/some-user/some-repo/commithash.tar.gz` if it doesn't already exist locally. (This is much quicker than using git clone, because you're not downloading the entire git history.)

By using this tool (and its ability to also copy subdirectories of GitHub repos), the resulting install instructions look something like this in the case of the toolkit:

<img width="940" alt="Screen Shot 2021-10-27 at 3 14 03 PM" src="https://user-images.githubusercontent.com/39639992/139155965-997c2b65-db83-4f7e-bb92-b71233125ed7.png">

If this is something that sounds desirable for this sample extension repo, **_I would be more than happy to open a PR with changes to the documentation on each sample_**.

Let me know what you think and no hard feelings whatsoever if it's decided that this change is not wanted. 🙂

cc @daviddossett @misolori

**Comment by mjbvz** [comment]
For simplicity, I think our documentation should stick to common tools instead of introducing potentially  unfamiliar ones like `degit`. If users prefer, they can use `degit` instead

**Comment by hawkticehurst** [comment]
Sounds totally reasonable to me! 👍
