### ISSUE TITLE
Bind custom command in vscode extension

### ISSUE THREAD

**Issue by pathakrohit08** [microsoft/vscode-extension-samples#520]
I am building an extension using typescript where I need to have a custom logic before save command is executed.

```
 context.subscriptions.push(
    vscode.commands.registerCommand("workbench.action.files.save", () => {
       /* 
          1. Execute custom logic
          2. save the file 
       */
    })
  );

```

Also there is a save command in the menu bar. How can I hook these commands to my `extension.ts` so that my custom logic gets executed?

**Comment by KamasamaK** [comment]
How does this relate to VS Code samples? You should ask questions like this at [StackOverflow](https://aka.ms/vscodestackoverflow) or [VS Code Dev Slack](https://aka.ms/vscode-dev-community).

You do not want to override the native save command. You probably just need to use [`workspace.onWillSaveTextDocument`](https://code.visualstudio.com/api/references/vscode-api#workspace.onWillSaveTextDocument).
