### ISSUE TITLE
Font name in the document-editing-sample

### ISSUE THREAD

**Issue by javigaralva** [microsoft/vscode-extension-samples#522]
Hello!
I just having a look in the extension samples and I wonder what font is this
https://raw.githubusercontent.com/microsoft/vscode-extension-samples/main/document-editing-sample/demo.gif

@joanrieu, Can you help me? ;)

Thanks!

**Comment by joanrieu** [comment]
Hello @javigaralva, I believe the font was Monofur. Enjoy! 😉
