### ISSUE TITLE
How important is it to "dispose" `client.start()`? Why do some examples `push(client.start())`, and others do not?

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-extension-samples#526]
[Searching this repository for `= client.start()`](https://github.com/microsoft/vscode-extension-samples/search?q=%3D+client.start%28%29) has 7 results at the time of this writing; five results do `client.start()` without assigning it to anything or disposing it.

[One result does](https://github.com/microsoft/vscode-extension-samples/blob/66223aae68dbea6313b80aecbcac99e8605c21b4/lsp-web-extension-sample/client/src/browserClientMain.ts)
```ts
const disposable = client.start();
context.subscriptions.push(disposable);
```

and [another does](https://github.com/microsoft/vscode-extension-samples/blob/63d86e3a0e459b2adf26487204891f7af62898ce/lsp-user-input-sample/client/src/extension.ts)

```ts
context.subscriptions.push(
  client.start(),
);
```

What are the benefits to doing this, and how dangerous is it if a developer _doesn't_ do

```ts
context.subscriptions.push(
  client.start(),
);
```

or

```ts
const disposable = client.start();
context.subscriptions.push(disposable);
```
?

**Comment by aeschli** [comment]
The disposables in `context.subscriptions` are all disposed when the extension is deactivated as it got disabled or uninstalled.

The disposable of `client.start()` terminates the language server process and unregister all language providers.

A correctly implemented extension does not leave back any resources when the extension is deactivated. 

So yes, you should do it.

**Comment by hamirmahal** [comment]
I see. Thank you for clarifying!
