### ISSUE TITLE
Can we stop using es6 as a target?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-extension-samples#530]
Looks like the examples still target ES6 for the code output. ES6 is almost 7 years old.

I can understand this for older browsers but VSCode doesn’t need this. As of v1.60 (and probably older) ES2020 can be used, this means a lot of boilerplate and polyfills don’t need to be generated reducing the final output.

It would be useful to update the examples to use a more up to date version of JavaScript.

**Comment by mjbvz** [comment]
The majority of samples already uses `es2019`. I'll update the few that don't and bump them all to `es2020`

**Comment by jasonwilliams** [comment]
Thanks @mjbvz
