### ISSUE TITLE
How can I set the title of VirtualDocument?

### ISSUE THREAD

**Issue by niwla23** [microsoft/vscode-extension-samples#534]
In virtual-document-sample it seems that the title of the tab is equal to the given text, instead of being the whole text of the file. I am unable to find the line in the example that sets a title. How is it done? In my extension it displays the whole content on hover and a cut-off version by default.

**Comment by niwla23** [comment]
I want this:
https://github.com/Microsoft/vscode-extension-samples/raw/main/virtual-document-sample/cowsay.gif

But have this:
![image](https://user-images.githubusercontent.com/46248939/143723381-55f9a582-0a52-40d2-8f1a-479c7ec7775b.png)

**Comment by jrieken** [comment]
The path or the uri of a virtual document defines its name, so `someScheme://path/with/name.txt` will use `name.txt` as name
