### ISSUE TITLE
compile custom-editor-sample failed, VSCode not responding

### ISSUE THREAD

**Issue by Codes-Breaker** [microsoft/vscode-extension-samples#538]
I tried to put custom-editor source code into vscode source code extensions but got following errors:

`../../node_modules/@types/wicg-file-system-access/index.d.ts:16:81` - error TS2304: Cannot find name 'PermissionState'.

../../node_modules/@types/wicg-file-system-access/index.d.ts:17:83 - error TS2304: Cannot find name 'PermissionState'.

17     requestPermission(descriptor?: FileSystemHandlePermissionDescriptor): Promise<PermissionState>;
                                                                                 
~~~~~~~~~~~~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:53:50 - error TS2304: Cannot find name 'PermissionDescriptor'.

53 interface FileSystemPermissionDescriptor extends PermissionDescriptor {
                                                ~~~~~~~~~~~~~~~~~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:81:61 - error TS2304: Cannot find name 'BufferSource'.

81     | { type: 'write'; position?: number | undefined; data: BufferSource | Blob | string }
                                                           ~~~~~~~~~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:81:76 - error TS2304: Cannot find name 'Blob'.

81     | { type: 'write'; position?: number | undefined; data: BufferSource | Blob | string }
                                                                          ~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:85:33 - error TS2304: Cannot find name 'BufferSource'.

85 type FileSystemWriteChunkType = BufferSource | Blob | string | WriteParams;
                               ~~~~~~~~~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:85:48 - error TS2304: Cannot find name 'Blob'.

85 type FileSystemWriteChunkType = BufferSource | Blob | string | WriteParams;
                                              ~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:93:44 - error TS2689: Cannot extend an interface 'WritableStream'. Did you mean 'implements'?

93 class FileSystemWritableFileStream extends WritableStream {
                                          ~~~~~~~~~~~~~~

../../node_modules/@types/wicg-file-system-access/index.d.ts:105:24 - error TS2304: Cannot find name 'File'.

105     getFile(): Promise<File>;
`

when i run the editor, the window shows no responding after few edits and stuck forever...

**Comment by hamirmahal** [comment]
What's the output when you run `npm install`?

**Comment by Codes-Breaker** [comment]
> 

I think I am doing a wrong thing. I am trying to build the extension code in vs code source code extensions folder....

**Comment by hamirmahal** [comment]
I think you want to build in `/custom-editor-sample`, instead, if that's the example you're using.

What happens when you do that?

**Comment by mjbvz** [comment]
Closing as this sounds like a general coding question, not an issue with the extension sample itself
