### ISSUE TITLE
Doc clarification

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode-extension-samples#54]
In this step in the readme, "open this folder in VS Code. In the Debug viewlet, run 'Launch Client' from drop-down to launch the extension and attach to the extension.", please be sure to specify that "this folder" means the client folder. I spent hours trying to debug from the root folder.

**Comment by cfjedimaster** [comment]
Sorry, this is for the language server example.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode-extension-samples/pull/55
