### ISSUE TITLE
Is there a way to mark code parts as unreachable and gray-out their colors?

### ISSUE THREAD

**Issue by Zensonaton** [microsoft/vscode-extension-samples#543]
I'm developing a extension with semantic tokens && language server support, and I want to make some parts of code grayed-out, as seen in this screenshot with Python:
![image](https://user-images.githubusercontent.com/66683075/146409230-c577e98a-cb9b-4a53-be38-120532168f2b.png)
I have no idea which token type/token modifier to use to get similar effect. `Developer: Inspect Editor Tokens and Scopes` shows no difference between "normal" and "grayed-out" code.

**Comment by KamasamaK** [comment]
This is accomplished through Diagnostics, not Semantic tokens. You will want to use the `tags` property with `DiagnosticTag.Unnecessary`.

**Comment by Zensonaton** [comment]
This is working, huge thanks! :wave: 

Code snippet for researchers:
```ts
const diagnostic: Diagnostic = {
	range: {
		start: startPos,
		end: endPos
	},
	message: description,
	tags: [
		DiagnosticTag.Unnecessary
	]
}

diagnostics.push(diagnostic)
```

**Comment by Zensonaton** [comment]
For some reason, VSCode marks code as error, even if `DiagnosticSeverity` is not set, and I don't want this behavior.
Screenshot:

![image](https://user-images.githubusercontent.com/66683075/146496663-d8b3e56d-b8be-4364-a45c-fed7e88caf04.png)

My code looks like this:
```ts
var diagnostic: Diagnostic = {
	range: {
		start: startPos,
		end  : endPos
	},

	message: "Unreachable code test",
	tags: [ DiagnosticTag.Unnecessary ],
	// severity: DiagnosticSeverity.Error
}

diagnostics.push(diagnostic)

// ...

connection.sendDiagnostics({ 
	uri: 			uri, 
	diagnostics: 	diagnostics
})
```

How to resolve this issue?

**Comment by Zensonaton** [comment]
To fix that issue, I've had to use `severity: DiagnosticSeverity.Hint` with `DiagnosticTag`.

![image](https://user-images.githubusercontent.com/66683075/146502957-9a360721-0ebd-4ef9-9530-cdd063d49524.png)
