### ISSUE TITLE
How to disable right click context menu in custom editor (copy/paste/cut)?

### ISSUE THREAD

**Issue by Codes-Breaker** [microsoft/vscode-extension-samples#544]
How to disable right click context menu in custom editor (copy/paste/cut)?

**Comment by Codes-Breaker** [comment]
![image](https://user-images.githubusercontent.com/10660055/147084656-75b4f998-c2f1-4b73-b63d-51b56aa96c8b.png)

**Comment by pugg11** [comment]
Dog

**Comment by pugg11** [comment]
Hack

**Comment by pugg11** [comment]
[122232438](owId=mgv2ResetPassword-flow&_flowExecutionKey=e1s1) 

> 

> `
![1639385289145](https://user-images.githubusercontent.com/96555888/147177471-9a0e6075-b10a-4978-8861-11209599e2f8.gif)
`

**Comment by pugg11** [comment]
Hahaha

**Comment by Codes-Breaker** [comment]
is it even possible to hide it in custom editor?
