### ISSUE TITLE
webview-view-sample bug

### ISSUE THREAD

**Issue by alexzerntev-raw** [microsoft/vscode-extension-samples#547]
I'am using most of this [samples code](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample) I noticed that if the webview-view is not the last one as in the example but it is in the middle of other views then the overall view gets messed up after accordion expansion and collision.

Before:
![before](https://user-images.githubusercontent.com/89914618/149335989-fc8b74d9-ad8d-4603-9318-0cb1877ff784.png)

Mid:
![mid](https://user-images.githubusercontent.com/89914618/149336041-81c5f910-6a13-48fb-86d3-0e9b485f866f.png)

After:
![after](https://user-images.githubusercontent.com/89914618/149336065-f836e04b-e4c3-4740-b045-f8f8bce4d394.png)

If i swap the middle view with the last, the issue goes away

**Comment by mjbvz** [comment]
This doesn't sound specific to the sample so please file an issue against VS Code itself
