### ISSUE TITLE
How to enable part of Semantic Highlighting Rules ?

### ISSUE THREAD

**Issue by fisheva** [microsoft/vscode-extension-samples#551]
I want to enable  part of  Semantic Highlighting Rules in my [Eva Theme](https://marketplace.visualstudio.com/items?itemName=fisheva.eva-theme). 
When I turn `semanticHighlighting` true, all the rules are actived. 
![企业微信截图_20220128112402](https://user-images.githubusercontent.com/17448419/151482809-7b4df203-8a41-4fcc-9172-4520ecb541f7.png)
But I just want to open `parameter`、`function`、`method` Semantic Highlighting Rules at this time. How can I do? Thanks!
![企业微信截图_20220128112917](https://user-images.githubusercontent.com/17448419/151482695-15156e49-a40f-4ded-9e10-153848ea2f25.png)

**Comment by aeschli** [comment]
Now you can add a `semanticTokenColors` property and define colors for `parameter`, `function` and `method`. See [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes) for an example.

You can't prevent that other semantic tokens types are also generated too, but they will be rendered using colors you defined in tokenColors based on fallback rules as defined [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map).

Use the [scope inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) tool to understand what color is used.

**Comment by aeschli** [comment]
Closing the issue but speak up if that doesn't work for you.
