### ISSUE TITLE
Use `enabledApiProposals`

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-extension-samples#555]
The new `enabledApiProposals` should be used instead of the deprecated `enableProposedApi` in the official samples that [use proposed APIs](https://code.visualstudio.com/api/advanced-topics/using-proposed-api).

The samples that still use the old method are:

- [`inline-completions`](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions)
  - [x] `inlineCompletions`
- [`terminal-sample`](https://github.com/microsoft/vscode-extension-samples/tree/main/terminal-sample)
  - [ ] `terminalDataWriteEvent`
  - [ ] `terminalDimensions`

Note that even though [`comment-sample`](https://github.com/microsoft/vscode-extension-samples/tree/main/comment-sample) and [`extension-terminal-sample`](https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample) use `enableProposedApi`, they do not currently use any actual proposed APIs. Also, [`extension-terminal-sample`](https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample) refers to "Proposed API" in its README, but those APIs were finalized.

**Comment by KamasamaK** [comment]
33d18813de5633c1506a65fcb4bcd33b1f89cbb2 erroneously added `vscode.proposed.d.ts` to [`test-provider-sample`](https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample).

As for [inline-completions](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions), the README still refers to the old method.

**Comment by Tyriar** [comment]
`enableProposedApi` seems to be all gone now
