### ISSUE TITLE
LSP-WEB sample fails when published together with a different target

### ISSUE THREAD

**Issue by jakubmisek** [microsoft/vscode-extension-samples#560]
The `lsp-web-extension-sample` build results in two .js files (browserClientMain.js and browserServerMain.js) (although docs say the extension should consist of a single file only https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-main-file).

When this extension is packed and published on the marketplace **standalone**, it can be installed and activated and used on vscode.dev without an issue.
```
vsce publish -t web
```

**However;** for some reason, when we have two extensions with the same ID targeting different platforms, the web extension's `browserServerMain.js` file fails to load - the `https://***.vscode-unpkg.net/<publisherid>/<extensionid>/<extensionversion>/server/dist/browserServerMain.js` does not exist, the server returns **404**. The file `browserClientMain.js` (the "browser" entry point) is there.

_first (win32-x64) ext:_
```
vsce publish -t win32-x64
```

_second (web) ext:_
```
vsce publish -t web
```

Activating the _web_ extension results in a javascript error caused by the 404 above:
```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://****.vscode-unpkg.net/****/****/****/extension/server/dist/browserServerMain.js?target%3Dweb' failed to load.
    at blob:https://cb049561-26f3-4410-847a-e2da21253db2.vscode-webview.net/319d41ae-c413-4e45-a41a-4cbc850307df:1:410
    at blob:https://cb049561-26f3-4410-847a-e2da21253db2.vscode-webview.net/319d41ae-c413-4e45-a41a-4cbc850307df:1:415
```

Maybe this is more likely an issue for the marketplace web?

**Comment by isidorn** [comment]
@jakubmisek Thanks for filling this issue. This should just work as you are publishing a platform specific extension.

@aeschli @sandy081 can you help?

**Comment by jakubmisek** [comment]
Thank you for the reply; the actual URLs and version that are live now:

extension: `devsense.phptools-vscode`
version: `1.6.8482`

The vsix seems to be incompletely extracted to the `https://devsense.vscode-unpkg.net` . There are two `.js` files that are contained in the vsix, but only one is available:

https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/extension/client/dist/main.js <-- OK
https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/extension/server/dist/server.js <-- Not Found

Both files are in the VSIX. Once the VSIX is published alone without the other target, files will be there.

**Comment by isidorn** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
Both those URLs are 404. And you can use the unpkg service to inspect what's inside: https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/extension/

**Comment by jakubmisek** [comment]
This URL (https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/extension/) is not showing the correct content tho. It lists the content of the first VSIX (win32-x64). But the content of the second published package (target web) is not listed, although its `main.js` file is there.

**Comment by joaomoreno** [comment]
Oh yeah got it. When I use `target=web` both URLs work just fine:

- https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/extension/server/dist/server.js?target=web
- https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/extension/client/dist/main.js?target=web

**Comment by jakubmisek** [comment]
@joaomoreno that's it!

**Comment by jakubmisek** [comment]
@joaomoreno 

We have published the updated version; so far it seems the behavior is a bit inconsistent.

Extension: `DEVSENSE.phptools-vscode`
Version: `1.6.8588`

The extension couldn't load `server.js?target=web` for the first time.

Once we have did a request to `server.js?target=web` from the browser, the extension works fine then. It works fine on other browsers and other machines as well. Can we rely on that?

**Comment by joaomoreno** [comment]
@sandy081 Any thoughts?

**Comment by sandy081** [comment]
It seems, the extension is directly loading these resources from our unpkg service. I am not aware of the implementation of unpkg service and AFIK the service download the VSIX if not available and should serve the resources. @joaomoreno you might be best person to know what's happening in the unpkg service and why the resources in the extension are not being served

**Comment by jakubmisek** [comment]
@sandy081 The extension is requesting the resource as instructed in the sample:
https://github.com/microsoft/vscode-extension-samples/blob/e52c48f22a81355b568f3cde8c60538726caad22/lsp-web-extension-sample/client/src/browserClientMain.ts#L41

**Comment by joaomoreno** [comment]
It seems that the sample just needs to be adjusted to account for platform specific extensions.

> Once we have did a request to `server.js?target=web` from the browser, the extension works fine then. It works fine on other browsers and other machines as well. Can we rely on that?

But this confuses me. It doesn't make much sense. @jakubmisek Can you reproduce this 100%?

**Comment by jakubmisek** [comment]
@joaomoreno I can't actually, and it seems the file from unpkg service is served just fine now.

We have been experimenting with Web extensions for the past two weeks, and the unpkg service was returning 404 for that file. We have tried a lot of deployments, in various orders and combinations, and none of them worked, even with `?target=web` in the URL.

It seems, a few days ago, something has changed? since it's not reproducible anymore, the issue can be closed.

**Comment by joaomoreno** [comment]
Actually, that made me realize that there's indeed an issue!

The unpkg service is backed by Front Door which handles all caching. I just confirmed that it currently ignores query params when caching. We should fix that.

**Comment by aeschli** [comment]
Adding `?target=web` to the serverMain path will break running locally on the [desktop](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vs-code-running-on-desktop) as well using [@vscode/test-web](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-a-browser-using-vscodetestweb).

You can try this out with the [lsp-web-extension-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-web-extension-sample).

IMO users should not have to deal with that.

**Comment by joaomoreno** [comment]
@aeschli Any thoughts on how to solve it? The unpkg service needs to respect a `target` query param... so it needs to be set from the asset requester.

**Comment by aeschli** [comment]
Some (random) thoughts:

* Can the `web` be part of the path instead of a query param? I think things would become easier.
e.g. `https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8482/web/extension/...`
We use URIs for hierarchical resources and do operation like `dirname` or `joinPath` on them. The query parameter doesn't work well with that as it's unclear what to do with a query parameter in such path operations. If `web` were part of the `context.extensionUri` all would work without change.

* Can the unpack service serve web resources by default? My understanding is that ithe unpack service's main purpose is to be used by web extensions. So, IMO if no traget is specified, web resources would be served.

* From the 404 log in the description `The script at 'https://****.vscode-unpkg.net/****/****/****/extension/server/dist/browserServerMain.js?target%3Dweb' failed to load.`
it see that `?target%3Dweb` was already added. So maybe @sandy081 has already thought about this?

**Comment by joaomoreno** [comment]
> * Can the unpack service serve web resources by default? My understanding is that the unpack service's main purpose is to be used for web extensions. So, IMO if no traget is specified, web resources would be served.
> *

That's hard to do without impacting the performance of the unpkg service. It would require one additional call to the MP, which we want to avoid.

> * From the 404 log in the description `The script at 'https://****.vscode-unpkg.net/****/****/****/extension/server/dist/browserServerMain.js?target%3Dweb' failed to load.`
>   it see that `?target%3Dweb` was already added. So maybe @sandy081 has already thought about this?

Yeah good point, @sandy081 is there some magic here?



> * Can the `web` be part of the path instead of a query param? I think things would become easier.

Definitely worth considering.

**Comment by joaomoreno** [comment]
So then we're OK? This specific incident might just have happened because FrontDoor had incorrect caching rules, which we have just fixed.

**Comment by jakubmisek** [comment]
we're only noticing that after some period of time, the first attempt to load our extension in _vscode.dev_ results in the following error in console:

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://devsense.vscode-unpkg.net/DEVSENSE/phptools-vscode/1.6.8588/extension/server/dist/server.js?target=web' failed to load.
```

which is caused by 404 I guess;

After refreshing the page, the `server.js` file loads correctly and the extension works just fine.

**Comment by aeschli** [comment]
IMO the problem is really that this is a query parameter and now everybody has to be super careful when using joinPath to preserve that query parameter. Our resources utolity do, but very linkly maybe users just use `path.posix` to append to the URL.
I think we should switch to adding `web` in the path and avoid query parameters.

**Comment by sandy081** [comment]
We expose URI utilities in our vscode API and it is recommended that extension to use that util and also if extension is not handling uri joins correctly, is not that extension has to fix it, instead of we change URI format?

**Comment by sandy081** [comment]
After talking to @aeschli I agree that having `target` in the path makes it easy to append paths especially for language servers who do not have access to vscode API. 

@joaomoreno This has to be supported in both vscode-unpkg and vscode.

**Comment by jakubmisek** [comment]
We're using the vscode API and the `?target=web` gets appended properly; Still, the first attempt to access the resource almost always fails.

**Comment by joaomoreno** [comment]
> everybody has to be super careful when using joinPath to preserve that query parameter

Yeah, doesn't `joinPath` keep the query param? That's one of the reasons we have the util. Doing string magic on URIs is also usually a bad idea, so I'm not sure optimizing for a solution to honor that is a good idea.

**Comment by aeschli** [comment]
As explained above,
query params don't go well with hierarchical URIs
`foo://server/bar/file?a=b`. Does `?a=b` belong to `file` or the full path?
Should it be preserved or not when computing a child-page or the parent page?

You can see the browser's URL resolve does not preserve it:
![image](https://user-images.githubusercontent.com/6461412/155564462-586109f3-f692-4235-9f4d-f15117eb2e4f.png)

So better avoid query parameters in resource URIs if possible.

**Comment by jakubmisek** [comment]
Alright, I have noticed the vscode API appends `?target%3Dweb` instead of `?target=web` ... that's what's causing the issue actually.
