### ISSUE TITLE
Update https://github.com/microsoft/vscode-extension-samples/blob/main/progress-sample/src/extension.ts

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-extension-samples#565]
I think it would be more illustrative if we had a version of https://github.com/microsoft/vscode-extension-samples/blob/main/progress-sample/src/extension.ts without `setTimeout`.

Extension authors aren't really showing progress bars after doing `setTimeout` for some number of milliseconds. It would be more realistic if we did `progress.report` after some synchronous task, even if the task is some simple placeholder like `for (let i = 1; i <= 10000; i++) console.log(i);`, for example.

**Comment by mjbvz** [comment]
Typically you should not long running sync code. The most common flows you'd want to report progress for would involve multiple async steps — such as fetching from the network or interacting with the file system

settimeout is a good approximation that lets us show the  basic functionality of the api without getting bogged down in specifics of what a given async task actually does or how it is implemented

**Comment by hamirmahal** [comment]
Ah, I see. Thanks for the clarification!
