### ISSUE TITLE
How to see my extension's marketplace info using extension API

### ISSUE THREAD

**Issue by KartikM123** [microsoft/vscode-extension-samples#577]
Hi all!

I recently wanted to bake in some automatic versioning management into my vscode extension. In order to do so, I need to have access to two main things:
1. What the latest version of my vscode extension available on the marketplace is-- eg. If I'm on 5.3.1, I want to ping latest to see how far behind I am; say latest is `5.6.1` then it would be nice to just see that
2. How long has my extension been released/what datetime was it released.

Does anyone know a good API/vscode library I can use to do this? I tried using the vscode extension API but wasn't able to find a good endpoint to hit.

If there's nothing for my request, I'm wondering if there's an API I can use to read information off of the extension marketplace. Any feedback would be greatly appreciated!

**Comment by mjbvz** [comment]
Closing this issue as it is a dev question and not about the extension samples
