### ISSUE TITLE
custom-editor-sample rename fails if only case is changed

### ISSUE THREAD

**Issue by jjuback** [microsoft/vscode-extension-samples#582]
Run custom-editor-sample and open example.cscratch. Rename file in explorer view to Example.cscratch. Fails with the error:
```
Unable to open 'Example.cscratch': Assertion Failed: argument is undefined or null.
```
Rename succeeds if the new filename is totally different, but fails if it differs only in case.

**Comment by mjbvz** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/146732
