### ISSUE TITLE
Progress report message display mechanism

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode-extension-samples#602]
https://github.com/microsoft/vscode-extension-samples/blob/513d20acf0aea623550c0b8b49c0685ee43b190c/progress-sample/src/extension.ts#L8

As the demonstration preview gif indicates, the message would **replace** the old one on each `report` invocation.

![](https://github.com/microsoft/vscode-extension-samples/blob/513d20acf0aea623550c0b8b49c0685ee43b190c/progress-sample/preview.gif?raw=true)

Whilst, I clone the project and install dependencies.  The progress bar message behaves like **appending** to the old one.

![real-progress](https://user-images.githubusercontent.com/24731539/161376238-61947234-f0ec-4910-b818-6e862fbddaaa.gif)

When I change the `title` to empty string in the first invocation `vscode.window.withProgress`, it works just like the illustration gif.

https://github.com/microsoft/vscode-extension-samples/blob/513d20acf0aea623550c0b8b49c0685ee43b190c/progress-sample/src/extension.ts#L10-L13

So, what is the expectation when progress `report` these message?

**Comment by mjbvz** [comment]
This sounds like a good question for StackOverflow or the main VS Code repo

**Comment by AkatQuas** [comment]
I have found some interesting [issue](https://github.com/microsoft/vscode/issues/50932) on this question. 

I'll try to add some documentation if necessary.

Seal this issue if possible.
