### ISSUE TITLE
How to use LSP to complet code

### ISSUE THREAD

**Issue by yangliguo7** [microsoft/vscode-extension-samples#604]
I couldn't find any information about this anywhere, so I might be missing something obvious - sorry if that's the case.

I want to use LSP to implement a snippets

in `lsp-sample` But this is the simplest example
https://github.com/microsoft/vscode-extension-samples/blob/fbdb9c5bc40f64489db00148d7f3bf6e161d9a8c/lsp-sample/server/src/server.ts#L190

But how can I implement alternative snippets of code  like pick color ？I checked the type of  `completionitem` . But I didn't find any 
more examples to understand what these fields mean.

**Comment by YangLG-7** [comment]
Can the extension display only three `red` `green` `blue` colors instead of all colors when I enter `color`?

**Comment by dbaeumer** [comment]
There are separate messages for color picking. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentColor
