### ISSUE TITLE
Language Server testing example

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode-extension-samples#62]
A while I ago I created a language server for Ember.js projects (https://github.com/emberwatch/ember-language-server). We initially forked the (old) example language server (https://github.com/Microsoft/vscode-languageserver-node-example) and built our LS on top of it. While we gave our best to test the language server, we were always missing basic integration tests. I tried creating integration tests a couple of times but somewhere on the way I always get stuck. I can imagine that this is a major problem for a lot of people that start working with the language server example.
So I think a basic integration test example could improve the language server example in this repository a lot.

What I would like to see in an example test would basically do:
1. Start the server and connect to it
2. Send a specified request
3. Check the response if it is correct

**Comment by octref** [comment]
This is resolved. See https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensions/example-language-server.md#testing-the-language-server and the updated sample code: https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample.

The doc will become public next week, but you can view it now on `vnext` branch of vscode-docs.
