### ISSUE TITLE
Race condition in custom-editor-sample catScratch editor?

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode-extension-samples#620]
The sample sets WebView HTML code and then calls `webview.postMessage` to send the document to the WebView. https://github.com/microsoft/vscode-extension-samples/blob/2556c82cb333cf65d372bd01ac30c35ea1898a0e/custom-editor-sample/src/catScratchEditor.ts#L49
However, at that time, the WebView script might not have set up the `window.addEventListener` yet. https://github.com/microsoft/vscode-extension-samples/blob/2556c82cb333cf65d372bd01ac30c35ea1898a0e/custom-editor-sample/media/catScratch.js#L77
In this case the extension WebView would remain blank and without any content.
What's the best way to improve that sample to avoid race condition?

**Comment by mjbvz** [comment]
You can post a `ready` message from the webview to the extension after the listeners have been added. Feel free to submit a simple PR that adds if you think this would be helpful to include in the example too
