### ISSUE TITLE
Best practices starting point for a VSCode debugger extension for a .NET IoT device....

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/vscode-extension-samples#625]
Hi,
  I was wondering if you have a best practices sample of implementing a C#/.NET debugger where by the code will be running on an IoT device. The debugger will be connecting via a port on the device.

**Comment by mjbvz** [comment]
This is out of scope of this repository. This repo shows how to implement various VS Code apis and is not about implementing features for specific languages
