### ISSUE TITLE
Configured debug type 'extensionHost' is not supported

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-extension-samples#626]
Trying to run the `test-provider-sample` but am running into errors on a clean install (also updated the vscode engine version):

<img width="590" alt="CleanShot 2022-04-26 at 15 36 30@2x" src="https://user-images.githubusercontent.com/35271042/165403969-d503c7c7-57ce-4eb5-afb1-0dde89fa30fb.png">

<img width="313" alt="CleanShot 2022-04-26 at 15 36 36@2x" src="https://user-images.githubusercontent.com/35271042/165403982-bff1d8fc-397e-4ee3-ad82-799f2841c477.png">

<img width="562" alt="CleanShot 2022-04-26 at 15 36 43@2x" src="https://user-images.githubusercontent.com/35271042/165403996-ca9f2fa4-31c2-462d-9774-3e3907f91f7c.png">

**Comment by connor4312** [comment]
Did you disable the js-debug extension? Search `@id:ms-vscode.js-debug` in the extensions view

**Comment by misolori** [comment]
Some how it did get disabled, not sure how, but thanks for finding that. Why do all of the error messaging not point to this and why doesn't the js debug extension show up when searching for "extensionHost" extensions? Not sure how others outside of the tea are able to figure that out.
