### ISSUE TITLE
When I compile a C file, the vscode is always Building and seems not to stop

### ISSUE THREAD

**Issue by SeeleVolle** [microsoft/vscode-extension-samples#627]
Well, it is just like the picture below.
Well, when I closed other extensions, it's still stuck here.
I have tried some of the methods, but they didn't work for me.

It happened today suddenly, I don't know how to solve it
<img width="1078" alt="屏幕截图 2022-04-27 222421" src="https://user-images.githubusercontent.com/93275435/165541450-f1d781cd-7f2d-4b16-99a4-8388ddac2e82.png">

<img width="674" alt="225" src="https://user-images.githubusercontent.com/93275435/165542747-befed921-57c9-494e-be8f-84ee20502b07.png">

**Comment by mjbvz** [comment]
Please file this against the C/C++ extension for VS Code
