### ISSUE TITLE
file peek

### ISSUE THREAD

**Issue by pakzad199** [microsoft/vscode-extension-samples#633]
is there any extension example for file peek??

**Comment by mjbvz** [comment]
What is file peek? Please share a screenshot

**Comment by pakzad199** [comment]
![Screenshot from 2022-05-06 23-14-37](https://user-images.githubusercontent.com/76616567/167199570-74d0e1d6-4ff0-481e-aa6d-fcebcb398c45.png)


lock at this, it available for css, vue , etc ...

**Comment by mjbvz** [comment]
To get peek ,you need to implement a [`DefinitionProvider`](https://github.com/microsoft/vscode/blob/6c8d8a2654dd5facc549a4f55dea15461ebbfdb0/src/vscode-dts/vscode.d.ts#L2563)

We don't provide samples for it because these provides are very simple
