### ISSUE TITLE
Do the webview samples work as web-extensions?

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode-extension-samples#638]
Should they?

Sorry if it's inappropriate to ask questions here about a sample's feature(s) but I want to build a small webview-view and have it work as a web-extension, and I thought of asking about it here.

**Comment by mjbvz** [comment]
Webviews work fine in web

To keep the samples simple, the webview samples focus on api usage but you can reference the web samples to enable them on web too

**Comment by boltex** [comment]
@mjbvz Thanks, I thought web-extensions could not load separate files such as css and/or bitmaps, etc. That's why I was asking if the webview-view samples would work as web-extensions.
