### ISSUE TITLE
Cannot debug server in lsp-web-extension-sample

### ISSUE THREAD

**Issue by Skleni** [microsoft/vscode-extension-samples#645]
I'm able to run the [lsp-web-extension-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-web-extension-sample) and it does what it's supposed to do. I'm not able to debug or even get any log messaged from the LSP server/web worker though.

The readme says:

> If you want to debug the server as well use the launch configuration Attach to Server

When I do that, it briefly shows up, but disappears again after a few seconds:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/10420514/169036600-5d041bd3-0d3e-41ae-9cf5-8db3f3680ce0.png">

Breakpoints aren't bound: 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/10420514/169036771-2212efce-f018-4660-b645-9c69a62c0a5c.png">

Also, there are no log messages. For example the the message `running server lsp-web-extension-sample` isn't shown in any of the output channels nor in the debug console. What the debug console *does* show is the following error:

```
ERR Error: ENOENT: no such file or directory, stat 'c:\Users\daniel.sklenitzka\AppData\Roaming\Code\logs\20220518T075600\exthost19\webWorker\exthost.log':
EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\daniel.sklenitzka\AppData\Roaming\Code\logs\20220518T075600\exthost19\webWorker\exthost.log'
    at r (C:\Users\daniel.sklenitzka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:28:4147)
    at r.toFileSystemProviderError (C:\Users\daniel.sklenitzka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:42483)
    at r.stat (C:\Users\daniel.sklenitzka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:34668)
```

I don't know if that's connected to one or both of the problems described above, but I also have no idea why the file isn't there and how I can fix it.

As I said, the language server itself is working correctly (the colors are visualized), I'm just not able to debug it or get any log messages to appear.

Any help is greatly appreciated.

**Comment by dbaeumer** [comment]
@connor4312 can you help with how a user can attach the VS Code debugger to a web worker thread.

@Skleni you should be able to debug this using the debugger from the Developer Tools.

**Comment by connor4312** [comment]
js-debug doesn't attach to nested other webworkers aside from the webworker extension host right now.

**Comment by dbaeumer** [comment]
OK. This seems to be related to how the debugger is working in VS Code.

**Comment by ejfasting** [comment]
@dbaeumer from testing the example today it looks like this is still an issue. If there is a problem with the debugger in vscode (still?) I suggest updating the readme for this sample. 

vscode reports this when trying to attach to the server:
 Error: Could not connect to debug target at http://localhost:6009: Could not find any debuggable target

**Comment by dbaeumer** [comment]
@aeschli can you please have a look. You wrote the example. I have updated the dependencies and fixed the code, however the Readme instructions are incorrect since this is a Web example and the server needs to be debugged differently (e.g. the package json has only a browser entry).

**Comment by aeschli** [comment]
I updated the readme and fixed source maps.

Debugging the server is currently broken, I opened issue https://github.com/microsoft/vscode/issues/204114

You can debug the server when running in the web browser.

**Comment by ejfasting** [comment]
very nice! looks like the underlying issue is actually being fixed as well, which is great! :)

//ej
