### ISSUE TITLE
Add a Notification sample

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-extension-samples#663]
While we have the `Hello World` sample, I think a formal notification sample showcasing more capabilities would be much more useful. We could also point to it from our [notification UX guidelines](https://code.visualstudio.com/api/ux-guidelines/notifications) for more visibility.

It could feature:
- Notification types (info, warning, error, progress)
- Styles (toast, modal) 
- Example for "Don't show again" notification (see [vscode-docs#5283](https://github.com/microsoft/vscode-docs/pull/5383)

cc @hawkticehurst @misolori

**Comment by misolori** [comment]
also cc @bpasero for other ideas
