### ISSUE TITLE
Consider removing trailing whitespace from the code files in this repository

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode-extension-samples#677]
VSCode automatically removes the whitespace which produces extended diffs even if the developer only changed a single line.

**Comment by KamasamaK** [comment]
VS Code only automatically removes trailing whitespace if you have the setting `"editor.trimAutoWhitespace": true`, which is not the default.

But I think it's a good idea to use this for languages where extra whitespace is not meaningful.

**Comment by mjbvz** [comment]
Should have been handled by ddae6c0c9ff203b4ed6f6b43bfacdd0834215f83
