### ISSUE TITLE
Clarification on Quick Fix browser redirects with Code Action commands and onExecuteCommand() 

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-extension-samples#678]
I'm working on trying to setup a Quick Fix code action that can be used to redirect the user to a specific URL similarly to what is done in this example: https://github.com/microsoft/vscode-extension-samples/tree/main/code-actions-sample

However, I am working with the LSP and so the formatting of everything is very different. I've managed to get an understanding of the overall structure though, thanks to the example here: https://github.com/microsoft/vscode-extension-samples/tree/d7c486e9c07f91407aed982e16c3839bfa0cefdc/lsp-user-input-sample

The goal of my specific implementation is to allow for the URL that is used for the redirect to be generated dynamically based on the characteristics of the current line of text observed.

The first set sample code above seems to suggest that the command has to be hard-coded ahead of execution (the URL, title, etc.). The second one has the Server create the command (title, identifier, document uri), but has the Server get the text to be inserted as part of the document edit from the Client via user input.

Is it possible for the server to control the content/creation of a command without Client input? Is it possible to generate a link within the Server, or a function called by the Server, then use that for the redirect within a single command?

The first example linked also uses the snippet
`vscode.env.openExternal(vscode.Uri.parse('https://unicode.org/emoji/charts-12.0/full-emoji-list.html'))`
to trigger the redirect, from what I can gather. Is similar functionality available for the LSP?

**Comment by dbaeumer** [comment]
The corresponding LSP request is https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showDocument

**Comment by david-pa** [comment]
Could you clarify how to implement this sort of action via a Code Action on the LSP? I have existing code actions that are sent out as quick fixes for certain lines, and I'd like to also include a quick fix for documentation via this "Show Document" request you've suggested.

Code Actions when constructed have different fields based on what data needs to be returned. For instance, there's a `edit?:` field for making changes to the document and `command?:` for executing commands. However, it's my understanding that `command?:` values are only meant to reference pre-registered/hard-coded identifiers. Is it possible to show a document within a code action "quick fix", or is it meant to be used another way? How does it go from the server over to the client? This is not very clear in the documentation.

Is there sample code that exists that illustrates the specifics of how to implement this?
