### ISSUE TITLE
lsp-embedded-request-forwarding: Which language servers are forwarded the embedded content?

### ISSUE THREAD

**Issue by russell-lew** [microsoft/vscode-extension-samples#681]
I am working on a language server extension with embedded Lua code which I want to get Intellisense support on. My extension does not have any language features for Lua. I have decided to use request forwarding to achieve Intellisense. 

I played around with the lsp-embedded-request-forwarding sample and tried using using completions for different languages by changing the following code: 

line 36: updating the slicing to remove .js extensions instead of .css
```
	workspace.registerTextDocumentContentProvider('embedded-content', {
		provideTextDocumentContent: uri => {
			const originalUri = uri.path.slice(1).slice(0, -3);
			const decodedUri = decodeURIComponent(originalUri);
			return virtualDocumentContents.get(decodedUri);
		}
	});
```

line 56: changing the authority and language extension
``` 
				const vdocUriString = `embedded-content://js/${encodeURIComponent(
					originalUri
				)}.js`;
```

Doing so allowed me to get Javascript completions within the <style> tags (just for testing's sake). However, when I try it with Python and Lua, I was unable to get any completion results when typing in their respective languages. 

The [VSCode documentation](https://code.visualstudio.com/api/language-extensions/embedded-languages#request-forwarding) explains that "request forwarding sends the request back to VS Code to query all language servers and forward their responses". 

I would like to clarify the scope of 'all language servers' - does that mean all third party ones available on the marketplace as well? 

Initially, I thought it could be limited to language servers developed by Microsoft. But since I could not get it to work on Python, it is not behaving the way I expected. 

Which language servers and languages are supported by this request forwarding feature? Is it possible to do request forwarding to marketplace language servers such as Lua and how do I do it?

**Comment by aeschli** [comment]
The request goes to all active extensions that have registered a completion provider for the embedded language. 
In your example the embedded URL ends with `js` and the TypeScript extension will compute a result as it contributes a completion provider for `js` files.

**Comment by aeschli** [comment]
I updated the documentation
