### ISSUE TITLE
[Help] Comments made from commentController are persistent?

### ISSUE THREAD

**Issue by s267348** [microsoft/vscode-extension-samples#686]
I tried the comment-sample example and customized it a bit.
The only thing that i didn't understand is regarding the persistance of the comments, do they expire if i close and re-open vscode or they are "attached" to the file?
And if not, is there a way to keep them anyway? (Checked API and nothing seemed to refer to that topic)

**Comment by alexr00** [comment]
@s267348 you would need your extension to restore comments that you want to "persist" upon extension activation by calling `createCommentThread` for each comment thread you to persist. 

https://github.com/microsoft/vscode/blob/f27f620e7797fa6f58629114ae80935c027eb39c/src/vscode-dts/vscode.d.ts#L15068-L15076
