### ISSUE TITLE
Cannot run the Vim sample

### ISSUE THREAD

**Issue by melonsodaddict** [Microsoft/vscode-extension-samples#69]
Hi, encountering an error with controller.ts when i try to run it:
![image](https://user-images.githubusercontent.com/13934119/40253831-0d83e68a-5a96-11e8-96ba-2f80652ae634.png)

Error:
Type 'PromiseLike<Promise<ITypeResult>>' is not assignable to type 'Thenable<ITypeResult>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = Promise<ITypeResult>, TResult2 = never>(onfulfilled?: (value: Promise<ITypeResult>) =...' is not assignable to type '<TResult1 = ITypeResult, TResult2 = never>(onfulfilled?: (value: ITypeResult) => TResult1 | Promi...'.
      Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'Promise<ITypeResult>' is not assignable to type 'ITypeResult'.
            Property 'hasConsumedInput' is missing in type 'Promise<ITypeResult>'.	

I understand this sample was for version 0.10.12 and the version i'm using is:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

So it's possible the API is no longer the same between versions? A fix or help to resolve this so that i may study and debug it further to make my own modal style keyboard would be greatly appreciated!

**Comment by sandy081** [comment]
Fixed.
