### ISSUE TITLE
【Tree-view-sample】only after I change the engines.vscode to "^1.67.0",it can work; when it is "^1.71.0",it cannot work properly.

### ISSUE THREAD

**Issue by duanlvxin** [microsoft/vscode-extension-samples#697]
![image](https://user-images.githubusercontent.com/55199253/184296392-5189116b-590c-4f88-9382-c2256c503594.png)

**Comment by alexr00** [comment]
I'm not able to reproduce this. The sample currently requires VS Code insiders (1.71) to run because it uses some proposed API.

**Comment by duanlvxin** [comment]
but it seems the latest released vscode version is 1.70.2?
