### ISSUE TITLE
WebView examples using React and/or Vue

### ISSUE THREAD

**Issue by mkloubertego** [microsoft/vscode-extension-samples#707]
I would like to contribute 1 or 2 examples on the topic of WebViews.

I have not yet found any examples here of how a WebView can work with JSX and Babel.

[We](https://github.com/egomobile) are currently working on an internal extension and are using React + Babel as CDN versions for the sake of simplicity, which makes coding much more pleasant.

We had also managed to use Vue for a VSCode WebView in the past: https://github.com/egomobile/vscode-powertools/wiki/Vue%20%2F%20Vuetify

I don't know if the example [notebook-renderer-react-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/notebook-renderer-react-sample) by @mjbvz already goes in this direction.

So I wanted to ask if there is interest in me making a pull request with 2 examples.

**Comment by mjbvz** [comment]
Examples of using specific frameworks like react is a better maintained by the community. These samples focus on use of the VS Code apis
