### ISSUE TITLE
Info/comment in _getHtmlForWebview of the WEBVIEW-VIEW-SAMPLE is wrong and misleading.

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode-extension-samples#711]
In the WEBVIEW-VIEW-SAMPLE, I found out that the lines below were copy pasted directly from the other webview sample, (WEBVIEW-SAMPLE) but the part about the image sources was removed in the meta tag.

( so the comment below from the '_getHtmlForWebview' method is wrong: the images are not allowed from the extension directory )

```
Use a content security policy to only allow loading images from https or from our extension directory,
and only allow scripts that have a specific nonce.
```

(threw me off for a while as I was believing this comment, hehe, and did not see the images that I added in my extension appear. Only when I compared with the other extension sample "WEBVIEW-SAMPLE"  )

Hope you fix this little line in the comment of the '_getHtmlForWebview' so that it's clear taht this only allows style and scripts, but no images.

Thanks for your great product and examples ! :D

**Comment by mjbvz** [comment]
Can you please submit a PR for this. Thanks!

**Comment by boltex** [comment]
@mjbvz no problem

**Comment by boltex** [comment]
@mjbvz  PR #712 addresses this issue. Thanks again! :smile:
