### ISSUE TITLE
esModuleInterop is false in tsconfig.json, but the recommendation is for it to be on

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode-extension-samples#719]
https://www.typescriptlang.org/tsconfig/#esModuleInterop says it's recommended. Also, when I edit my project in VSCode it keeps suggesting `import path from "path"` and I need to change it to `import * as path from "path"`. The former suggestion lints fine, but errors at runtime. Is this related?

**Comment by mjbvz** [comment]
You can enable this setting you need to for your extension. Since all the samples seem to be working fine today, I don't think we need to make a big pass to update them all
