### ISSUE TITLE
When will be the inline completion API available?

### ISSUE THREAD

**Issue by yachty66** [microsoft/vscode-extension-samples#722]
When do you plan to make [this API](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions) available for VSC standard editor? Are there any workarounds currently to do this greyed out inline suggestions? Copilot is also using it.

**Comment by KamasamaK** [comment]
The general [Inline Completions API was finalized](https://code.visualstudio.com/updates/v1_68#_inline-completions-finalization) for VS Code v1.68.

You can follow the pending enhancements in the [microsoft/vscode repo](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+inline+label%3Ainline-completions), which is where such things take place. This is not the repo to inquire about API progress.

However, it is fair to request that the sample be updated to no longer indicate that it is using proposed APIs or to submit a PR yourself correcting it.

**Comment by softmarshmallow** [comment]
Can you update the README on https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions since it can confuse the users. ?
