### ISSUE TITLE
[WebView-Codicons-Sample]Can't load codicon.css correctly

### ISSUE THREAD

**Issue by mirreri** [microsoft/vscode-extension-samples#727]
Hi,

I'm trying to include @vscode/codicons module, so I add "@vscode/codicons" in package.json,
then do "npm install" and make sure this module show up in my "node_modules" directory.
However, when I check my webview, the codicons.css I include is empty (no any content in that file).

May I ask what should I do to make it works?

Thanks a lot
![image](https://user-images.githubusercontent.com/22906283/196750190-81b660f1-ccd9-4719-b71b-40bd1c865fc0.png)

[package.json.txt](https://github.com/microsoft/vscode-extension-samples/files/9822280/package.json.txt)
[index.html.txt](https://github.com/microsoft/vscode-extension-samples/files/9822283/index.html.txt)
[main-panel.ts.txt](https://github.com/microsoft/vscode-extension-samples/files/9822312/main-panel.ts.txt)

**Comment by dacort** [comment]
I believe you need to add the proper Content-Security-Policy to your `<head>`.

This is demonstrated in the sample [here](https://github.com/microsoft/vscode-extension-samples/blob/fdd3bb95ce8e38ffe58fc9158797239fdf5017f1/webview-codicons-sample/src/extension.ts#L44)

```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src ${webview.cspSource}; style-src ${webview.cspSource};">
```

**Comment by mirreri** [comment]
Thanks a lot, according to your response, I add
<meta content="default-src 'none'; font-src ${webview.cspSource}; style-src ${webview.cspSource};">
in my header

cause it's an old program so, it will take too much effort if I apply "Content-Security-Policy" lol
and cause I use localResourceRoots for WebviewOptions so I also need to add node_modules in it.
Just write this for record.

Thanks for your assistance!!!!

> I believe you need to add the proper Content-Security-Policy to your `<head>`.
> 
> This is demonstrated in the sample [here](https://github.com/microsoft/vscode-extension-samples/blob/fdd3bb95ce8e38ffe58fc9158797239fdf5017f1/webview-codicons-sample/src/extension.ts#L44)
> 
> ```
> <meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src ${webview.cspSource}; style-src ${webview.cspSource};">
> ```
