### ISSUE TITLE
`helloworld-web-sample` does not function in vscode.dev

### ISSUE THREAD

**Issue by AdamRaichu** [microsoft/vscode-extension-samples#731]
I ran the command `Developer: Install web extension...` in vscode.dev and pasted in [https://raw.githubusercontent.com/microsoft/vscode-extension-samples/main/helloworld-web-sample/](https://raw.githubusercontent.com/microsoft/vscode-extension-samples/main/helloworld-web-sample/), and the extension installed. However, running `Hello World` from Crtl+Shift+P brings up an error.

```
Command 'Hello World' resulted in an error (command 'helloworld-web-sample.helloWorld' not found)
```

**Comment by sandy081** [comment]
You cannot use this command to install the extension this way. You have to host the extension in a server and provide the location of the extension and the server shall support rest APIs to fetch extension resources for eg: `<location>/<extension_resource>`
