### ISSUE TITLE
Multi-server language extension won't build, due to tasks.json issue

### ISSUE THREAD

**Issue by okeefm** [Microsoft/vscode-extension-samples#75]
When trying to build the `lsp-multi-server-example` in VS Code, the following messages appear:

    Couldn't resolve dependent task 'watch:client' in workspace folder 'lsp-multi-server-sample'
    Couldn't resolve dependent task 'watch:server' in workspace folder 'lsp-multi-server-sample'

This appears to be because `watch:client` and `watch:server` in `vscode-extension-samples/lsp-multi-server-sample/.vscode/tasks.json` were changed to `npm` tasks instead of `shell` tasks, which changes the signature to `npm: watch:client` and `npm: watch:server`.

**Comment by dbaeumer** [comment]
See my comment in the PR.

**Comment by bpasero** [comment]
@dbaeumer this sounds like the issue I was seeing when trying to run from a multi-root folder, can you merge the PR?

**Comment by dbaeumer** [comment]
@bpasero I think you were affected by a task bug I introduced this morning. But did the change in the tasks.json to make this work.
