### ISSUE TITLE
How is `CustomReadonlyEditorProvider` used in a web extension?

### ISSUE THREAD

**Issue by AdamRaichu** [microsoft/vscode-extension-samples#771]
The `custom-editor-sample` extension is written in TypeScript, and I don't have the knowledge of how to convert it to JavaScript for a web extension. For example, catScratchEditor.ts uses `implements`, but JS doesn't have that. How would one implement a CustomReadonlyEditorProvider in a JavaScript web extension?

**Comment by mjbvz** [comment]
See https://code.visualstudio.com/api/extension-guides/web-extensions

It's very similar to how desktop extensions are written, just with a different entry-point (and you can't use native node modules)
