### ISSUE TITLE
2 Source Files,  One Theme

### ISSUE THREAD

**Issue by Triangle4** [microsoft/vscode-extension-samples#777]
It would be ideal to store the various languages used in a theme in their own file.
This makes editing much easier.
Can we make this happen? Is there a way to supply multiple support files for a single theme? For Example, instead of:
```
{
    "label": "Some Dark Theme",
    "uiTheme": "vs-dark",
    "path": "./themes/name.json"
},

```
We could have:
```
{
    "label": "Some Dark Theme",
    "uiTheme": "vs-dark",
    "path": 
    [
        "./themes/dark.cpp.json",
        "./themes/dark.cs.json",
        "./themes/dark.js.json",
    ]
},
```

This would make the programming of themes much much more efficient.
I am presently working on developing full and complete language support for HLSL. 
This would really help in the process.

**Comment by mjbvz** [comment]
Please file a feature request against VS Code (although this is unlikely to be added IMO)

**Comment by Triangle4** [comment]
It would be quite useful to split up the code into files. I agree though,
not likely to be added either. Never hurts to ask!
