### ISSUE TITLE
Couldn't resolve dependent task 'watch:client'

### ISSUE THREAD

**Issue by zunlihu** [Microsoft/vscode-extension-samples#78]
When I try to build the task, it outputs something as follows.

**Couldn't resolve dependent task 'watch:client' in workspace folder 'lsp-sample'
Couldn't resolve dependent task 'watch:server' in workspace folder 'lsp-sample'**

OS: win10
VSCode version :1.24.0 

'npm install' and 'npm run compile' successfully.

**Comment by dbaeumer** [comment]
Thanks. Fixed.
