### ISSUE TITLE
LSP Sample no longer working (may be related to PR #776)

### ISSUE THREAD

**Issue by ankrgyl** [microsoft/vscode-extension-samples#785]
I was just onboarding via https://code.visualstudio.com/api/language-extensions/language-server-extension-guide, and noticed that the tutorial wasn't working: the extension never seemed to start, and setting a breakpoint in extension.ts did not work:

<img width="624" alt="Screenshot 2022-12-12 at 10 20 09 PM" src="https://user-images.githubusercontent.com/565363/207241476-73ab520e-2e4a-488c-93e2-6cb44f4481a9.png">

However, if I reintroduce the `activationEvents` removed in PR #776, everything worked again: the Extension Development Host properly loaded the extension and setting breakpoints worked.

```
$ git diff
diff --git a/lsp-sample/package.json b/lsp-sample/package.json
index 8558cfa..ac07de0 100644
--- a/lsp-sample/package.json
+++ b/lsp-sample/package.json
@@ -16,7 +16,9 @@
        "engines": {
                "vscode": "^1.74.0"
        },
-       "activationEvents": [],
+       "activationEvents": [
+               "onLanguage:plaintext"
+       ],
        "main": "./client/out/extension",
        "contributes": {
                "configuration": {
```

Also not sure this matters, but I noticed that the `vscode` version in https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/package.json is still 1.63.

**Comment by vancluever** [comment]
@ankrgyl looks like this was due to some missing necessary configuration in the manifest when this extension was updated to support 1.74 (where activation events are inferred from the extension's contributed languages. The changes I've put in with #787 seem to fix it. Might want to check that out!

**Comment by DiegoBM** [comment]
Well in my case it's actually not working and I reckon it's because I have enabled the new Settings Profiles, so it might not be pulling the extension folder the right way anymore? Know anything about this?

**Comment by kernelguardian** [comment]
I also had the same issue, 
adding this settings in the root package.json and restarting everything fixed it for me
[Complete package.json](https://gist.github.com/kernelguardian/5afc29e71f118d79e58a0689e4854161)

`
"languages": [
			{
				"id": "plaintext",
				"extensions": [
					".txt"
				],
				"aliases": [
					"Plain Text"
				]
			}
		]`

**Comment by ashu17706** [comment]
Thank you so much @ankrgyl . I have spent a lot of time to understand why it was not working? 😢 
Everything worked the moment I added the the activation event back. ❤️

**Comment by dbaeumer** [comment]
I updated all dependencies here: https://github.com/microsoft/vscode-extension-samples/pull/826 and tested the extension. I can start and debug the extension out of VS Code when opening the `lsp-sample` folder.

Will close the issue. Please ping if it still doesn't work after the PR is merged.
