### ISSUE TITLE
Hello-world-web-sample broken

### ISSUE THREAD

**Issue by EstebanDalelR** [microsoft/vscode-extension-samples#791]
Hello,

I tried running both on Mac and Windows (powershell and WSL) the sample to upgrade my sample but could not get it to run.

I tried using `yo code` as a generator too and failed to run.

I have tried both on insiders and vscode. 

The error lies in that it expects an `out` folder that does not exist:

![imagen](https://user-images.githubusercontent.com/11527621/209368895-1ac901d1-6f2f-4a5a-90f5-5fb17132b249.png)

`Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/c%3A/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/out-vscode/vs/code/electron-sandbox/workbench/workbench.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-sandbox\workbench\out-vscode\vs\code\electron-sandbox\workbench\nls.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/debug.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\debug.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/grammar.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\grammar.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/grammarReader.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\grammarReader.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/json.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\json.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/main.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\main.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/matcher.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\matcher.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/plist.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\plist.js.map'  

Could not read source map for file:///C:/Users/USER/Documents/GitHub/vscode-extension-samples/helloworld-web-sample/out/registry.js: ENOENT: no such file or directory, open 'c:\Users\USER\Documents\GitHub\vscode-extension-samples\helloworld-web-sample\out\registry.js.map'  `

**Comment by Ajitweb** [comment]
In my case, on debugging, the new vscode window opens up and the 'helloworld' command can be  run.
But there are more than 450 lines of "Could not read source map..." being spitted to the Debug Console Panel window
If I add the resolveSourceMapLocations property in launch.json
`
			"resolveSourceMapLocations": [
				"${workspaceFolder}/**",
				"!**/node_modules/**"
			]`

then, the "Could not read source map..." reduces to around 50 lines

I am using the latest version of vscode 1.80.0. 
I did not make any other changes to the helloworld-web-sample directory (other than the resolveSourceMapLocations)

@connor4312 , 
[1.txt](https://github.com/microsoft/vscode-extension-samples/files/11998405/1.txt)
[2.txt](https://github.com/microsoft/vscode-extension-samples/files/11998409/2.txt)

**Comment by connor4312** [comment]
Known issue, not something to worry about.

Closing this one since we haven't heard back from the original reporter.
