### ISSUE TITLE
How to hook up Semantic Tokens from a server ?

### ISSUE THREAD

**Issue by AntoineBalaine** [microsoft/vscode-extension-samples#796]
Hello,

I’m trying to hook-up the [semantic tokens sample](https://github.com/microsoft/vscode-extension-samples/tree/main/semantic-tokens-sample) into the [lsp-sample’s server](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample).

Following the [semantic highlight guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) doesn’t quite give me all the info I need. The guide points to `vscode.languages.registerDocumentSemanticTokensProvider(selector, provider, legend);`, but:
- After passing `{semanticTokensProvider: legend}` in the server capabilities; in the server’s `initialize`, how is the `DocumentSemanticTokensProvider` supposed to be hooked-up to the connection?
- is there also some setup to do on the client side ?
- do the `SemanticTokens` get automatically handled at every update or must they be continuously updated in the `documentsManager.onDidChangeContent` ? 

Referencing [`lsp-sample/server/src/server.ts`](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts):
```typescript
import {
	DocumentSemanticTokensProvider,
	legend,
} from './semanticTokensProvider/tokensProvider';

const connection = createConnection(ProposedFeatures.all);
const SemanticProvider = new DocumentSemanticTokensProvider(); // where does this guy go?

const documentsManager: TextDocuments<TextDocument> = new TextDocuments(TextDocument);
//[...]
connection.onInitialize((params: InitializeParams) => {
	const capabilities = params.capabilities;

	const serverCapabilities: InitializeResult = {
		capabilities: {
                       //[...]
			semanticTokensProvider: {
				legend,
			},
		},
	};
	return serverCapabilities;
});
```

**Comment by Upndup** [comment]
Thank u so much.
My honest truth is, she used me to get a house. She managed to get the house with my salary to have our mortgage approved.
The first week in I noticed marks of sex all over my brand new sofas.
I enquired what those marks were. She became hostile and called the police, had me removed.  Within 4 months I was chested on, accused arrested and removed from my household and children.
Whilst she plays the victim.

She manipulates the world to her gain.
If u are capable of processing the pictures and video, I'll send u a pic of myself and prove to u she had and affair and now presented herself as an oppressed wife



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Antoine Balaine ***@***.***>
Sent: Thursday, December 29, 2022 9:29:15 PM
To: microsoft/vscode-extension-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/vscode-extension-samples] How to hook up Semantic Tokens from a server ? (Issue #796)


Hello,

I’m trying to hook-up the semantic tokens sample<https://github.com/microsoft/vscode-extension-samples/tree/main/semantic-tokens-sample> into the lsp-sample’s server<https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample>.

Following the semantic highlight guide<https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide> doesn’t quite give me all the info I need. The guide points to vscode.languages.registerDocumentSemanticTokensProvider(selector, provider, legend);, but:

  *   After passing {semanticTokensProvider: legend} in the server capabilities; in the server’s initialize, how is the DocumentSemanticTokensProvider supposed to be hooked-up to the connection?
  *   is there also some setup to do on the client side ?
  *   do the SemanticTokens get automatically handled at every update or must they be continuously updated in the documentsManager.onDidChangeContent ?

Referencing lsp-sample/server/src/server.ts<https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts>:

import {

        DocumentSemanticTokensProvider,

        legend,

} from './semanticTokensProvider/tokensProvider';



const connection = createConnection(ProposedFeatures.all);

const SemanticProvider = new DocumentSemanticTokensProvider(); // where does this guy go?



const documentsManager: TextDocuments<TextDocument> = new TextDocuments(TextDocument);

//[...]

connection.onInitialize((params: InitializeParams) => {

        const capabilities = params.capabilities;



        const serverCapabilities: InitializeResult = {

                capabilities: {

                       //[...]

                        semanticTokensProvider: {

                                legend,

                        },

                },

        };

        return serverCapabilities;

});

**Comment by Upndup** [comment]
Thank you so much for your help


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlecGhost** [comment]
Hello there,
unfortunatly I cannot really answer your first question.

However, I can confirm, that you do not need any additional setup on the client side. If the client starts the server and the server announces, that it has the capability to provide semantic tokens, you are fine.

Regarding your final question: VSCode as a client automatically requests semantic tokens, when it needs them. So you do not need to send them on your own. In fact, there is not even a method defined in the LSP, that lets you do this. The only thing, that you can do (if I read the protocol correctly) is to send a [`workspace/semanticTokens/refresh`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#semanticTokens_refreshRequest) request, which recommends to the client to ask for semantic tokens again.

I hope this information can help you.

**Comment by AntoineBalaine** [comment]
Got it, thank you very much!

**Comment by caryyu** [comment]
Any solutions for this, I got this from the `Extension Development Host` output:

```txt
[Error - 8:12:35 PM] Request textDocument/semanticTokens/full failed.
  Message: Unhandled method textDocument/semanticTokens/full
  Code: -32601 
```

Here's my config very similar to yours:

```txt
  const result: InitializeResult = {
    capabilities: {
      semanticTokensProvider: {
        legend: {
          tokenTypes: [
            'comment', 'string', 'keyword', 'number', 'regexp', 'operator', 'namespace',
            'type', 'struct', 'class', 'interface', 'enum', 'typeParameter', 'function',
            'method', 'decorator', 'macro', 'variable', 'parameter', 'property', 'label'
          ],
          tokenModifiers: [
            'declaration', 'documentation', 'readonly', 'static', 'abstract', 'deprecated',
            'modification', 'async'
          ],
        },
        full: true,
      },
....
```

**Comment by mtiller-jh** [comment]
I found this useful:

https://github.com/microsoft/vscode-discussions/discussions/819

**Comment by wakaztahir** [comment]
@AlecGhost Hi, you said client doesn't need additional setup, however VSCode is just not sending the request to server, so client requires additional setup through

```typescript
vscode.languages.registerDocumentSemanticTokensProvider(selector, provider, legend);
```

As stated in :
https://github.com/microsoft/vscode/issues/204906#issuecomment-1937097350

**Comment by AlecGhost** [comment]
@wakaztahir I have no knowledge of the VSCode internals, I can only report the behaviour I experience. My extension works without additional client-side setup for the semantic tokens, see https://github.com/AlecGhost/LSP4SPL/blob/master/editors/code/src/extension.ts.

Besides, `registerDocumentSemanticTokensProvider` sounds very much like a server method, not like a client method.
Maybe your server does not announce a `semanticTokenProvider` in its capabilities during the initialization phase?

**Comment by wakaztahir** [comment]
Hi @AlecGhost , I have fixed everything, I've mentioned everything here

[semantic_tokens_opt](https://github.com/microsoft/vscode/issues/204906)
