### ISSUE TITLE
LSP-SAMPLE broken

### ISSUE THREAD

**Issue by TobiasLadner** [microsoft/vscode-extension-samples#822]
The LSP-SAMPLE appears to be broken. When downloading sample and running ```npm run compile``` you get various errors. Errors can be fixed by adding 'DOM' to the 'lib' in the client and server 'tsconfig.json'. Additionally you have to run ```npm install @types/node@14.0.4 --saveDev``` for everything to work.

**Comment by dbaeumer** [comment]
I updated the dependencies and tested the extension and it works for me now. See https://github.com/microsoft/vscode-extension-samples/pull/826
