### ISSUE TITLE
Couldn't resolve dependent task 'npm: watch:[client and server]'

### ISSUE THREAD

**Issue by glcraft** [Microsoft/vscode-extension-samples#83]
When i tried to launch The LSP Sample by pressing `Ctrl-Shift-B` as said in the tutorial nearby [Diagnostics Tips and Tricks](https://code.visualstudio.com/docs/extensions/example-language-server#_diagnostics-tips-and-tricks), I have the following errors :
```
Couldn't resolve dependent task 'npm: watch:client' in workspace folder 'lsp-sample'
Couldn't resolve dependent task 'npm: watch:server' in workspace folder 'lsp-sample'
```
I tried to remove 'npm: ' without success.

I didn't modified tasks.json and both tasks appear in it.

**Comment by dbaeumer** [comment]
This works for me. @glcraft are you using a French locale?

**Comment by dbaeumer** [comment]
Made the tasks locale independent.
