### ISSUE TITLE
lsp-samples unable to debug

### ISSUE THREAD

**Issue by aq949342769** [microsoft/vscode-extension-samples#830]
I set a breakpoint in ` server.ts`  file ,then launch the client. However, the breakpoint couldn't bind. 
When I changed the launch.json where `workspaceRoot` to `workspaceFolder` , the breakpoint worked well.It seems that the `workspaceRoot` is deprecated？ And if it's necessary to update the `launch.json` file？BTW, the `outFiles` option is narrow

**Comment by dbaeumer** [comment]
Debugging failed because of `"autoAttachChildProcesses": true,`

I removed the setting

**Comment by yg-i** [comment]
The LSP-SAMPLE example is still broken for me.

If I don't change `workspaceRoot` to `workspaceFolder`, the folder in which debugging starts is an entirely different folder on my drive from the LSP-SAMPLE folder.

If I do change `workspaceRoot` to `workspaceFolder`, debugging starts in the right folder, but the .txt file does not get the squiggly lines under the uppercase 'ANY's.

**Comment by dbaeumer** [comment]
You can start the example on any file you want and open a text file.
