### ISSUE TITLE
server debug broken on the lsp-sample

### ISSUE THREAD

**Issue by mateusabelli** [microsoft/vscode-extension-samples#836]
## The problem 

> [Referred project](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample)

According to the [docs](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#debugging-both-client-and-server) It should've been possible to debug both **client** and **server**, but there is no **Attach to Server** configuration in the `.vscode/launch.json` anymore and I could not find any other methods or documentation to make my server breakpoints hit when trying to debug.

### Steps to reproduce
- clone the repo
- `cd` into the **lsp-sample**
- run `npm install` and `npm run compile`
- add breakpoints to `client/src/extension.ts`
- add breakpoints to `server/src/server.ts`
- open your debug panel choose **Launch Client**

> server breakpoints are gray, showing "unbound breakpoint"

## Initial thoughts

After running into this issue the first thing I noticed was the missing **Attach to Server** configuration, so I went to this repository and looked through the previous commits and found the following.

- The configuration is present and everything worked as expected at this commit https://github.com/microsoft/vscode-extension-samples/commit/e1ecdaec8974b938e7a92589faa233e1691d251f
- After this patch, debugging the server did not worked anymore https://github.com/microsoft/vscode-extension-samples/commit/dbee9a0daf8f25c4eff7d4cdc65b70a3c01bd25c

## Possible solution

If nothing else breaks, we could maybe revert some of the configurations to that previous working state?

**lsp-sample/.vscode/launch.json**
https://github.com/microsoft/vscode-extension-samples/commit/dbee9a0daf8f25c4eff7d4cdc65b70a3c01bd25c#diff-767cc09063399b4f3bc13098f37ad284f1e1a4333cf28740ca5da00d5d451f23

**lsp-sample/client/src/extension.ts**
https://github.com/microsoft/vscode-extension-samples/commit/dbee9a0daf8f25c4eff7d4cdc65b70a3c01bd25c#diff-a6a41ed849771f4fda193238ec10d62e59f5bf1a09029b710852d17389105d3b

**Comment by dbaeumer** [comment]
@connor4312 could be please comment. You remove the attach configs in favor of `autoAttachChildProcesses` but that doesn't work under WSL so I needed to remove it (see https://github.com/microsoft/vscode-js-debug/issues/1503)

We either need to bring the attach configs back or make the `autoAttachChildProcesses` work?

**Comment by TobiasLadner** [comment]
@connor4312 so I have the same problem and do not manage to debug the server. Do you think it would be possible for you to explain to me how I can make it work? I added the option `autoAttachChildProcess` to the `launch.json` but it is still not working.

**Comment by gentledepp** [comment]
@TobiasLadner 

I have no idea how the `autoAttachChildProcess` works, so I will explain how I fixed it for my case:

1. Add the missing launch configuration
```json

		{
			"name": "Attach to Server",
			"type": "node",
			"request": "attach",
			"address": "localhost",
			"port": 6009,
			"sourceMaps": true,
			"outFiles": ["${workspaceRoot}/server/out/**/*.js"],
			"preLaunchTask": {
				"type": "npm",
				"script": "watch"
			}
		},
```

2. Run "Launch Client"
3. once a new VS Code instance opens, run "Attach to server"

Your break points in both client and server should now be hit:

![vs_lsp-sample_debug](https://github.com/microsoft/vscode-extension-samples/assets/1175751/e8339b9b-3b55-4cba-bf00-93172cd2f1ef)

**Comment by VisualDev-FR** [comment]
Impossible for me to hit a breakpoint on the server side, or even to display a console.log...

**Comment by hlin-neo4j** [comment]
> Impossible for me to hit a breakpoint on the server side, or even to display a console.log...

Found the issue. Along with @gentledepp 's solution, you also need to change extension.ts to look like
```
export function activate(context: ExtensionContext) {
    const serverModule = context.asAbsolutePath(
        path.join('server', 'out', 'server.js')
    );
    // The debug options for the server
    // --inspect=6009: runs the server in Node's Inspector mode so VS Code can attach to the server for debugging
    let debugOptions = { execArgv: ['--nolazy', '--inspect=6009'] };

    const serverOptions: ServerOptions = {
        run: { module: serverModule, transport: TransportKind.ipc },
        debug: {
            module: serverModule,
            transport: TransportKind.ipc,
            options: debugOptions
        }
    };
    
    ....
}
```

The "Attach to Server" piece in launch.json needs to be paired with these debugOptions, both of which were removed from the git source, and the latter being present in the tutorial. I added this part in and the breakpointing worked for me

**Comment by dbaeumer** [comment]
I updated the dependencies and fixed the server debug problem.

**Comment by mtiller-jh** [comment]
Thanks @dbaeumer 

However, I think most (if not all) of the other `lsp-*` projects have this same issue.  As far as I can tell, this fix is only applied to one of them.  I could be wrong, but it looks that way to a novice like me at least.

**Comment by dbaeumer** [comment]
I will update the once that I own as well.
