### ISSUE TITLE
TreeDataProvider onDidChangeTreeData not trigering view update

### ISSUE THREAD

**Issue by JohnstonCode** [Microsoft/vscode-extension-samples#84]
Hi,

I am implementing a tree view in my extension using the tree-view-sample as reference.

I have implemented the [TreeDataProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TreeDataProvider) and the optional onDidChangeTreeData event. When i fire the event with no parameters as the documentation advises, no update is done. Am i missing something?

[My TreeDataProvider](https://github.com/JohnstonCode/svn-scm/blob/tree-view-incomming-changes/src/treeView/dataProviders/svnProvider.ts)

**Comment by sandy081** [comment]
@JohnstonCode Can you please debug in your extension that after the event is fired, are you getting a request for getting children `getChildren`?

**Comment by JohnstonCode** [comment]
@sandy081 Thanks for the reply, yeah the issue was with my implementation of get children. 

Don't know why i didn't use the debugger. My bad

Cheers.

**Comment by ngarg-panw** [comment]
I have another question related to the content of the children. Is it possible to have a row value as a hyper-link?
For example, i have name and url, so clicking on name opens the url in another browser tab?
