### ISSUE TITLE
How to access the DOM of a custom webview in VS Code extension tests?

### ISSUE THREAD

**Issue by fanurs** [microsoft/vscode-extension-samples#846]
Hi there,

I'm working on a VS Code extension that includes a custom webview, and I'm trying to write tests to verify the behavior of the webview. **Specifically, I'm interested in counting the number of appearances of `<div>` elements with `class="my-element"` in the webview.**

I've been looking at the `helloworld-test-sample` example in the VS Code Extension Samples repository, and I've noticed that the test code only includes simple arithmetic assertions which are not really helpful to me:
https://github.com/microsoft/vscode-extension-samples/blob/98346fc4fa81067e253df9b32922cc02e8b24274/helloworld-test-sample/src/test/suite/extension.test.ts#L8-L14

Is it possible to access the DOM of a custom webview in extension tests, and write more complex tests that check for specific elements or attributes in the webview? For example, I would like to count the number of appearances of `<div>` elements with `class="my-element"` in the webview, while avoid importing the extension module that defines `createWebviewPanel`.

If anyone has any tips or advice on how to accomplish this, I'd greatly appreciate it!

**Comment by mjbvz** [comment]
> Is it possible to access the DOM of a custom webview in extension tests,

No, not directly

However you could post a custom message to the webview to get information about its dom. You will have to implement this inside your webview though
