### ISSUE TITLE
Question: how do I configure Azure's Application Insight key with this example

### ISSUE THREAD

**Issue by marjoripomarole** [microsoft/vscode-extension-samples#850]
https://github.com/microsoft/vscode-extension-samples/blob/f7b27a91779e770b8f8f0e6791bcefc5d9c64035/telemetry-sample/src/extension.ts#L7-L19

Since this code example is not using the extension, https://github.com/microsoft/vscode-extension-telemetry, 
where do I configure the application insight's key with the reporter fetched from vscode.env?

**Comment by marjoripomarole** [comment]
I guess, my question here is, which method is the most future-proof for logging data from VS Code extensions since the one that gets the reporter from vscode.env has the newest code examples.

**Comment by lramos15** [comment]
The `vscode-extension-telemetry` package does use the reporter API underneath. So you will be receiving the most up to date VS Code features by using that. This was just a simple example to demonstrate how this API can be used for anything and is not limited to Microsoft only data providers.
