### ISSUE TITLE
Are there any sample for language grammar injection ?

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode-extension-samples#853]
I cannot fine any sample utilizing `injectTo` grammar. If there aren't exist yet then could we also have that too?

**Comment by mjbvz** [comment]
See https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example for an example of this for markdown

**Comment by Thaina** [comment]
> See https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example for an example of this for markdown

Thank you. However could you put that into this repo too?
