### ISSUE TITLE
I can't use modules

### ISSUE THREAD

**Issue by coolCucumber-cat** [microsoft/vscode-extension-samples#859]
I have to import with require and export with module.exports. I've tried changing the file extension to .mjs, in the package.json and changing the type to module but it doesn't work. Maybe in jsconfig I can do something? I have to use modules and I also hate the look of the word require.

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode/issues/130367

**Comment by coolCucumber-cat** [comment]
> See [microsoft/vscode#130367](https://github.com/microsoft/vscode/issues/130367)

It's been almost 2 years and it still hasn't been resolved. Isn't it like one line of code where it's doing require instead of import?

**Comment by igorskyflyer** [comment]
> > See [microsoft/vscode#130367](https://github.com/microsoft/vscode/issues/130367)
> 
> It's been almost 2 years and it still hasn't been resolved. Isn't it like one line of code where it's doing require instead of import?

No, actually, it's a huge change...

**Comment by coolCucumber-cat** [comment]
> > > See [microsoft/vscode#130367](https://github.com/microsoft/vscode/issues/130367)
> > 
> > 
> > It's been almost 2 years and it still hasn't been resolved. Isn't it like one line of code where it's doing require instead of import?
> 
> No, actually, it's a huge change...

What is it then?

**Comment by coolCucumber-cat** [comment]
> > > See [microsoft/vscode#130367](https://github.com/microsoft/vscode/issues/130367)
> > 
> > 
> > It's been almost 2 years and it still hasn't been resolved. Isn't it like one line of code where it's doing require instead of import?
> 
> No, actually, it's a huge change...

Also you realise it really doesn't help until everything works. Weakest link in the chain.

**Comment by coolCucumber-cat** [comment]
What's the change though? It doesn't seem like it would be a big thing, it's just importing something. Can't you just replace require with await import? I don't understand because my problem is not being able to import so why are changes needed other than how you import?

**Comment by coolCucumber-cat** [comment]
> > > > See [microsoft/vscode#130367](https://github.com/microsoft/vscode/issues/130367)
> > > 
> > > 
> > > It's been almost 2 years and it still hasn't been resolved. Isn't it like one line of code where it's doing require instead of import?
> > 
> > 
> > No, actually, it's a huge change...
> 
> Also you realise it really doesn't help until everything works. Weakest link in the chain.

Does everything need to be updated to ES6, or what? Also ES modules have been around for 8 years. The time between CJS require and ES modules is greater than the time between ES modules and now. Why wasn't this done 8 years ago?
