### ISSUE TITLE
How to ensure webview is mounted ?

### ISSUE THREAD

**Issue by jaycethanks** [microsoft/vscode-extension-samples#861]
As the title mentiond, I need my Webview after loaded/mounted, to get a postmessage from `Extension.ts` through `message` event . 
But I did not find related hook/lifecycle-like function, How can I do this?
Currently , I use a setTimeout to achieve it, but I think that's not good.

Thanks!

**Comment by 1983Thai** [comment]
you need to store the required addresses for easy validation

**Comment by mjbvz** [comment]
Your webview code (the JS running in the webview) can post a `ready` message back to your extension once it is loaded. When your extension receives this message, it knows it can start sending messages to the webview
