### ISSUE TITLE
LSP Embedded request forwarding not doing anything

### ISSUE THREAD

**Issue by AllanJard** [microsoft/vscode-extension-samples#863]
I'm confused by the LSP Embedded request forwarding example. [It suggests](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-embedded-request-forwarding) that it is registering a new language called `html1`, but if I follow the instructions in the readme and launch the client, there is no language called `html1` in the new VS Code instance that opens.

If I create a file called `test.html1` it is just "Plain text" with no highlighting and no auto-complete.

I'm not sure what I'm missing. Is anyone able to clarify how to get the example to run?

**Comment by AllanJard** [comment]
It is the same as this: https://github.com/microsoft/vscode-extension-samples/issues/807 .

**Comment by BB-301** [comment]
I just faced a [similar issue](https://github.com/microsoft/vscode-extension-samples/issues/952). I solved the problem by adding `onLanguage:html1` in the `activationEvents` array in the `package.json` file.

@AllanJard , the link you shared was helpful. Thank you!
