### ISSUE TITLE
window.tabGroups.activeTabGroup.tabs cannot capture tabs with duplicated names

### ISSUE THREAD

**Issue by TautologicalContradiction** [microsoft/vscode-extension-samples#866]
If you have at the same workspace folder, a file at the path 'lib/foo.txt' and another file at the path 'src/foo.txt', only one of those is exposed at the tabs array if both are at the active group

**Comment by TautologicalContradiction** [comment]
For further info, apparently the tabs array is storing both, however, whenever i access those Tab instances at the array, only seems to contain a label or an input.uri

**Comment by mjbvz** [comment]
Please file this issue against the main vscode repo: https://github.com/microsoft/vscode
