### ISSUE TITLE
Extract the `MultiStepInput` into a standalone package

### ISSUE THREAD

**Issue by axelrindle** [microsoft/vscode-extension-samples#868]
The [MultiStepInput](https://github.com/microsoft/vscode-extension-samples/blob/ca68ab8a9cc23a6bfbbe4314f62c8e272b737251/quickinput-sample/src/multiStepInput.ts#L169) from the [quickinput-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample) is an awesome extension of the VSCode API. I was wondering why this does not exist as a standalone package and whether someone has already created a standalone package for this.

**Comment by 1983Thai** [comment]
I'm looking into what you're talking about

**Comment by TylerLeonhardt** [comment]
Not planning on releasing that as a standalone package but you are welcome to use the code in the sample anytime

**Comment by 1983Thai** [comment]
Hope to add comments to promote better
