### ISSUE TITLE
Add submenu demo

### ISSUE THREAD

**Issue by Simon-He95** [microsoft/vscode-extension-samples#873]
<img width="565" alt="image" src="https://github.com/microsoft/vscode-extension-samples/assets/57086651/a9272c3a-7c8d-4b06-a522-f5e13b24ee59">

Right-click to open how to configure the second-level menu, can you add a demo?
For example, the first level is called group, and the second level is expanded after hover, group-item-1, group-item-2

**Comment by andreamah** [comment]
You can see https://code.visualstudio.com/api/references/contribution-points#contributes.submenus for help on that.

**Comment by Simon-He95** [comment]
Hi, @andreamah thanks for your reply, I saw these references, but I still don't know how to set the parent menu and submenu, the image in the content obscures the configured code, I would rather have a simple demo that can run like this.

**Comment by Simon-He95** [comment]
Can we move forward with this question? :)

**Comment by Simon-He95** [comment]
@aeschli could you please offer a simple demo or update https://code.visualstudio.com/api/references/contribution-points#contributes.submenus to use easier

**Comment by Ayyoub-ESSADEQ** [comment]
@Simon-He95 you package contribution points should look something like this :
```
     "contributes": {
	...,
    "commands": [
      {
        "command": "demo.testCommand1",
        "title": "option 1"
      },
      {
        "command": "demo.testCommand2",
        "title": "option 2"
      },
      {
        "command": "demo.testCommand3",
        "title": "option 3"
      }
    ],
    "submenus":[
      {
        "id" : "submenuId",
        "label" : "Test Submenus"
      }
    ],
    "menus": {
      "editor/context": [
        {
          "submenu": "submenuId"
        }
      ],

      "submenuId":[
        {
          "command": "demo.testCommand1"
        },
        {
          "command": "demo.testCommand2"
        },        
        {
          "command": "demo.testCommand3"
        }
      ]
    }
  },
  ...
 }
```
Then you will see something like this : 

![image](https://github.com/microsoft/vscode-extension-samples/assets/114437119/a25bb88b-989d-4776-bd58-3d099adaefbd)

**Comment by Simon-He95** [comment]
> @Simon-He95 you package contribution points should look something like this :
> 
> ```
>      "contributes": {
> 	...,
>     "commands": [
>       {
>         "command": "demo.testCommand1",
>         "title": "option 1"
>       },
>       {
>         "command": "demo.testCommand2",
>         "title": "option 2"
>       },
>       {
>         "command": "demo.testCommand3",
>         "title": "option 3"
>       }
>     ],
>     "submenus":[
>       {
>         "id" : "submenuId",
>         "label" : "Test Submenus"
>       }
>     ],
>     "menus": {
>       "editor/context": [
>         {
>           "submenu": "submenuId"
>         }
>       ],
> 
>       "submenuId":[
>         {
>           "command": "demo.testCommand1"
>         },
>         {
>           "command": "demo.testCommand2"
>         },        
>         {
>           "command": "demo.testCommand3"
>         }
>       ]
>     }
>   },
>   ...
>  }
> ```
> 
> Then you will see something like this :
> 
> ![image](https://user-images.githubusercontent.com/114437119/256423045-a25bb88b-989d-4776-bd58-3d099adaefbd.png)

@Ayyoub-ESSADEQ thanks for you reply, I will try it later

**Comment by Simon-He95** [comment]
This is exactly what I was looking for, thanks
