### ISSUE TITLE
How do I listen to the click event on token in the editor?

### ISSUE THREAD

**Issue by baspinarenes** [microsoft/vscode-extension-samples#883]
Hi. I have a custom JSON file in my project and suppose it is like below:

```json
{
  "files": ["file1", "file2", ...]
}
```

I want to open the file when i use CMD + Click on the file names in this file. Just like when I click on the path in the import statement, it redirects to the module. But how do I listen to the click event and add underline style? Is it possible?

**Comment by AR3as** [comment]
صعب نكن اكثر   ramyloev@gmail.com
