### ISSUE TITLE
Initialize response from LSP Server doesn't reach the (vscode) lsp client (TransportKind is stdio)

### ISSUE THREAD

**Issue by tlaemmlein** [microsoft/vscode-extension-samples#906]
Hi,
I have implemented an LSP server  c++ under windows (Visual Studio 2022).
For this I used the https://github.com/kuafuwang/LspCpp repro.
I added this simple C++ server implementation
[LspServer.zip](https://github.com/microsoft/vscode-extension-samples/files/12498686/LspServer.zip)
in the https://github.com/kuafuwang/LspCpp/tree/master/examples folder.
This server works with standard input/output (stdio) communication via boost.
Hint: The server logs into DebugOutput. You can fetch this log entries with https://learn.microsoft.com/de-de/sysinternals/downloads/debugview

On the client side I sligthly changed https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/src/extension.ts
to

```typescript
const serverOptions: ServerOptions = {
command:
'C:/Users/laemmleint/lspcpp/_build/Release/LspServer',
};
```

The aim is that the initialize request/response is working.

Therefore the client sends the init request -> the server gets this request and sends a response back, but the client never get this response.

I added a breakpoint in the client.js file
![image](https://github.com/microsoft/vscode-extension-samples/assets/3143027/5e0ba800-b6dd-430a-8c88-b9cb3370e1ff)
But the response remains in a endless loop.

The server write the log entries into DebugOutput, and it seems there are no problems with this response:
![image](https://github.com/microsoft/vscode-extension-samples/assets/3143027/1f3f976f-939b-4fdb-935d-7827739ee53d)

Furthermore I tested the initialize with 
https://github.com/kuafuwang/LspCpp/blob/master/examples/StdIOClientExample.cpp
Here are no problems at all. The C++ client gets the initialize response.

Who can help me in this case?

Regards,

Thomas

**Comment by tlaemmlein** [comment]
After Investigation some time, I know the whole communication for LSP works with node.js child process (https://nodejs.org/api/child_process.html).

So I added a simple 'child process' code here:
![image](https://github.com/microsoft/vscode-extension-samples/assets/3143027/5296777e-2d5f-4995-80bf-41f233dcfb41)

And what a surprise, the breakpoint is working. Hence the response from the server is arriving.

![image](https://github.com/microsoft/vscode-extension-samples/assets/3143027/77815277-39f3-47e8-99e1-753a6ac673d6)

Who can help me to find the code were vscode process the response?
I see the StreamMessageReader and StreamMessageWriter, but I don't know where these classes will be called/triggered.

**Comment by dbaeumer** [comment]
The onData has now a try/catch block to better discover these errors and report them via the error listener.

The reason why `\r\r\n` is incorrect is that both http and lsp define header value separators as `\r\n`

I am closing the issue. Sounds like you found the underlying problem.
