### ISSUE TITLE
extension-terminal-sample is not working.

### ISSUE THREAD

**Issue by skatkov** [microsoft/vscode-extension-samples#907]
I've built and launched extension-terminal-sample extension on my VS Code and here are the messages that I receive:

<img width="269" alt="Screenshot 2023-09-02 at 23 24 32" src="https://github.com/microsoft/vscode-extension-samples/assets/544377/69b81bee-471f-428b-941c-43f810bac953">
<img width="269" alt="Screenshot 2023-09-02 at 23 25 11" src="https://github.com/microsoft/vscode-extension-samples/assets/544377/d00d105e-3681-4459-8222-b395c1958dbd">

My specs:
Version: 1.82.0-insider (Universal)
Commit: e7756c8870ee1df7360e6624e220534174039b02
Date: 2023-08-31T05:37:09.543Z (2 days ago)
Electron: 25.7.0
ElectronBuildId: 23434598
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by Sintayew4** [comment]
e7756c8870ee1df7360e6624e220534174039b02
