### ISSUE TITLE
feat: recommend and support Bun

### ISSUE THREAD

**Issue by alestiago** [microsoft/vscode-extension-samples#909]
## Description

Bun was recently released and it claims to be a faster alternative to node and npm. It also includes a test suite that might be worth considering.

This issue aims to ask **if there are plans to migrate the samples to use Bun** or if there are plans to **recommend using Bun.** If so, the issue may be used to track the progress of the such plans.

## Further context

- [Bun](https://bun.sh/)
- [Bun 1.0 blog announcement ](https://bun.sh/blog/bun-v1.0)
- [Bun 1.0 video announcement](https://www.youtube.com/watch?v=BsnCpESUEqM)
- https://github.com/oven-sh/bun/pull/4543

**Comment by mjbvz** [comment]
You can use whatever tools you want to build your extension but we try to keep these samples simple and fairly generic
