### ISSUE TITLE
Localization doesn't work

### ISSUE THREAD

**Issue by Brighttll** [Microsoft/vscode-extension-samples#92]
I tried to localize a message which should displays in ja(Japanese), but the message shows in en(English) after updating the locale as 'ja'. I noticed that localize('key', 'stringValue') are not transformed to localize(0, null) in **extension.js** after executing command **gulp package**. But the file **extension.nls.ja.json** would be generated correctly in the out folder. 

I cannot figure out what's going on, did I missed anything?

I attached the source code, the reproduce steps are followings, you can refer the page [https://github.com/Brighttll/vscode-extension-samples/tree/master/i18n-sample] for details.
1. Export the extension package and install it
2. Update the locale as 'ja', restart vs code IDE.
3. Run the command Tester: Create Application
![image](https://user-images.githubusercontent.com/12249650/44976288-61c4a580-af97-11e8-84f4-28f5d61112b7.png)
4. Message box pop up, it's not in ja.
![image](https://user-images.githubusercontent.com/12249650/44976329-828cfb00-af97-11e8-8c21-429e2905606d.png)

Much appreciate if any one have a change to have a look at the issue.

[Extension.zip](https://github.com/Microsoft/vscode-extension-samples/files/2344798/Extension.zip)

**Comment by Brighttll** [comment]
I noticed that  localize('key', 'stringValue') are transformed to localize(0, null) in extension.js if I debug start from "${workspaceRoot}/node_modules/gulp/bin/gulp.js". 
When I execute command "gulp package", the localize('key', 'stringValue') are not transformed in extension.ts. I guess it is the root reason why localization does not work well.

extension.js generated by debug:
    const message = localize(0, null);
    vscode.window.showInformationMessage(message);
    const message1 = localize(1, null);
    vscode.window.showInformationMessage(message1);

 extension.js generated by executing command "gulp package":
    const message = localize('hello.text', 'Hello111');
    vscode.window.showInformationMessage(message);
    const message1 = localize('bye.text', 'Byebye');
    vscode.window.showInformationMessage(message1);

**Comment by dbaeumer** [comment]
@Brighttll yes, if the localize calls don't get replace localization doesn't work. But I don't know why this fails with the package task. It does work with the build task :-)

**Comment by dbaeumer** [comment]
I know why: the `gulp package` task calls `vsce package` which calls `npm run vscode:prepublish` which calls `npm run compile` which does a normal compile again replace the *.js file generated by the nls compiler. Simply remove the script and everything should work. However some observations:

For an extension you can simply do:

```
import * as nls from 'vscode-nls';
const localize = nls.loadMessageBundle();
```

which auto configures the NLS.

You can also checkout the lsp-sample we have here: https://github.com/Microsoft/vscode-extension-samples/tree/master/i18n-sample

**Comment by Brighttll** [comment]
@dbaeumer Thank you very much. Another question, the second argument of localize call must be a string literal, but I saved the text with default language(en) in a JSON file, is there any other way to load the default language text from JSON file to localize?  Thanks again!

var commandText = require('../../i18n/en/out/extension.i18n.json');
localize('sayHello.text', commandText.sayHello.text.en);

**Comment by dbaeumer** [comment]
Not sure I understand you. There is not need for you to load localization files by hand.

**Comment by Brighttll** [comment]
The second argument of localize is the default local text, I have to pass a exact string value for it. 
Do you mean it will load the default local text from JSON file? How to do it?

**Comment by Brighttll** [comment]
If the second argument is different as the default local text in the localization file, it will display the second argument value, not the text defined in the localization file.
