### ISSUE TITLE
CANNOT use API proposal: chatAgents2

### ISSUE THREAD

**Issue by shamas** [microsoft/vscode-extension-samples#937]
### Extension sample

chat-agent-sample

### VS Code version

1.85.1

### What went wrong?

I successfully ran the Hello World extension sample to get the process down. Following the steps of
1. `npm i` in terminal
2. Open the folder in VSCode
3. open extension.ts - F5 to open debugging vscode extension
4. Also tried adding `--enable-proposed-api vscode-samples.chat-agent-sample` to the code startup string - no change

Error message on load

> Activating extension 'vscode-samples.chat-agent-sample' failed: Extension 'vscode-samples.chat-agent-sample' CANNOT use API proposal: chatAgents2. Its package.json#enabledApiProposals-property declares: but NOT chatAgents2. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode-samples.chat-agent-sample.

**Comment by lukka** [comment]
@shamas FYI it worked for me using vscode insiders 1.86.0-insiders. [By reading the docs it looks like it is mandatory to use VSCode insiders](https://code.visualstudio.com/api/advanced-topics/using-proposed-api#using-a-proposed-api): one prerequisite is to _"Use [Insiders](https://code.visualstudio.com/insiders) release of VS Code."_

**Comment by roblourens** [comment]
Yes, please use Insiders
