### ISSUE TITLE
Cannot Launch Chat-Agent-Sample

### ISSUE THREAD

**Issue by sholtomaud** [microsoft/vscode-extension-samples#944]
### Extension sample

chat-agent-sample

### VS Code version

1.85.2

### What went wrong?

The co-pilot chat window did not contain the @cat or subcommands so it fails. Is there a way you can release these samples with tests?

**Comment by lukka** [comment]
@sholtomaud FYI it worked for me using vscode insiders 1.86.0-insiders. [By reading the docs it looks like it is mandatory to use VSCode insiders](https://code.visualstudio.com/api/advanced-topics/using-proposed-api#using-a-proposed-api): one prerequisite is to _"Use [Insiders](https://code.visualstudio.com/insiders) release of VS Code."_

**Comment by roblourens** [comment]
Yes, please use Insiders
