### ISSUE TITLE
is there any demo for DocumentCommentProvider/WorkspaceCommentProvider

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode-extension-samples#95]

**Comment by rebornix** [comment]
We don't have samples yet as it's still in proposed state and the APIs are very likely to change (not vastly but tiny changes here and there). We'll prepare code samples when we think it's in a good shape.

**Comment by mjbvz** [comment]
An example of using the VS Code 1.35 comment api is now available: https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample
