### ISSUE TITLE
Error compiling test-provider-sample executionCount does not exist on type StatementCoverage

### ISSUE THREAD

**Issue by warent** [microsoft/vscode-extension-samples#979]
### Extension sample

test-provider-sample

### VS Code version

1.87.0

### What went wrong?

Following the instructions here https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

It says the steps to get this running are:
```
> git clone https://github.com/microsoft/vscode-extension-samples.git
> cd vscode-extension-samples/lsp-sample
> npm install
> npm run compile
> code .
```

When I get to the compile step, it succeeds for a while but eventually hits an error and seems to abort
```
=== Running compile on test-provider-sample ===

> test-provider-sample@0.0.1 compile
> tsc -p ./

src/extension.ts:99:15 - error TS2339: Property 'executionCount' does not exist on type 'StatementCoverage'.

99      lineInfo.executionCount++;
                 ~~~~~~~~~~~~~~
```

I've tried this with both Node 18 and 20

**Comment by dbaeumer** [comment]
Not about lsp-sample.

**Comment by connor4312** [comment]
This'll be fixed as we finalize test coverage
