### ISSUE TITLE
How to broadcast an event to multiple extensions

### ISSUE THREAD

**Issue by Brighttll** [microsoft/vscode-extension-samples#99]
Is there a way to broadcast an custom event to other extensions? And is it possible to respond to the extension who fired the event?

**Comment by jrieken** [comment]
> Is there a way to broadcast an custom event to other extensions

No, what you can do is expose an api from your extension that others code against. See https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/vscode.d.ts#L4493-L4497

**Comment by mjbvz** [comment]
Closing as question
