### ISSUE TITLE
Authentication provider sample can't log out

### ISSUE THREAD

**Issue by kyswtn** [microsoft/vscode-extension-samples#991]
### Extension sample

authenticationprovider-sample

### VS Code version

1.87.2

### What went wrong?

1. Run the sample extension.
2. Sign in by running the command and filling in the PAT input.
3. Sign out from Accounts Menu > Personal Access Token (PAT).

<img width="534" alt="image" src="https://github.com/microsoft/vscode-extension-samples/assets/153218822/ede884f1-d548-4160-9459-51539ba4113d">

4. VSCode will say "Successfully logged out" but the item doesn't disappear.

![Screen Recording of Reported Behavior](https://github.com/microsoft/vscode-extension-samples/assets/153218822/5059d2c4-7d0a-4ed2-be25-635d09a25586)

**Comment by TylerLeonhardt** [comment]
Nice catch, I have a fix out for this.
